### ISSUE TITLE
In SpeechToTextV1.recognize(): Keyword argument 'word_confidence' is not propagated correctly to API

### ISSUE THREAD

**Issue by mpuels** [watson-developer-cloud/python-sdk#107]
In the method `SpeechToTextV1.recognize()` the keyword argument `word_confidence` is not propagated correctly to Watson's API. If I run `examples/speech_to_text_v1.py`, a JSON object is printed to my terminal as expected. But if I add `word_confidence=True` to the argument list, I get a warning in the returned JSON object. Here is the code before adding `word_confidence`:

    …
    with open(join(dirname(__file__), '../resources/speech.wav'), 'rb') as audio_file:
        print(json.dumps(speech_to_text.recognize(
            audio_file, content_type='audio/wav', timestamps=True), indent=2))
    …

Here it is after adding `word_confidence`:

    …
    with open(join(dirname(__file__), '../resources/speech.wav'), 'rb') as audio_file:
        print(json.dumps(speech_to_text.recognize(
            audio_file, content_type='audio/wav', timestamps=True, word_confidence=True), indent=2))
    …

Running the modified python file yields

    …
    "warnings": [
        "Unknown arguments: wordConfidence."
    …

If in [speech_to_text_v1.py](https://github.com/watson-developer-cloud/python-sdk/blob/59f21de85bbdec88d839f369ec8e53afa94a087f/watson_developer_cloud/speech_to_text_v1.py#L44) I replace the line

    'wordConfidence': word_confidence,

by

    'word_confidence': word_confidence,

then the warning in the returned JSON object vanishes and the confidence score for each word is included in it.

**Comment by jsstylos** [comment]
Thanks for the report -- the service used to support either `wordConfidence` or `word_confidence`, but currently only accepts `word_confidence`, so I'll change the SDK to use the new parameter naming.

**Comment by jsstylos** [comment]
Fixed in 1accfd069822924213625c8cf1d0bcfe35456585 (0.20.1 release)
