### ISSUE TITLE
Installation should not depend on pypandoc

### ISSUE THREAD

**Issue by jsstylos** [watson-developer-cloud/python-sdk#11]
Attempting to install without the pypandoc module installed results in the error:

    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
    warning: pypandoc module not found, could not convert Markdown to RST

**Comment by germanattanasio** [comment]
The problem is that `__init__.py` is not only holding the version that we need in `setup.py` but also things that need `requests` to be installed up front. 

I'm going to get the version from a variable in  `setup.py` and update the version everywere using bumpversion.
