### ISSUE TITLE
AlchemyLanguageV1: "anchorDate" not working correctly

### ISSUE THREAD

**Issue by elifriedman** [watson-developer-cloud/python-sdk#115]
AlchemyLanguageV1 ExtractDates request does not return any dates if `"anchorDate"` is in the `params` input parameter of `requests.request`. It should be in the `data` parameter.

**Comment by jsstylos** [comment]
I think it's more complicated than just whether or not it's in the params or data section -- I looked at this earlier, and there's some incompatibility with the way the Python requests library is encoding the parameters (spaces and colons) and the way the service is needing to accept it.

When looking at this again now I changed the code to pass the parameters in the data section for POST requests (which it probably should have been doing anyway, although the query parameters still worked), but I couldn't get this to solve the anchorDate problem.

**Comment by jsstylos** [comment]
See: http://stackoverflow.com/questions/21823965/use-20-instead-of-for-space-in-python-query-parameters

**Comment by jsstylos** [comment]
See also: http://stackoverflow.com/questions/42349000/python3-requests-use-quote-instead-of-quote-plus

**Comment by jsstylos** [comment]
The AlchemyLanguage service has been deprecated so closing this out.
