### ISSUE TITLE
Possible error in WatsonDeveloperCloudService request method

### ISSUE THREAD

**Issue by nilehmann** [watson-developer-cloud/python-sdk#131]
I think this line (https://github.com/watson-developer-cloud/python-sdk/blob/master/watson_developer_cloud/watson_developer_cloud_service.py#L261) is intended to say `full_url.startswith('https://gateway-a.watsonplatform.net/calls'):`. Anyways, at least for me it seems that calls work either with `api_key` or `apikey` in the `https://gateway-a.watsonplatform.net/calls/text/TextGetRankedNamedEntities` endpoint.

**Comment by jsstylos** [comment]
👍 Good catch. Fixed in 452f7992b9a2906f7f4933fa2a7e21c56ad94737
