### ISSUE TITLE
TypeError: get_news_documents() got an unexpected keyword argument 'next' 

### ISSUE THREAD

**Issue by andrew21c** [watson-developer-cloud/python-sdk#141]
When I run AlchemyDataNewsV1 query with added "next" argument, I got following error message,
TypeError: get_news_documents() got an unexpected keyword argument 'next'.  My python script:

results = alchemy_data_news.get_news_documents(start='now-1d', end='now',
                next = "MzY1MjY...",                                              
                return_fields=['enriched.url.title',
                               'enriched.url.url',
                               'enriched.url.author',
                               'enriched.url.publicationDate',
                               'enriched.url.text'
                               ],
                query_fields={
                    'q.enriched.url.enrichedTitle.entities.entity':
                    '|text=APPLE,type=company|'},
                                               )

The next string is what I get from first query result. Do you have an example to show how to use "next" argument? I want to print out all the query results.

Thanks.

**Comment by jsstylos** [comment]
In the Python SDK the next field should be passed as `next_page`.

**Comment by andrew21c** [comment]
Thanks. Then the document on your web seems to be outdated.
