### ISSUE TITLE
Pip release doesn't have create_configuration

### ISSUE THREAD

**Issue by enriquetolby** [watson-developer-cloud/python-sdk#149]
I'm using python sdk but there is no information in the API and some methods are not available. For example, using create_configuration:

![screenshot from 2017-02-03 12-56-09](https://cloud.githubusercontent.com/assets/10809216/22590650/79157df2-ea10-11e6-809e-37198a70f850.png)

**Comment by kognate** [comment]
You are correct about the 0.23 version not including create_configuration.  It's in master, and a new release will be prepared.

You can use the tooling to create new configurations as a work-around.

**Comment by kognate** [comment]
This shipped in the 0.24 version today.
