### ISSUE TITLE
Unable to import package

### ISSUE THREAD

**Issue by geetanjali10** [watson-developer-cloud/python-sdk#161]
I tried to run this code:

import sys
import os
sys.path.append(os.path.join(os.getcwd(),'..'))
import watson_developer_cloud
import watson_developer_cloud.nlu.features.v1 as features

but here it is showing: No module named 'watson_developer_cloud.nlu' 
Kindly help me with importing watson_developer_cloud.nlu.features.v1

**Comment by jsstylos** [comment]
The package name was changed to `natural_language_understanding`, the Python notebook example was fixed in 0812ef710cb38faed4797712616dfc06d47dccc8
