### ISSUE TITLE
Support for different models in AlchemyLanguageV1

### ISSUE THREAD

**Issue by scchow** [watson-developer-cloud/python-sdk#162]
Hi,
I am wondering if there is support for different models created by Watson Knowledge Studio. 

I was looking at the Watson Developer Cloud [documentation for AlchemyLanguage](https://www.ibm.com/watson/developercloud/alchemy-language/api/v1/?python#custom-models) and couldn't find the correct command if there is one.

To clarify, I have trained a model using Watson Knowledge Studio and am trying to deploy it through AlchemyLanguage as described [here](https://www.ibm.com/watson/developercloud/doc/wks/wks_mapublish.shtml).

Thanks for your help.

**Comment by kognate** [comment]
The deployment process is handled in the WKS tooling, not the api.  

Once you have deployed your WKS model you can reference that model ID in the endpoint that supports it (like Entities and typed relations).  The combined call does not allow you to specify a model ID.

**Comment by scchow** [comment]
Thank you so much. Was looking in the wrong place the whole time. 👍
