### ISSUE TITLE
Error importing library

### ISSUE THREAD

**Issue by belgort** [watson-developer-cloud/python-sdk#163]
I'm using the watson_developer_cloud Python library to experiment with Watson. I have used PIP to install the watson_developer_cloud. This appears to work. When I try this:

import watson_developer_cloud.natural_language_understanding.features.v1 as features

I get an error saying: ModuleNotFoundError: No module named 'watson_developer_cloud.natural_language_understanding'

Thanks for your help

**Comment by kognate** [comment]
What version of python and sdk are you using?

**Comment by belgort** [comment]
I used pip install and also pip —upgrade to get the latest.

**Comment by belgort** [comment]
Python is V3.6

**Comment by kognate** [comment]
I'm looking into this.  It works on python < 3.6 but I can replicate this on python 3.6 (which is odd)

**Comment by belgort** [comment]
Just installed in 3.5 and got same results:

https://www.dropbox.com/s/wwedzq8ewby33dq/Screenshot%202017-02-23%2008.54.25.png?dl=0 <https://www.dropbox.com/s/wwedzq8ewby33dq/Screenshot%202017-02-23%2008.54.25.png?dl=0>

https://www.dropbox.com/s/tjoiyr6zvkmp3ok/Screenshot%202017-02-23%2008.54.48.png?dl=0 <https://www.dropbox.com/s/tjoiyr6zvkmp3ok/Screenshot%202017-02-23%2008.54.48.png?dl=0>

**Comment by belgort** [comment]
Also, same after installing in 2.7

https://www.dropbox.com/s/0ojerfsacjfsb60/Screenshot%202017-02-23%2008.55.57.png?dl=0 <https://www.dropbox.com/s/0ojerfsacjfsb60/Screenshot%202017-02-23%2008.55.57.png?dl=0>

**Comment by kognate** [comment]
Thanks for reporting this.  I think I got it sorted.  And you are correct, this happens on everyone's machine but I couldn't replicate it locally at first because of me.  

When that PR get's reviewed we should be able to update the release and get that fixed.  

Thanks for your help @belgort

**Comment by belgort** [comment]
Excellent! Is there an anticipated release date? I won’t hold you too it.

**Comment by kognate** [comment]
I would expect tomorrow at the latest.

**Comment by belgort** [comment]
Thank you. 



Regards,

Bruce Elgort

**Comment by belgort** [comment]
Will the code also be updated on PIP?

**Comment by germanattanasio** [comment]
@jsstylos can you do
```sh
bumpversion patch
git push --tags
git push origin master
```

**Comment by jsstylos** [comment]
This should already be updated in 0.25.0 -- the only commit to happen since then is to the .ipynb file, and not directly related to the issue. Is the problem reproducible on 0.25.0?

**Comment by belgort** [comment]
I’m now getting credentials errors that were not occurring yesterday:

https://www.dropbox.com/s/6lp0r0kheohrztw/Screenshot%202017-02-24%2011.15.54.png?dl=0

**Comment by jsstylos** [comment]
The credentials issue seems likely unrelated to the update -- if you uninstall and pip install 0.24.0 do you still get a credentials issue?

**Comment by belgort** [comment]
On 0.24.0 I get this: https://www.dropbox.com/s/pjxej4wiml0r9kq/Screenshot%202017-02-24%2012.37.01.png?dl=0 <https://www.dropbox.com/s/pjxej4wiml0r9kq/Screenshot%202017-02-24%2012.37.01.png?dl=0>

**Comment by kognate** [comment]
@belgort you'll need to supply the URL to use the staging URL until the service is available on Monday.  Staging credentials won't work on the prod front end until the tile is up.

**Comment by belgort** [comment]
Where do I find this?

**Comment by kognate** [comment]
You should contact the OM or salesperson who gave you the staging credentials.

**Comment by belgort** [comment]
I did this all on my own through Bluemix. No one from IBM was involved. I’m so confused :(

**Comment by kognate** [comment]
Sorry for the confusion.  I assumed that since you were using the service you were given early access.  The NLU service is not released yet so you won't be able to use it until it is.  When it gets released, you'll be able to create a service instance in the Bluemix console and get credentials.  

The SDKs provide support for NLU ahead of the service launch for teams given early access.

**Comment by belgort** [comment]
Here is where I got started on Bluemix: https://www.dropbox.com/s/ksy0s69qi3zqmr4/Screenshot%202017-02-24%2012.43.44.png?dl=0 <https://www.dropbox.com/s/ksy0s69qi3zqmr4/Screenshot%202017-02-24%2012.43.44.png?dl=0>

**Comment by kognate** [comment]
OK,   That is the Natural Language Classifier service,  not the Natural Language Understanding service (I realize that may not help the problem, the names are _way_ too similar).

**Comment by belgort** [comment]
Ah and not seeing that on Bluemix. So wait until Monday for it to be available within Bluemix?

**Comment by immanuvelv** [comment]
@belgort I am facing exactly the same issue. i.e. when i run the below code in Spyder, i am getting the error as "ModuleNotFoundError: No module named 'watson_developer_cloud'". i used pip install as well as pip upgrade. 
code: from watson_developer_cloud import NaturalLanguageUnderstandingV1. 

Here is the twist, If i use the above code in IDLE it runs well. However, i run into wrong credential issue when using the below code. 

import watson_developer_cloud.natural_language_understanding.features.v1 as Features
natural_language_understanding = NaturalLanguageUnderstandingV1(
  username="{XXX-XXX-XXX-XXX-XXX}",
  password="{YYXXYYXX}",
  version="2017-02-27")

response = natural_language_understanding.analyze(
  text="IBM is an American multinational technology company headquartered \
    in Armonk, New York, United States, with operations in over 170 \
    countries.",
  features=[
    Features.Entities(
      emotion=True,
      sentiment=True,
      limit=2
    ),
    Features.Keywords(
      emotion=True,
      sentiment=True,
      limit=2
    )
  ]
)

Pls let me know if you have a workaround..

**Comment by 1788** [comment]
I'm using the watson_developer_cloud Python library for chatbot.
When I try this:
from watson_developer_cloud import ConversationV1

I get an error saying: ImportError: No module named watson_developer_cloud

Thanks for your help

**Comment by krtrth** [comment]
I am using aws lambda to write api for nlc so I can't pip install there any idea how can I do that

**Comment by ammardodin** [comment]
@krtrth You need to zip the library files. The process is described in the official aws [documentation](https://docs.aws.amazon.com/lambda/latest/dg/lambda-python-how-to-create-deployment-package.html)

**Comment by TOUIBIS** [comment]
i have the same problem in my raspberry pi 3 
ImportError: No module named 'watson_developer_cloud'
what can i do ???

**Comment by Harsha-Praneetha** [comment]
In a python file there is a statement as follows:
 from watson_developer_cloud import ConversationV1
conversation=ConversationV1(
username = ' my username',
password = ' my password',
version = '2017-05-26'
)

When I try to run the file in command prompt, it is showing an error as "cannot import name 'ConversationV1'

Python version: 3.5
How can this error be fixed?

**Comment by ehdsouza** [comment]
@Harsha-Praneetha which version of the SDK are you using?

We have deprecated the `ConversationV1`. You can now use the `AssistantV1`.

**Comment by Harsha-Praneetha** [comment]
Hello
Thank you so much for responding this soon

Sorry that I didn't get you. SDK version of what??
