### ISSUE TITLE
Include optional parameters in AlchemyVision examples

### ISSUE THREAD

**Issue by Decker87** [watson-developer-cloud/python-sdk#17]
There are a couple optional parameters to some AlchemyVision APIs that would be nice to include in the examples.  There's knowledgeGraph=(0|1) for GetRankedImageFaceTags and GetRankedImageKeywords, and forceShowAll=(0|1) for GetRankedImageKeywords.

**Comment by jsstylos** [comment]
Fixed in 8e657a
