### ISSUE TITLE
Speech to Text Cutting Off

### ISSUE THREAD

**Issue by belgort** [watson-developer-cloud/python-sdk#170]
Hello,

I'm using the Python Speech to Text API which is pretty awesome. I am however finding that it's cutting off after the first few words in this file:

https://www.dropbox.com/s/m3wngsqmidaj249/ibm.wav?dl=0

It cuts out after the first pause. Thank you as always for your awesome support.

Bruce

**Comment by jsstylos** [comment]
Hi Bruce, that sounds like an issue with the parameter `continuous`, which is set to `False` by default, but if you set it to `True` you'll get the expected behavior. (This is really an API design flaw, as `continuos=True` is the behavior most users want and expect, but because it's a breaking change, we're waiting until the next major release to fix it.)

**Comment by belgort** [comment]
Here is the code I use:

   data = json.dumps(speech_to_text.recognize(
        audio_file, content_type='audio/wav', timestamps=False,
        word_confidence=False,continuous=True),
        indent=2)

With continuous=True I’m still seeing the same behavior.

**Comment by jsstylos** [comment]
When I run the code:

```import json
from os.path import join, dirname
from watson_developer_cloud import SpeechToTextV1

speech_to_text = SpeechToTextV1(
    username='xxx',
    password='xxx'
)

with open(join(dirname(__file__), 'speech.wav'), 'rb') as audio_file:
    data = json.dumps(speech_to_text.recognize(audio_file, content_type='audio/wav', timestamps=False, word_confidence=False, continuous=True), indent=2)
    print(data)
```

I get the results:

```
{
  "results": [
    {
      "alternatives": [
        {
          "confidence": 0.893,
          "transcript": "today I have been playing with IBM Watson "
        }
      ],
      "final": true
    },
    {
      "alternatives": [
        {
          "confidence": 0.894,
          "transcript": "IBM Watson is a supercomputer me by the IBM corporation based in Armonk New York "
        }
      ],
      "final": true
    }
  ],
  "result_index": 0
}
```

This looks right to me (the service returns an array of results with one per utterance).

**Comment by kognate** [comment]
I posted the output I get here https://gist.github.com/kognate/d53ff23e1bf8885b536216e998925e02

I see both sentences in the file, 

"transcript": "today I have been playing with IBM Watson ",
          "transcript": "IBM Watson is a supercomputer me by the IBM corporation based in Armonk New York ",

Are you seeing a partial string, or one or more of these transcripts?

**Comment by belgort** [comment]
Thanks for this. I will move onto the next service and give it a try again later. I do appreciate your assistance. Thank you again.

**Comment by belgort** [comment]
This issue can be closed.
