### ISSUE TITLE
Error 400: Request to fetch blocked: disallowed

### ISSUE THREAD

**Issue by prateekpg2455** [watson-developer-cloud/python-sdk#180]
I have been trying to query Watson's NLU API. I have a paid version of API. It is giving me this error again and again.
```
USERNAME = '****'
PASSWORD  = '****'
from watson_developer_cloud import NaturalLanguageUnderstandingV1
import watson_developer_cloud.natural_language_understanding.features.v1 as features

NLU = NaturalLanguageUnderstandingV1(version = '2017-02-27',username = USERNAME, password = PASSWORD)

url = 'www.cynopsis.com/031617-fox-turner-and-viacom-team-to-untangle-audience-targeting-fx-orders-season-2-of-legion-hbo-keeps-crashing/'
Categories = features.Categories()
response = NLU.analyze(url =url, features =[ Categories ], \
                                   return_analyzed_text = True)
```
It keeps on giving me error:
```
WatsonException: Error: request to fetch blocked: disallowed, Code: 400
```

**Attempts to solve the above problem:**

1. After using python debugger, I found that the request going out from above has the 'data' parameter which is a string. 

```
'{"url": "www.cynopsis.com/031617-fox-turner-and-viacom-team-to-untangle-audience-targeting-fx-orders-season-2-of-legion-hbo-keeps-crashing/", "clean": true, "features": {"categories": {}}, "fallback_to_raw": true, "return_analyzed_text": true}'
```

Request's documentation says that data is a dict or tuple, bytes, or file-like objects. I am not sure if string form above will fall into any of the above categories. 

2. I used json instead of data. 

```
requests.request(method='POST', url=full_url, params = params, headers=headers, json=json, auth=auth)
```
Same error

**Comment by kognate** [comment]
That error looks like it's comming from the site.  Can you verify the robots.txt allows this kind of fetch?

**Comment by prateekpg2455** [comment]
Where can I find that?

**Comment by jsstylos** [comment]
From http://www.cynopsis.com/robots.txt it looks like programmatic is disabled except for certain user agents, so I think this is the Natural Language Understanding service being a good robot citizen, although the error message wording could probably be a little clearer.

**Comment by prateekpg2455** [comment]
Natural Language Understanding is a good robot citizen but not Alchemy API, but it is going to be deprecated soon.

**Comment by jsstylos** [comment]
You can choose not to be a good citizen and use a white-listed user-agent to programmatically fetch the page and pass it to the service; other than that (or requesting the site to provide a more lenient robots.txt), I'm not sure what else to suggest.
