### ISSUE TITLE
 Natural Language Understanding Example With URL Returns Exception

### ISSUE THREAD

**Issue by mikayla-grace** [watson-developer-cloud/python-sdk#182]
Using natural_language_understanding_v1.py with a URL against a Bing news RSS feed returns this exception:

```
watson_developer_cloud.watson_developer_cloud_service.WatsonException: Error: attempt to fetch failed: :closed, Code: 400
```
Some other URL's work fine.  Here is the relevant call:

```
response = nlu.analyze(url='https://www.bing.com/news/search?q=IBM+Watson&format=RSS',
  return_analyzed_text=True,
  features=[features.Entities(), features.Keywords()])
```

**Comment by kognate** [comment]
The `robots.txt` file at https://www.bing.com/robots.txt appears to block robots from `/news/search?`.  

Sorry the error message isn't more clear.  

Related to #18

**Comment by mikayla-grace** [comment]
I can see where it might fail if you are crawling the website but in this case we're analyzing just one web page.  Python's ```requests.get()``` can download single page results from Bing news as well as ```curl``` and ```wget```.   We could use Python's ```requests.get()``` extension to download the page ourselves and pass the contents to NLU as text, but our preference is to pass a URL to NLU and let it do the work.  If we can download the page with ```requests.get()``` why can't Watson's NLU get the page?

**Comment by kognate** [comment]
Python requests doesn't check the `robots.txt' so  I think this is the Natural Language Understanding service being a good robot citizen, although the error message wording could probably be a little clearer.  

You can choose not to be a good citizen and use a white-listed user-agent to programmatically fetch the page and pass it to the service; other than that (or requesting the site to provide a more lenient robots.txt), I'm not sure what else to suggest.

**Comment by mikayla-grace** [comment]
Thanks, we'll extract the direct URL from Bing / Google News and go directly to the news source.  They likely will have a friendly robots.txt file NLU can fetch from.
