### ISSUE TITLE
Add ability to escape special characters when querying discovery

### ISSUE THREAD

**Issue by rchaks** [watson-developer-cloud/python-sdk#185]
### Current behavior
When using the sdk to query a discovery instance, I currently have to manually escape special characters from the query string before passing it to the API like so:

```py
discovery.query(
  environment_id=e_id,
  collection_id=c_id,
  query_options={
    'query': escape_special_tokens_for_discovery_syntax(query_text)
  }
)
```
### Desired behavior
It would be nice to have the option to include a flag or something that would auto-escape the special query operators from the query text.

### Reason for Suggesting the Feature
Often the query text is coming from user input and, thus, can contain whatever special characters they chose to type in...every user of this sdk will have to write up their own auto-escape logic. Also, it is possible to misinterpret the [documentation](https://www.ibm.com/watson/developercloud/doc/discovery/query-reference.html) and think that periods have to escape when, in fact, escaping them causes an un-interpretable error.

**Comment by jsstylos** [comment]
Good suggestion. We should figure out how to coordinate the escaping across SDKs. I think always escaping is probably reasonable behavior -- right now there's no use case (that we'd want to support) that includes passing special characters without having them escaped.

**Comment by germanattanasio** [comment]
Could this be related to #337

**Comment by germanattanasio** [comment]
@rchaks Since you already wrote the function would you mind creating a PR for this?
