### ISSUE TITLE
Add ability to create the free Discovery environment in a trial account

### ISSUE THREAD

**Issue by markstur** [watson-developer-cloud/python-sdk#186]
To create the freebie Discovery environment, I need to call create_environment(..., size=0).
But the SDK currently has a check that requires size of 1, 2 or 3.
It seems zero should be allowed to enable auto-deployment of example Discovery apps to trial accounts.

**Comment by jsstylos** [comment]
Are you using 0.25.2? This was (hopefully) fixed in the latest release.

**Comment by markstur** [comment]
Yeah. Turns out we were pinned to 0.25.1.  Sorry. Not tested, but the code seems to be fixed.
