### ISSUE TITLE
Add more documentation

### ISSUE THREAD

**Issue by germanattanasio** [watson-developer-cloud/python-sdk#2]
I ran `pylint` and got:

<img width="490" alt="screen shot 2015-10-08 at 3 59 45 pm" src="https://cloud.githubusercontent.com/assets/313157/10378213/a2278252-6dd5-11e5-851f-f22b40bbf675.png">

We probably want to focus on documentation and test cases

**Comment by bvonhag** [comment]
Did you run this against the new Python "wrapper" code? That GitHub project is the only place the Python whatever-we-call-them lives at the moment, right?

**Comment by germanattanasio** [comment]
yes

**Comment by germanattanasio** [comment]
I love the `whatever-we-call-them` part aahaha
