### ISSUE TITLE
pip install after bump to 0.26.0 now requires compiler for cffi (may be intentional?)

### ISSUE THREAD

**Issue by erikjasiak** [watson-developer-cloud/python-sdk#203]
All containers that I used to run "pip install watson-developer-cloud" broke this afternoon - the containers were intentionally built without a compiler.

Looks like the bump to 0.26.0 [earlier today](https://github.com/watson-developer-cloud/python-sdk/releases) requires cffi>1.4.1, which either requires a working compiler to install or has invalid flags being passed to it.

Changing containers to "RUN pip3 install watson_developer_cloud==0.25.2" gets around the issue.

Is there any way to get a pip install of wdc without needing a c compiler?

Output:
`
Step 5/8 : RUN pip3 install watson_developer_cloud
 ---> Running in 2c8b6af7986b
Collecting watson_developer_cloud
  Downloading watson-developer-cloud-0.26.0.tar.gz (66kB)
`

further down: 

`
Collecting cffi>=1.4.1 (from cryptography>=1.7->pyOpenSSL>=16.2.0->watson_developer_cloud)
  Downloading cffi-1.10.0.tar.gz (418kB)
    Complete output from command python setup.py egg_info:
`

`
        No working compiler found, or bogus compiler options
        passed to the compiler from Python's distutils module.
        See the error messages above.
        (If they are about -mno-fused-madd and you are on OS/X 10.8,
        see http://stackoverflow.com/questions/22313407/ .)
`

Thanks!

**Comment by erikjasiak** [comment]
It seems the cffi requirement came along with the addition of pyOpenSSL:
[Commit 1](https://github.com/watson-developer-cloud/python-sdk/commit/b7174920a6c5c33f2955eda4be257816368688c5)
[Commit 2](https://github.com/watson-developer-cloud/python-sdk/commit/8129da18b4fac3af17a20d82a44973375221d90e)

[pyOpenSSL requires cryptography](https://pyopenssl.readthedocs.io/en/stable/install.html#) (see "warning")

cryptography seems to make its [compiler requirement clear](https://cryptography.io/en/latest/installation/#building-cryptography-on-linux)  even for pip installs.

SSL support is a nice feature, and I have access to pre-compiled ssl libraries; any alternative options than adding a compiler suite to our images that use wdc?

**Comment by jsstylos** [comment]
Thanks for the heads up. We saw issues with not requiring an SSL library in some but not all environments, but it's good to know that requiring it has issues. We're looking into this but the options seem to be:

a) Remove pyOpenSSL requirement, fixing this issue but regressing on the SSL one (which is more common? not sure yet)
b) Try to find another SSL library without cffi dependency (so far no luck, but any options would be useful to know about)
c) Leave pyOpenSSL requirement, not fixing this issue

Any other suggestions would be useful.

**Comment by erikjasiak** [comment]
Thanks for the reply - that about covers it.  I'll see if I can dive into exploring any of those later this evening.

Only other option I'm exploring is a workaround using [MultiStage builds in docker](https://docs.docker.com/engine/userguide/eng-image/multistage-build/), which I'm happy to share instructions for if it works.  But those are very new and clearly a Docker-focused solution.

**Comment by jsstylos** [comment]
This doesn't seem to be a widespread problem, so closing.
