### ISSUE TITLE
is it possible to add credentials files for bluemix ? 

### ISSUE THREAD

**Issue by MourIdri** [watson-developer-cloud/python-sdk#211]
Is it possible to have a credentials files like aws has ? 
then I could import my Api key directly from my credentials on a service basis ? ( visu rec, speetch to text etc..)

**Comment by kognate** [comment]
If you bind your service to your application,  the SDK will get the service credentials out of the vcap environment.

Or are you looking to do this with an Unbound service?

**Comment by jsstylos** [comment]
Currently the only way to load a collection of credentials at once is by setting them to the `VCAP_SERVICES` environment variable, which happens automatically on Bluemix but can be done manually in other environments.

We've talked but not yet implemented a feature where you could load a credentials file directly with a command to the SDK, which would have the same effect as if you had set the environment variable. Would this be what you're looking for?

**Comment by MourIdri** [comment]
@jsstylos : and after loading my credentials (mail + password ) to that file, a command in the sdk would do something like "
- "./get_watson_apis -show_visu_rec_api" => show my keys
-"./get_watson_apis -create_visu_rec" => create and return the newly created key. 
The idea is to basically to manipulates the keys for a given watson service directly from the sdk based on my credentials.

**Comment by germanattanasio** [comment]
You can't manipulate the credentials from the SDK. You need to do it from Bluemix which is where you get the credentials.

**Comment by markstur** [comment]
Loading VCAP_SERVICES from a file as mentioned above would be nice. Basically, I often want to export them (as JSON) and it is not easy to turn that into an env for local testing. But to slurp that json in from a file would be handy.

**Comment by germanattanasio** [comment]
@lpatino10 ☝️

**Comment by germanattanasio** [comment]
@ehdsouza can you look into this? We already have `dotenv` so it will only means adding some code to load the credentials as we load them from `VCAP_SERVICES`

**Comment by ehdsouza** [comment]
Similar implementation has been done in https://github.com/watson-developer-cloud/python-sdk/releases/tag/v2.7.0
