### ISSUE TITLE
Asynchronous STT support?

### ISSUE THREAD

**Issue by rclough** [watson-developer-cloud/python-sdk#212]
Hello, I'm currently trying out the speech-to-text API, and was wondering if there is an implementation of the [asynchronous version of the API](https://www.ibm.com/watson/developercloud/speech-to-text/api/v1/?curl#async_methods) for the python client? It's definitely not documented in the examples, and perusing the SDK code by hand seems to suggest this is not yet implemented.

**Comment by kognate** [comment]
The python sdk doesn't support that api endpoint right now (but we welcome PRs).

**Comment by rclough** [comment]
Cheers, I'm going to move forward synchronously for now, but if I end up productionizing my project I'll probably have to add it; happy to submit a PR if that ends up being the case.

**Comment by hswick** [comment]
Asynchronous support would be really helpful. Could probably just switch out requests with aiohttp

**Comment by germanattanasio** [comment]
@hswick the problem with `aiohttp` is that it works with Python >= 3.4.  `requests` works with Python >= 2.7 .

**Comment by DarBeck** [comment]
I created a STT using WebSocket connection. Its not in a class as yet but you will get the idea. Her is the git:
https://github.com/DarBeck/realtime_stt_watson/blob/master/real_time_transcript.py

**Comment by ehdsouza** [comment]
Speech to text support using websocket has been added in PR: https://github.com/watson-developer-cloud/python-sdk/pull/376 which would be released in V1.1.0 coming shortly
