### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 73: character maps to <undefined>

### ISSUE THREAD

**Issue by rushikesh988** [watson-developer-cloud/python-sdk#213]
Hello ,I am trying a document converter example given at [https://www.ibm.com/watson/developercloud/document-conversion/api/v1/#convert-document](https://www.ibm.com/watson/developercloud/document-conversion/api/v1/#convert-document).  

It it throwing an error "UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 73: character maps to <undefined>"

I am using following code
```
import json
from watson_developer_cloud import DocumentConversionV1
document_conversion = DocumentConversionV1(
  username='<MY USERNAME>',
  password='<MY PASSWORD>',
  version='2015-12-15'
)
config = {
  'conversion_target': 'ANSWER_UNITS',
  'word': {
    'heading': {
      'fonts': [
        {'level': 1, 'min_size': 24},
        {'level': 2, 'min_size': 16, 'max_size': 24}
      ]
    }
  }
}

with open(('testDoc.docx'), 'r') as document:
  response = document_conversion.convert_document(document=document, config=config)
  print(json.dumps(response, indent=2))

```
Any suggestion where I might be getting wrong?

**Comment by rushikesh988** [comment]
I am using Python 3.6 .

**Comment by germanattanasio** [comment]
@rushikesh988 do you have the document handy?

**Comment by rushikesh988** [comment]
Thanks for reply . Here is that document.

[samplePDF.pdf](https://github.com/watson-developer-cloud/python-sdk/files/1189918/samplePDF.pdf)

**Comment by ehdsouza** [comment]
Hi,

Read the file as a binary file and it should work.

``` python
with open(('testDoc.docx'), 'rb') as document:
  response = document_conversion.convert_document(document=document, config=config)
```
