### ISSUE TITLE
Python SDK using deprecated feature

### ISSUE THREAD

**Issue by rclough** [watson-developer-cloud/python-sdk#215]
Library: Speech to Text

Noticed some warnings in our responses regarding the use of a parameter "continuous" that we did not explicitly set. When researching, I found [this reference](https://www.ibm.com/watson/developercloud/doc/speech-to-text/release-notes.html) in the release notes from last week (Titled May 22nd).

If it is advisable, I'd happily contribute a simple PR to remove it from the recognize method: https://github.com/watson-developer-cloud/python-sdk/blob/master/watson_developer_cloud/speech_to_text_v1.py#L30-L57

**Comment by jsstylos** [comment]
Good catch @rclough, a pull request would be great.

**Comment by jsstylos** [comment]
035dac5214931ec90b6806ee9423c5035efc026c changes the default to `None` which will prevent it from getting passed by default. I haven't moved it out of the method so as not to break any current users by causing the parameters to be reordered, but not passing the parameter unless it's explicitly set should solve the majority of the problem.
