### ISSUE TITLE
[Conversation] Allow workspace creation from single JSON object

### ISSUE THREAD

**Issue by data-henrik** [watson-developer-cloud/python-sdk#216]
Right now create_workspace requires the individual parts to be passed in as parameters. When I load a JSON file it is much simpler to just pass in the entire object.

Use cases where workspaces are created:
https://github.com/data-henrik/watson-conversation-tool
https://github.com/data-henrik/bluemix-egobot

**Comment by germanattanasio** [comment]
@data-henrik can you write a PR ?

**Comment by data-henrik** [comment]
Should be possible, after the vacation.

**Comment by data-henrik** [comment]
I looked into it and I will close my request.

* The Conversation API itself requires the individual parts.
* Having a similar Python API hence is ok.
* It requires some more processing for the API user, but it has the benefit of checking all required data is really present.
* Having a single API function only outweighs the gained comfort of above request.
