### ISSUE TITLE
WatsonException: Error: This 8000hz audio input requires a narrow band model.

### ISSUE THREAD

**Issue by ZuluagaSD** [watson-developer-cloud/python-sdk#220]
I'm trying to use the Speech-to-text API using a file that has a 256kbps bit rate (I don't know much about audio files)

![image](https://cloud.githubusercontent.com/assets/1851696/26832314/af884ef2-4a94-11e7-9a56-3fd90218135b.png)

And this is the error that I'm getting:
`WatsonException: Error: This 8000hz audio input requires a narrow band model.  See https://stream.watsonplatform.net/speech-to-text/api/v1/models for a list of available models., Code: 400`

I'm using the code from the examples:

`import json`
`from os.path import join, dirname`
`from watson_developer_cloud import SpeechToTextV1`

`speech_to_text = SpeechToTextV1(`
`    username='SECRET',`
`    password='SECRET',`
`    x_watson_learning_opt_out=False)`

`# I have tried using the es-ES_BroadbandModel as well as the es-ES_NarrowbandModel`
`print(json.dumps(speech_to_text.get_model('es-ES_NarrowbandModel'), indent=2))`

`with open('84368.wav', 'rb') as audio_file:
    print(json.dumps(speech_to_text.recognize(
        audio_file, content_type='audio/wav', timestamps=True,
        word_confidence=True),
        indent=2))`

**Comment by kognate** [comment]
You'll need to downsample the audio file to match the model you want to use.  https://stackoverflow.com/questions/30619740/python-downsampling-wav-audio-file. Discussions on how to do that ilusing scipy

**Comment by ZuluagaSD** [comment]
Hey kognate!
Thank you so much for your answer, I'm running the code suggested in that discussion but I'm not sure about the output parameter that I need.

```python
class DownSample():
    def __init__(self):
        self.in_rate = 8000.0 # I put 8000 because I think thats what my input file is
        self.out_rate = 16000.0 # Not sure about this one, what do I need to put here?
```

**Comment by ehdsouza** [comment]
Hey,

You would need to specify the sampling rates for your audio correctly. For more info have a look here: https://www.ibm.com/watson/developercloud/doc/speech-to-text/input.html#formats

Marking the issue closed, feel free to open if need be.
