### ISSUE TITLE
Delete Counter Example Error: Resource not found, Code: 404

### ISSUE THREAD

**Issue by entheos37** [watson-developer-cloud/python-sdk#227]
I want to delete the counter example, but I got this error message.

```watson_developer_cloud.watson_developer_cloud_service.WatsonException: Error: Resource not found, Code: 404```

```
conversation.delete_counterexample(workspace_id, text_deleted)
--> This does not work. 
```
```
conversation.list_counterexamples(workspace_id, include_count=True)
```
--> This does work well. I can list the counter examples. 

How can I delete the counter example?

**Comment by ehdsouza** [comment]
Hi, 
Make sure you have added the correct workspace_id before running the code. It worked for me, so marking the issue closed.

Feel free to reopen in case the problem still exists.
