### ISSUE TITLE
Rate Limit Error Handling for Conversation

### ISSUE THREAD

**Issue by ckuzma** [watson-developer-cloud/python-sdk#228]
When rate limited by Conversation, the error thrown by the SDK is vague:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/watson_developer_cloud/conversation_v1.py", line 109, in create_workspace
    accept_json=True)
  File "/usr/local/lib/python3.6/site-packages/watson_developer_cloud/watson_developer_cloud_service.py", line 320, in request
    raise WatsonException(error_message)
watson_developer_cloud.watson_developer_cloud_service.WatsonException: Unknown error
```

cURL reveals the actual service response to be this (as plain text):
```
Rate limit exceeded
```

Would be nice if the SDK gave a more meaningful error message, or if the service itself returned a response that matched the error formatting used by some of the other events, such as maximum workspaces exceeded:
```
{"error":"Maximum workspaces limit exceeded. Limit = 20"}
```

**Comment by jsstylos** [comment]
Thanks for bringing this to our attention. This should be fixed in an upcoming service update.

**Comment by victorzhao1990** [comment]
Does the sdk support the header info about rate limiting? I don't see the header available in either python response or the cURL/Postman response. 
Ref: https://www.ibm.com/watson/developercloud/conversation/api/v1/?curl#rate-limiting

**Comment by jsstylos** [comment]
This is being actively looked at again, still (!) expected to be coming in an upcoming release.
