### ISSUE TITLE
where is Watson's training dataset 

### ISSUE THREAD

**Issue by iamharshit** [watson-developer-cloud/python-sdk#229]
Is the dataset on which Ibm watson(for emotional analysis) is trained on available online ?

Sorry, if this isn't the right place, can you direct me the correct person or team?

**Comment by germanattanasio** [comment]
The training data for emotional analysis is not public.

**Comment by iamharshit** [comment]
Thanks for replying, just a last query

Is the sentiment analysis dataset public?

**Comment by germanattanasio** [comment]
No @iamharshit it's not
