### ISSUE TITLE
Can't import alchemy-related classes from sdk

### ISSUE THREAD

**Issue by boxcarton** [watson-developer-cloud/python-sdk#23]
After using 'pip install --upgrade watson-developer-cloud' in my virtualenv

```
from watson_developer_cloud import AlchemyLanguageV1
```

results in **'ImportError: cannot import name 'AlchemyLanguageV1'**

but 

```
from watson_developer_cloud import SpeechToTextV1 
```

works fine.

This is the case for both python 2.7 and python 3.5.

**Comment by jsstylos** [comment]
Hi Josh, thanks for the report. Support for Alchemy API services had not yet be published to pip, although the code for it existed in the repository. I just released a new version, so if you try again it should work.
