### ISSUE TITLE
Allow developers to choose the return type ('json', 'xml') for services like "Relationship Extraction"

### ISSUE THREAD

**Issue by tanmayb123** [watson-developer-cloud/python-sdk#24]
This is not an issue, I just wanted to bring this up as an enchancement: If you see the file "relationship_extraction_v1_beta.py", you can see that "'rt': 'xml'" is hardcoded.

This means that this service will ALWAYS return "XML" as its format. However, I prefer using JSON, and other developers have their own preferences, so I propose a solution: Just let the developer choose which Data Type they prefer! We can do this by adding "rt" or "return_type" as one of the parameters passed into the "extract" function of the class.

**Comment by jsstylos** [comment]
Thanks for the proposal. Release 0.3.3 adds this.
