### ISSUE TITLE
Document Conversion API not working in Windows 10 environment for word to html, Text to HTML etc

### ISSUE THREAD

**Issue by itsdeepakrai** [watson-developer-cloud/python-sdk#244]
The command works fine in MAC and linux , but its not working in a Windows environment .

**Comment by germanattanasio** [comment]
Which command? can you provide some steps to reproduce the issue?

**Comment by ehdsouza** [comment]
Steps to reproduce the issue would be very helpful. I just ran the test for document conversion on Windows and it worked.
```
C:\Users\Erika Dsouza\python-sdk>pytest test/test_document_conversion_v1.py
============================= test session starts =============================
platform win32 -- Python 3.6.2, pytest-3.1.3, py-1.4.34, pluggy-0.4.0
rootdir: C:\Users\Erika Dsouza\python-sdk, inifile:
plugins: cov-2.5.1
collected 1 item s

test\test_document_conversion_v1.py .

========================== 1 passed in 0.25 seconds ===========================```

**Comment by itsdeepakrai** [comment]
import json

from watson_developer_cloud import DocumentConversionV1

document_conversion = DocumentConversionV1(

username='f73212bb-1b2b-4b05-b218-f1b86e8ed289',

password='TBJKCdRLHQ6C',

version='2015-12-15'

)

config = {'conversion_target': DocumentConversionV1.NORMALIZED_TEXT}

with open(('C:/Users/Dell/Desktop/Sample.pdf'),encoding='latin-1') as document:

response = (document_conversion.convert_document(

document=document, config=config, media_type='application/pdf').content)

print(response)

***********************************************************************************************************************************

**Comment by ehdsouza** [comment]
Hi,

Could you read the file as a binary file which should work.
```
with open('C:/Users/Dell/Desktop/Sample.pdf', "rb") as document:
  config = {'conversion_target': DocumentConversionV1.NORMALIZED_TEXT}
  response = document_conversion.convert_document(document=document, config=config, media_type='application/pdf').content
  print(response)
```

**Comment by germanattanasio** [comment]
The problem is that you are reading the file as a text file and it's a pdf. @ehdsouza's code snippet should fix the problem
