### ISSUE TITLE
Creating a Job

### ISSUE THREAD

**Issue by pmbaumgartner** [watson-developer-cloud/python-sdk#245]
I'm getting the same issue as #204 when I attempt to create a job, resulting in `ConnectionError: ('Connection aborted.', OSError("(32, 'EPIPE')",))
`. My file is an mp3 under 100 MB.

Here's the code in raw python (without the SDK).
```python
print(os.path.getsize('./output.mp3') / (1024*1024.0), "MB")
>>> 5.910395622253418 MB
headers = {'Content-Type' : 'audio/mp3'}
data = open('./output.mp3', 'rb').read()
auth = (user, pass)
recognitions_url = "https://stream.watsonplatform.net/speech-to-text/api/v1/recognitions"
r = requests.post(url=recognitions_url,
                    data=data,
                    headers=headers,
                    auth=auth)
```

I also tried by subclassing SpeechToTextV1 and modifying its `recognize` method to just change the url to `/v1/recognitions`, with the same effect. I also tried
```python
with open('./output.mp3', 'rb') as audio_file:
    r = requests.post(url=recognitions_url,
                    data=audio_file,
                    headers=headers,
                    auth=auth)
```

I'm getting the `ConnectionError` regardless.

**Comment by ehdsouza** [comment]
Hi,

Could you enable logging for requests and paste the output here.
import requests
import logging
logging.basicConfig(level=logging.DEBUG)

**Comment by jsstylos** [comment]
Hi @pmbaumgartner,

As you've probably noticed the Python SDK doesn't currently support asynchronous recognition jobs. Have you tried the file with the synchronous `speech_to_text.recognize()` and does that also give a connection error?

**Comment by ehdsouza** [comment]
Closing this due to no response @pmbaumgartner
