### ISSUE TITLE
TypeError: analyze() got multiple values for keyword argument 'features'

### ISSUE THREAD

**Issue by vkg70** [watson-developer-cloud/python-sdk#247]
response = natural_language_understanding.analyze(text_to_process, features=[Features.Entities()])

TypeError: analyze() got multiple values for keyword argument 'features'

How should the analyze function be invoked with the dict parameter. Tried many combinations none of them work even with the example code.

**Comment by jsstylos** [comment]
The `features` parameter is the first in the list, so you need `text=text_to_process`

**Comment by vkg70** [comment]
Thanks
