### ISSUE TITLE
Not getting a response back from an example tutorial

### ISSUE THREAD

**Issue by TimKanake** [watson-developer-cloud/python-sdk#249]
I am new to using the Watson service and am facing some inconsistencies while testing it out. Yesterday I ran the speech_to_text_v1.py file from the examples folder using my credintials and got a response back. However, I have been trying to do it today and I don't seem to be getting a response back. I am running the .py file from the command prompt and it seems to hang once it gets to opening the file.

Could someone please help me figure out what the problem might be? It's probably something small that as a newbie I don't know.

**Comment by ehdsouza** [comment]
Hi,

I just ran the  speech_to_text_v1.py file and it works well. Make sure your environment is set correctly for example proper internet connection.

**Comment by blacknred0** [comment]
@TimKanake are you paying for BlueMix service? I think this one has 30 days trial.  Make sure that yours hasn't expired.

**Comment by TimKanake** [comment]
@blacknred0 I started paying for the account so that wasn't the problem. I figured it out though. Thank you. @ehdsouza Thank you for the tip. I had a small bug but now it seem to be working fine.
