### ISSUE TITLE
calling watson developer cloud in jupyter notebook

### ISSUE THREAD

**Issue by soundaryalaharik** [watson-developer-cloud/python-sdk#251]
I have executed the pip install command in the anaconda folder and it was successful. Still when i open a jupyter notebook and import watson_developer_cloud it gives the below error:

ModuleNotFoundError: No module named 'watson_developer_cloud'

**Comment by ehdsouza** [comment]
I don't think this is a problem with the sdk as you were able to successfully install it with pip. Maybe some problem with your environment?

**Comment by ses1430** [comment]
Check whether you install another python.

**Comment by blacknred0** [comment]
@soundaryalaharik I would check that when you are opening jupyter you are calling the right kernel with watson_developer_cloud

**Comment by ehdsouza** [comment]
I'm closing this as it's not a problem with the SDK
