### ISSUE TITLE
Remove deprecated argument 'continuous' from speech_to_text_v1.recognize

### ISSUE THREAD

**Issue by sheikhfaisalanwar** [watson-developer-cloud/python-sdk#252]
https://console.bluemix.net/docs/services/speech-to-text/release-notes.html#relnotes

Continuous argument is longer supported. Remove it so we don't get:
` "warnings": [
  "Unknown arguments: continuous."
]`

**Comment by jsstylos** [comment]
This was changed in 035dac5214931ec90b6806ee9423c5035efc026c and will be fixed in the next release. To prevent being a breaking change the `continuous` argument still exists, but has a default value of `None` so that it doesn't generate this warning.
