### ISSUE TITLE
Speaker Labels in Python

### ISSUE THREAD

**Issue by belgort-clark** [watson-developer-cloud/python-sdk#253]
Are speaker labels currently supported in Python? I tried using features.Speakers() with no luck.

**Comment by ehdsouza** [comment]
Hi @belgort-clark,

Could you provide code for what you are trying to do?

There is a speaker_labels parameter in recognize(), if thats what you are looking out for?

**Comment by belgort-clark** [comment]
Erika, I just figured out what I was doing wrong. Dumb mistake on my part. Thank you for the reply. This can be closed.
