### ISSUE TITLE
this benchmark shows very slow response time for the STT service using the python SDK.

### ISSUE THREAD

**Issue by daniel-bolanos** [watson-developer-cloud/python-sdk#257]
benchmark: https://blog.recast.ai/benchmarking-speech-recognition-api/

Can you guys please take a look at response times? I wonder if there is an issue in the SDK since I have been able to talk to STT from python with very good response times (https://github.com/watson-developer-cloud/speech-to-text-websockets-python) 

thanks

**Comment by germanattanasio** [comment]
The only difference between your repository and this SDK is that your repository uses WebSocket. We use the requests library and send the audio to the service directly.
