### ISSUE TITLE
[discovery] create_collection and test_document retrieves wrong default configuration

### ISSUE THREAD

**Issue by maniax89** [watson-developer-cloud/python-sdk#258]
## Description

The `POST /collections` endpoint allows you to specify some parameters in the body:
  
https://watson-api-explorer.mybluemix.net/apis/discovery-v1#!/Collections/createCollection

```
{
  "name": "",
  "description": "",
  "configuration_id": "",
  "language": "en"
}
```

All elements are `optional` (only one that should be updated to `required` I believe is `name`). If you do not specify a `configuration_id`, the service uses the default configuration. However, in this SDK, if a `configuration_id` is not provided, it retrieves a list of the configurations and looks for one with the name `Default Configuration`:

https://github.com/watson-developer-cloud/python-sdk/blob/master/watson_developer_cloud/discovery_v1.py#L131-L142

This also occurs in the `test_document` method.

## Proposed Solution

Remove the `get_default_configuration` method entirely and all references to it. Let the service decide what the default configuration is (configuration is always `optional`)

**Comment by jsstylos** [comment]
Good idea, should be fixed in 13f4f5312ed752d7a52533f871c5ebed83e5ab9a
