### ISSUE TITLE
Segmentaion fault

### ISSUE THREAD

**Issue by DuyTrandeLion** [watson-developer-cloud/python-sdk#260]
Hello,

After I tried "pip install --upgrade watson-developer-cloud" but at the end it said segmentation fault. Anyone know how to fix it? Thank you very much.

There are the final lines: 
  Using cached enum34-1.1.6-py2-none-any.whl
Collecting pycparser (from cffi>=1.7->cryptography>=1.9->pyOpenSSL>=16.2.0->watson-developer-cloud)
Installing collected packages: six, asn1crypto, ipaddress, pycparser, cffi, enum34, idna, cryptography, pyOpenSSL, urllib3, chardet, certifi, requests, pysolr, watson-developer-cloud
Segmentation fault

**Comment by ehdsouza** [comment]
Hi,

Segmentation fault would be because of your environment issue. You could try updating the ulimit:
ulimit -s <new_val>

To check your previous value:
ulimit -s

**Comment by DuyTrandeLion** [comment]
Thank you for your reply. I tried to update the new ulimit but the same mistake still occurred. I even tried to update the new python but it also failed.

**Comment by ehdsouza** [comment]
This is an environment issue, hence closing.
