### ISSUE TITLE
Jumps missing while updating workspaces

### ISSUE THREAD

**Issue by sandlis** [watson-developer-cloud/python-sdk#264]
I tried updating workspaces using 'update_workspace' function.
Workspace got updated but jumps were missing.
Is there any way to fix this?

**Comment by ehdsouza** [comment]
Hi,

Could you give a code snippet? The sdk is not doing anything with the workspace, it only wraps the API call.

**Comment by sandlis** [comment]
Actually I am using https://github.com/data-henrik/watson-conversation-tool for making request.
I checked code of that tool as well as your sdk, I didn't see any data processing.
I am not sure if this is the write place to bring this up. I would be grateful If someone can help in fixing this or point me into right direction.

**Comment by germanattanasio** [comment]
This is not an issue in the SDK. I talked to the Conversation team and they will look into this. No ETA.

**Comment by ans10** [comment]
One reason that jumps might not be there is the version of the conversation api that is being used. I faced the similar error and updating the error to the latest version solved the problem.
