### ISSUE TITLE
Querying Multiple Collections

### ISSUE THREAD

**Issue by rebecca-makar** [watson-developer-cloud/python-sdk#277]
I am running into an issue which involves the new feature of querying multiple collections at once. I have a work around that can be added, adding a new method query_multiple_collections, that will have the correct url.

**Comment by ehdsouza** [comment]
Could you be precise? Like what service, code, etc?

**Comment by rebecca-makar** [comment]
In Discovery_V1.py - I created a PR https://github.com/watson-developer-cloud/python-sdk/pull/278

**Comment by ehdsouza** [comment]
Hi @rebecca-makar,

This is already being addressed in #276 as part of the new SDK release. It is named federated_query. Thanks for the effort.
