### ISSUE TITLE
Exceptions don't have enough information for users

### ISSUE THREAD

**Issue by germanattanasio** [watson-developer-cloud/python-sdk#279]
As a Developer _I want_ to have `code`, `message`, `description` whenever a Watson service raises an exception _so that_ I can write code that reacts different depending on the exception.

# Context
It seems like the Python exceptions this SDK is throwing are not very useful for developers:
> **Bruce Adams:**
> I do not have a strong opinion about exception classes. I do find it irritating that `WatsonException` takes a structured error response from as service call and flattens it into a string as the exception args. When I want to make decisions based on the error code (my code needs to react differently to 429 compared to a 500), I have to pick the code out of the string.

More info:
 * https://stackoverflow.com/questions/256222/which-exception-should-i-raise-on-bad-illegal-argument-combinations-in-python
 * https://www.youtube.com/watch?v=o9pEzgHorH0
## Acceptance Criteria
- [ ] Switch to use `ValueError` when there is a missing or illegal argument
- [ ] Parse the error parameters and make them available to users (`code`, `description`)

**Comment by mkistler** [comment]
Even more info: The [Google Python Coding Guidelines](https://google.github.io/styleguide/pyguide.html?showone=Exceptions#Exceptions) state:

>Modules or packages should define their own domain-specific base exception class, which should inherit from the built-in Exception class. The base exception for a module should be called Error.
>```
>class Error(Exception):
>    pass
>```

It's not clear if this means _all_ exceptions raised by the package/module should use this special exception class, or only those that don't fit an existing standard exception.

AND ... another data point ... the Python client generated by the (open-source) swagger-codegen uses `ValueError` for missing/incorrect arguments:

```
        # verify the required parameter 'workspace_id' is set
        if ('workspace_id' not in params) or (params['workspace_id'] is None):
            raise ValueError("Missing the required parameter `workspace_id` when calling `create_counterexample`")
```

**Comment by mkistler** [comment]
To do this properly, I think we will need to extend `WatsonException` to support the additional information we want to return.

https://stackoverflow.com/questions/1319615/proper-way-to-declare-custom-exceptions-in-modern-python
