### ISSUE TITLE
API Reference for Document Conversion incorrect: 400 error because no version in request

### ISSUE THREAD

**Issue by boxcarton** [watson-developer-cloud/python-sdk#28]
https://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/document-conversion/api/v1/?python#convert-document

Is inconsistent with what's actually in the SDK example.

document_conversion = DocumentConversion(username='YOUR SERVICE USERNAME',
                                         password='YOUR SERVICE PASSWORD',
                                         version='2016-02-09')

The SDK actually requires you to put in version date(?) for object instantiation.

**Comment by jsstylos** [comment]
Good catch. The SDK updated and the documentation hasn't yet reflected that.

**Comment by kcheat** [comment]
Cool. I am updating this. I have it tucked in with a tone analyzer 
incremental review. I'll send it to you for review.

_________________________________________________________________________
Kaylyn Cheatham

Information Developer - Watson Platform
email: kcheath@us.ibm.com | Tel: 614-792-4264




_________________________________________________________________________
