### ISSUE TITLE
Is there a way to use 'include_event' as a filter in Conversation's list_logs function?

### ISSUE THREAD

**Issue by renatojen** [watson-developer-cloud/python-sdk#281]
Hello,

I tried creating a filter similar to this:
```
response_timestamp%3E%3D1970-01-02T00:00:00.000Z,response_timestamp%3C2017-10-18T18:50:04.138Z,request.input.text:!%22%20%22&include_event=improve_log_edit
```

But I get the following error:
```
watson_developer_cloud.watson_developer_cloud_service.WatsonException: Error: Analytics Service Error: Invalid query request, Code: 400
```
I noticed other query params like 'sort' or 'page_filter' are specific params in the list_logs function.

**Comment by ehdsouza** [comment]
Could you give a code snippet which would be easier to understand.
Also, we are coming up with a new release https://github.com/watson-developer-cloud/python-sdk/pull/276

**Comment by ehdsouza** [comment]
Hi,
@renatojen , could you try if the problem exists with the new version(1.0.0) released?

**Comment by ammardodin** [comment]
@renatojen My understanding is that in your case, you are filtering for requests that include events with the title`improve_log_edit`. You should be able to do something like  `request.event:improve_log_edit`. 

@ehdsouza The additional `include_event` parameter would be something that needs to be changed at the service level, so we probably need to open an issue with the service team.

**Comment by renatojen** [comment]
Hi @ehdsouza, @ammardodin ,

Here's a working code snippet using requests (instead of watson_developer_cloud python sdk) to achieve what I want.

`
import requests

wcs_wksp = 'Your Conversation Workspace'
wcs_user = 'Your Conversation User'
wcs_pswd = 'Your Conversation Password'

#example dates
start_date = '2017-11-01'
end_date = '2017-11-28'

headers = {'Content-type': 'application/json', 'Accept': 'text/plain'}

params = (
    ('version', '2017-05-26'),
    ('filter', 'response_timestamp>=' + start_date + 'T00:00:00.000Z,response_timestamp<' + end_date + 'T23:59:59.999Z'),
    ('include_count', 'true'),
    ('include_event', 'improve_log_edit'),
    ('page_limit', '500'),
    ('sort', 'request_timestamp'),
)
r = requests.get('https://gateway.watsonplatform.net/conversation/api/v1/workspaces/' + wcs_wksp + '/logs' , params=params, headers=headers, auth=(wcs_user, wcs_pswd))
logs_dump = r.json()`

I'm using this query to obtain the 'addition_events' in logs that received some kind of action in User Conversations, i. e. mapping the log to a different intent.

**Comment by ammardodin** [comment]
@renatojen Oh, I see. Well, those properties that you are using with the raw HTTP request are not part of the public [API](https://watson-api-explorer.mybluemix.net/apis/conversation-v1). Additionally, If they were intended to be part of the public API, then they need to be added to the official spec before they can be supported in the SDK.
