### ISSUE TITLE
Conversation - Error on .delete_example when example is "#"

### ISSUE THREAD

**Issue by Eibriel** [watson-developer-cloud/python-sdk#304]
When deleting an intent example with text "#" the following error raises:

`DEBUG:urllib3.connectionpool:https://gateway.watsonplatform.net:443 "DELETE /conversation/api/v1/workspaces/00e477c9-790b-47e7-ee11-48fcx1c22496c/intents/what_is_conversational_experience/examples/?version=2017-05-26 HTTP/1.1" 404 None`

Python 3.5.2 on Linux
watson-developer-cloud==0.26.1

**Comment by germanattanasio** [comment]
@Eibriel can you encode the example parameter before you send it?

**Comment by germanattanasio** [comment]
This was fixed in v1.0.0
