### ISSUE TITLE
Support for multi-part audio, and customization_weight parameters in the Python SDK for STT

### ISSUE THREAD

**Issue by amaresh-rajasekharan** [watson-developer-cloud/python-sdk#306]
Hi,
Unless I am missing something, I don't see how to use the STT python libraries to process multipart audio files (cURL command lets you do this)... 
Also, is there a way to pass content headers, and the parameter customization_weight etc to the recognize call using the Python SDK?

**Comment by ammardodin** [comment]
@amaresh-rajasekharan the `recognize()` method in the latest release accepts a `content_type` parameter. As for `customization_weight`, that seems to be missing and I will work on adding that. Thanks for bringing it to our attention!
