### ISSUE TITLE
Add Get Dialog File Call in the Dialog API

### ISSUE THREAD

**Issue by jagan120** [watson-developer-cloud/python-sdk#31]
The Dialog API Supports the call to Download the Dialog File(GET /v1/dialogs/{dialog_id}). Not Sure if this call was not available earlier.

I am talking about the Number 6 in [here](https://watson-api-explorer.mybluemix.net/apis/dialog-v1#/). I can have this assigned to myself if you guys dont mind!

**Comment by jsstylos** [comment]
Thanks for the report. Fixed in 08cf16bc1bd60592e6eafeb02c769208f61781af

**Comment by jagan120** [comment]
Thanks for fixing it guys!
