### ISSUE TITLE
NLC create_classifier function fails?

### ISSUE THREAD

**Issue by stefanvds** [watson-developer-cloud/python-sdk#318]
Hi,  I tried using the `create_classifier` function in the python SDK to train a classifier.  The code fails with:
`"WatsonApiException: Error: Missing metadata, Code: 400"`

I used the example from the repo (which is commented out, probably cause the code is not working?)

The code is key to perform various testing, please could somebody look into it?

Thanks!

**Comment by stefanvds** [comment]
As a follow-up, the comment in the code points to documentation that still uses the old `create` function...
https://www.ibm.com/watson/developercloud/natural-language-classifier/api/v1/#create_classifier

**Comment by germanattanasio** [comment]
The documentation is using:
```
pip install -I watson-developer-cloud==0.26.1
```
The latest version is `1.0.1` and fixed this issue. Make sure you are using that version
