### ISSUE TITLE
Api key vs username/passwork issue

### ISSUE THREAD

**Issue by mengkeding** [watson-developer-cloud/python-sdk#320]
To run alchemy_data_news_v1.py in the examples, I need an api key. I have my username and password in the credentials but couldn't find api keys. How to fix this issue?

**Comment by ammardodin** [comment]
@mengkeding Thanks for reporting the issue. You should be able to pass in your username and password when you create the service instance via the named parameters `username` and `password`, i.e.:

```python
alchemy_data_news = AlchemyDataNewsV1(username='YOUR USERNAME', password='YOUR PASSWORD')
```

I am closing this issue, but please feel free to reopen if you're stil having issues.

**Comment by germanattanasio** [comment]
@mengkeding The Alchemy Data News service was deprecated. I would suggest you to try the [Discovery](https://www.ibm.com/watson/services/discovery/) service.
