### ISSUE TITLE
'/v1/environments/{0}/collections/{1}/notices' api not updating after deleting all training data

### ISSUE THREAD

**Issue by breathe** [watson-developer-cloud/python-sdk#325]
I've augmented python sdk to interact with discovery service api's for which support is missing the python sdk.

The methods added are for deleting all training data in a collection, querying for the set of training data defined on a collection, and querying for the set of notices available for a collection.

Subclass with implementation of relevant discovery service api interaction in the class below:

```py
class CustomDiscovery(DiscoveryV1):
    def delete_all_training_examples(self: DiscoveryV1,
                                     environment_id: str,
                                     collection_id: str):
        """Delete all training examples for collection
        """
        base_url = '/v1/environments/{0}/collections/{1}/training_data/'

        url_string = base_url.format(
            environment_id, collection_id)

        params = {'version': self.version}

        return self.request(method='DELETE',
                            url=url_string,
                            params=params
                            )

    def get_training_data(self: DiscoveryV1,
                          environment_id: str,
                          collection_id: str
                          ):
        """
        Get notices
        :param environment_id the guid of the environment
        :param collection_id collection guid
        :return dict of notice info
        """
        base_url = '/v1/environments/{0}/collections/{1}/training_data'

        url_string = base_url.format(
            environment_id, collection_id)

        params = {'version': self.version}

        return self.request(method='GET',
                            url=url_string,
                            params=params,
                            accept_json=True)

    def get_notices(self: DiscoveryV1,
                    environment_id: str,
                    collection_id: str
                    ):
        """
        Get notices
        :param environment_id the guid of the environment
        :param collection_id collection guid
        :return dict of notice info
        """
        base_url = '/v1/environments/{0}/collections/{1}/notices'

        url_string = base_url.format(
            environment_id, collection_id)

        params = {'version': self.version}

        return self.request(method='GET',
                            url=url_string,
                            params=params,
                            accept_json=True)
```

If I:

(1) add training examples which cause 'notices' (querying the set of training data confirms its not empty)
(2) then delete all training examples (re-querying the set of training data confirms its empty)
(3) then re-query the notices api -- the notices api still reports errors associated with the no longer present training data

Shouldn't the notices api update after the problematic training data is removed?

**Comment by RWArunde** [comment]
@breathe It's expected for the notices to stick around. They'll stay until the next time that Discovery tries to train a new model on your data, then the old notices are deleted and the notices index is populated with warnings from the next training attempt. 

If you want them gone, you'll need to upload some non-problematic training data

**Comment by breathe** [comment]
Thanks for the info @RWArunde!  I’ll update my test and try to confirm that I observe this behavior.
