### ISSUE TITLE
[Watson Discovery Service] API docs do not correspond to recent version on pip, method parameters

### ISSUE THREAD

**Issue by HigginTown** [watson-developer-cloud/python-sdk#333]
After pip installing, the version is different from the API docs and the python examples in this repo. 

For example, the `.add_document` method does not have the parameter `file_info` in the new version, but does in your docs and examples.

Also, when trying to pass an html doc on my local machine, I get `WatsonApiException: Error: Unsupported Media Type, Code: 415`
compare these
<img width="616" alt="screen shot 2017-12-13 at 1 52 07 pm" src="https://user-images.githubusercontent.com/18233688/33959465-30c469ca-e00d-11e7-909a-6885103b3ca8.png">

![screen shot 2017-12-13 at 1 55 22 pm](https://user-images.githubusercontent.com/18233688/33959497-4d222d5a-e00d-11e7-89a7-cadd83d92de3.png)

and also compare these
<img width="1346" alt="screen shot 2017-12-13 at 1 53 06 pm" src="https://user-images.githubusercontent.com/18233688/33959512-5570dd76-e00d-11e7-88a3-ebdfb1597193.png">

![screen shot 2017-12-13 at 1 56 32 pm](https://user-images.githubusercontent.com/18233688/33959541-74e58710-e00d-11e7-8a56-702979d12341.png)

I'm an IBMer, figured I should just take this here. 
Find me on slack @adam.massachi

**Comment by germanattanasio** [comment]
This is not an issue in the SDK but a problem with the API Reference which is not updated yet.

**Comment by HigginTown** [comment]
@germanattanasio any idea when this will be updated?
