### ISSUE TITLE
Discovery add_document() fails with "too many parts" if metadata dict has more than one entry

### ISSUE THREAD

**Issue by uoo** [watson-developer-cloud/python-sdk#334]
If I call add_document() with Discovery, and include a dict with a single entry as metadata, it works as expected, the metadata is stored by Discovery, and returned with query results.  However, if I include a dict with more than one entry, something apparently goes awry with the request, and Discovery returns a "too many parts" error and HTTP code 439.

**Comment by ammardodin** [comment]
@uoo Thanks for reporting the issue. I just tried using `add_document` with a multi-entry dictionary, and things seems to work just fine.

Can you provide the following to help us reproduce the issue:
1. Version of the python-sdk you're using
2. Code snippet in which the `add_document()` method is failing with the aforementiond exception

Thanks,

**Comment by SimeonKostadinoff** [comment]
Hey, I experienced exactly the same issue. The version of my sdk is watson-developer-cloud==0.26.1 and here is the snippet:
```
    meta_data = {
        "document_name": "name1",
        "page_number": 1
    }
    with open(path_to_page, "rb") as pdf_page:
        add_doc = DISCOVERY.add_document(
                          app.config["IBM_WATSON_ENV_ID"],
                          app.config["IBM_WATSON_COLLECTION_ID"], 
                          file_info=pdf_page, 
                          metadata=meta_data)
```
The call stack is:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/simeonkostadinov/Projects/QA/qa/__init__.py", line 142, in upload_single_page
    add_doc = DISCOVERY.add_document(app.config["IBM_WATSON_ENV_ID"], app.config["IBM_WATSON_COLLECTION_ID"], file_info=pdf_page, metadata=meta_data)
  File "/Users/simeonkostadinov/Projects/QA/env/lib/python3.6/site-packages/watson_developer_cloud/discovery_v1.py", line 281, in add_document
    accept_json=True)
  File "/Users/simeonkostadinov/Projects/QA/env/lib/python3.6/site-packages/watson_developer_cloud/watson_developer_cloud_service.py", line 324, in request
    raise WatsonException(error_message)
watson_developer_cloud.watson_developer_cloud_service.WatsonException: Error: Too many parts, Code: 500

I looked at the sdk code, to me, everything seems fine on the client side.

**Comment by ammardodin** [comment]
@SimeonKostadinoff I was able to reproduce the issue with 0.26.1. After looking at the client code, it seems that we're sending metadata to the server twice. I think that is the issue. You can see in this snippet that we're sending metadata twice, which I think is triggering the `too many parts` error on the server side. You can see the 

```python
return self.request(method='POST',
                            url=url_string,
                            params=params,
                            data=metadata,
                            files={'file': file_tuple,
                                   'metadata': (None,
                                                json.dumps(metadata),
                                                'application/json')},
                            accept_json=True)
```

If you remove the `data=metadata`, you shouldn't see the error anymore. I've verified that this is no longer an issue in the latest release, i.e. 1.0.2, so you can try using that as well.

**Comment by SimeonKostadinoff** [comment]
@ammardodin Thank you very much for the response. Yes, I noticed that is being used twice but didn't think of removing the data. Nice move! 

Great support 💯

**Comment by SimeonKostadinoff** [comment]
@ammardodin Thank you! I can confirm that it is working with your example. 👍
