### ISSUE TITLE
Unable to X-Watson-Learning-Opt-Out with Natural Language Classifier

### ISSUE THREAD

**Issue by usakthivel** [watson-developer-cloud/python-sdk#336]
I'm trying to flag the X-Watson-Learning-Opt-Out to True in Python as per the document but getting the error message as below. 

NaturalLanguageUnderstandingV1(username = user_name, password = password, version  = version,                                                               x_watson_learning_opt_out=True)

TypeError: __init__() got an unexpected keyword argument 'x_watson_learning_opt_out'

Saw something similar @ https://github.com/watson-developer-cloud/python-sdk/issues/83
Please help

**Comment by mkistler** [comment]
The mechanism for setting the `x-watson-learning-opt-out` header has changed in the latest version of the SDK.  What you need to do now is set it with the `default_headers` method after creating the service, like so:

```
natural_language_understanding = NaturalLanguageUnderstandingV1(username = user_name, password = password, version = version)
natural_language_understanding.set_default_headers({'x-watson-learning-opt-out': "true"})
```

Sorry for the error in the docs ... we'll get that updated.
