### ISSUE TITLE
WatsonException drops description

### ISSUE THREAD

**Issue by SirSpidey** [watson-developer-cloud/python-sdk#34]
The WatsonException doesn't return the description property from the service error message. For example, with not enough training data in the Natural Language Classifier, this is returned: 

```
raise WatsonException('Error: ' + error_message + ', Code: ' + str(response.status_code))
watson_developer_cloud.watson_developer_cloud_service.WatsonException: Error: Data too small, Code: 400
```

* The description is missing from this.
* Also might want to put the message, code, and description on separate lines
* Also, to match service, labels should be lower case. For example,

```
{
   "description": "No training data is specified. The form field 'training_data' should contain the training CSV and 'training_metadata' should contain a JSON metadata string.",
   "error": "Missing training data",
   "code": 400
}
```

**Comment by jsstylos** [comment]
Fixed in 0c603adeff780a05fd9d6b38c38f98d3d4c577c8

**Comment by SirSpidey** [comment]
@jsstylos: Doesn't the `raise WatsonException` line 252 from `watson_developer_cloud/watson_developer_cloud_service.py`need to be updated as well to include the description?
```
...
  File "/Library/Python/2.7/site-packages/watson_developer_cloud/watson_developer_cloud_service.py", line 252, in request
    raise WatsonException('Error: ' + error_message + ', Code: ' + str(response.status_code))
watson_developer_cloud.watson_developer_cloud_service.WatsonException: Error: Data too small, Description: The number of training entries received = 3, which is smaller than the required minimum of 5, Code: 400
```

**Comment by jsstylos** [comment]
The code is admittedly a little confusing here -- the (optional) description, including ', Description: ', is being added to `error_message`. This way, when the description doesn't exist (which is most of the time), the ', Description: ' is omitted. I could refactor the message handling code to handle the ', Code: ' logic also, which may be cleaner;.

**Comment by jsstylos** [comment]
Cleaned up in d9b0b808bf7c54acc8b3c05fca4be086b156ebb1
