### ISSUE TITLE
speech to text (error 500 Internal Server Error) 

### ISSUE THREAD

**Issue by dragonsharma** [watson-developer-cloud/python-sdk#343]
i tried using speech to text from example but whenever i use customization_id it run into error 500
![image](https://user-images.githubusercontent.com/11546854/34607818-5bc75d7c-f23b-11e7-9af6-59a1594aec9e.png)

**Comment by ehdsouza** [comment]
Hi @dragonsharma ,

Could you try again as there might have been a service problem at that time.

**Comment by dragonsharma** [comment]
@ehdsouza  hi 
i have trying this code from last week and having same error message .
`from __future__ import print_function
import json
from os.path import join, dirname
from watson_developer_cloud import SpeechToTextV1
speech_to_text = SpeechToTextV1(
    username='adsde413-f16a-484d-a20d-b2b214b2aaec',
    password='FaRbmacoiSyH',
    x_watson_learning_opt_out=False
)
print(json.dumps(speech_to_text.models(), indent=2))
print(json.dumps(speech_to_text.get_model('en-US_NarrowbandModel'), indent=2))
with open(join(dirname("C://vivo_curl//"), 'test1.wav'),'rb') as audio_file:
    print(json.dumps(speech_to_text.recognize(audio_file, content_type='audio/wav',customization_id='22e61c73-9a62-4c13-9754-c00a68a571fb'
                                              ,speaker_labels=True,timestamps=True,word_confidence=True),indent=2))`

**Comment by ehdsouza** [comment]
@dragonsharma could you run the command outside the sdk, say using curl command?

**Comment by dragonsharma** [comment]
hi @ehdsouza i have tried this through this code also but i get the same result :
import requests
headers = {
    'Content-Type': 'audio/wav',
}
params = (
    ('continuous','true'),
    ('model', 'en-US_NarrowbandModel'),
    ('customization_id', '44e61c73-9a12-4c13-9754-n00a68a343fb'),
    ('max_alternatives', '1'),
    ('word_confidence', 'true'),
    ('timestamps', 'true'),
    ('profanity_filter', 'true'),
    ('smart_formatting', 'true'),
    ('speaker_labels', 'true'),
)
data = open('C:/Users/ksharm50/Music/nps/test1.wav', 'rb').read()
response = requests.post('https://stream.watsonplatform.net/speech-to-text/api/v1/recognize', headers=headers, params=params, data=data, auth=('bcbde223-f16a-814d-a45d-b2b817b2aaec', 'FatbmwefPWyH'))
print(response)

result: error 500

**Comment by ehdsouza** [comment]
Hi @dragonsharma,

Make sure you don't add your authentication details here for security. I updated it.

Anyways, the service team tried your code above and got a 401 error (I am guessing it because you gave invalid credentials here).

Here is your equivalent curl command:
curl -u b<username>:<password> -X POST --header "content-type: audio/wav" --data-binary @{audio}.wav "https://stream.watsonplatform.net/speech-to-text/api/v1/recognize?model=en-US_NarrowbandModel&customization_id=44e61c73-9a12-4c13-9754-n00a68a343fb&max_alternatives=1&word_confidence=true&timestamps=true&profanity_filter=true&smart_formatting=true&speaker_labels=true"

Also, make sure the the customization ID is valid and the continuous parameter is deprecated.

**Comment by dragonsharma** [comment]
Hi i entered  wrong  credentials  for a reason .

**Comment by germanattanasio** [comment]
@dragonsharma can you try with the `curl` comment that @ehdsouza wrote above?

**Comment by dragonsharma** [comment]
hi @germanattanasio  @ehdsouza  i have tried this curl command and i am getting output as 
{"code":500,"message":"Forwarding error"}
i guess its same error i am getting from python sdk.

**Comment by ehdsouza** [comment]
@dragonsharma, we contacted the service team and they said that there is a known service bug when passing the customization_id and speaker_labels parameters together. They are working on fixing this. A 503 Service Unavailable is incorrectly returned at the moment. Here's the equivalent curl command for the code that currently fails:

```
curl -v -u <username>:<pwd> -X POST --header "content-type: audio/wav" --data-binary @{audio}.wav "https://stream.watsonplatform.net/speech-to-text/api/v1/recognize?model=en-US_NarrowbandModel&customization_id=<id>&speaker_labels=True&timestamps=True&word_confidence=True"
```

{"code":503,"message":"Service Unavailable"}

It works fine when either customization_id or speaker_labels is removed above, so this is a temporary option.

**Comment by ehdsouza** [comment]
Also, a good place to open a ticket is: https://watson.service-now.com/wcp when there is a service issue

**Comment by dragonsharma** [comment]
hi @ehdsouza thank's for all your help . i raised a ticket on 2 jan 2018 and they didn't know what is happening exactly and they take so long to reply .

**Comment by Jaswanth-Devarinti** [comment]
Found the answer? Same problem here

**Comment by inkones** [comment]
Why was this case closed? Do we now have a solution to the internal server issues, please?

**Comment by kunalsharmagnome** [comment]
hey @inkones no i didn't found any help from from ibm about this so i left watson platform there customer service is messed up.
