### ISSUE TITLE
x_watson_learning_opt_out defaulting to False

### ISSUE THREAD

**Issue by chughts** [watson-developer-cloud/python-sdk#344]
Re: https://developer.ibm.com/answers/questions/419905/set-x-watson-learning-opt-out-with-natural-languag.html?childToView=419937#comment-419937

I suspect that post V 1.0.0 that the Python SDK is ignoring the setting of x_watson_learning_opt_out

**Comment by ehdsouza** [comment]
Hi,

There was a similar issue created: https://github.com/watson-developer-cloud/python-sdk/issues/336

The mechanism for setting the x-watson-learning-opt-out header has changed in the latest version of the SDK. What you need to do now is set it with the default_headers method after creating the service, like so:

```python
natural_language_understanding = NaturalLanguageUnderstandingV1(username = user_name, password = password, version = version)
natural_language_understanding.set_default_headers({'x-watson-learning-opt-out': "true"})
```
Sorry for the error in the docs ... we'll get that updated.

**Comment by chughts** [comment]
ok - I will close as a duplicate of #336
