### ISSUE TITLE
Migration document missing changes to update_document api

### ISSUE THREAD

**Issue by breathe** [watson-developer-cloud/python-sdk#345]
https://github.com/watson-developer-cloud/python-sdk/wiki/Migration

No reference to changes to Discovery service update_document api or how to resolve when migrating to latest sdk version.

What is filename supposed to be and what does it represent in the service layer?

**Comment by ehdsouza** [comment]
@breathe thanks for pointing it out. I updated the migration document.

update_document() parameters `mime_type` renamed to `file_content_type`, `file_info` and `file_data` replaced by `file` and `filename` is the file name given to the file

**Comment by breathe** [comment]
Thank you!  

Any chance to include more clarity for I what the file name is supposed to represent?  I’m passing io.StringIO instances created from non file data sources — I’ve just set the filename to the same value as I’m setting the document_id and not running into any issues — but it’s not clear to me what the filename is supposed to be used for and if there are any constraints on what should be used for this.

**Comment by germanattanasio** [comment]
The filename will be more metadata that the service will save. Imagine you ingest documents and then you query them wouldn't be great to know the name of the file that was used to ingest the data you are seeing in the result?

**Comment by breathe** [comment]
Hmm ok — I don’t exactly understand why I wouldn’t put that property in the document (maybe to avoid including the name of the file in the index?).  In any case, I can set it to something appropriate and in many cases I can see it being useful to have a value for this — but making it mandatory surprised me because it seems to imply that the properties value might have some kind of fixed semantics with respect to some other component of the system.

When you say it’s stored as metadata — does that mean the value is saved in the “metadata” portion of the document (which I understand is not indexed and not part of the document hash)?  Thanks,

**Comment by germanattanasio** [comment]
Maybe someone from the @watson-developer-cloud/discovery can help answer why is filename required when ingesting a document.

**Comment by maniax89** [comment]
`filename` is not required by Discovery. If `file` is provided, it must have a `name` which can be overridden with the `filename` parameter for files that are created in-memory rather than uploading from a file on disk. I believe the SDK attempts to make this process easier by providing these parameters for use in the in-memory "file"

**Comment by maniax89** [comment]
Some SO on the topic: https://stackoverflow.com/questions/1342506/why-is-form-enctype-multipart-form-data-required-when-uploading-a-file

**Comment by breathe** [comment]
Ok — so filename is this property from the transport layer that will be stored into the database for various practical reasons.  But it has no meaning in the data store and no constraints on it other than those inherited from the transport layer.

I think I’m good with this issue then — though I think the docs could perhaps better explain the semantics of the filename parameter

**Comment by ehdsouza** [comment]
@NickyBleiel can this be addressed in the discovery docs?

**Comment by germanattanasio** [comment]
@breathe I talked to the documentation team and they said the API reference will be updated in 2 weeks.

I'm going to close this issue since it's not a problem in this SDK. Feel free to reopen if you have more questions
