### ISSUE TITLE
Discovery API Does Not Return All Results - Unexpected Behavior

### ISSUE THREAD

**Issue by HigginTown** [watson-developer-cloud/python-sdk#348]
The Discovery V1 API does not produce the results we might expect 

<img width="1161" alt="screen shot 2018-01-29 at 4 54 41 pm" src="https://user-images.githubusercontent.com/18233688/35538919-23abb68a-0515-11e8-9898-0f22f03e42d9.png">

This is true for every query I have tried. Is there a limit of 10 results? 

We don't mention this in [these docs](https://www.ibm.com/watson/developercloud/discovery/api/v1/#query-collection)

or on [Bluemix here](https://console.bluemix.net/docs/services/discovery/using.html#query-concepts) 

what am I missing? 

It's impossible to work with multiple Watson services if they each require different versions.....

**Comment by ehdsouza** [comment]
Hi @HigginTown ,

Ill contact the discovery team to get more information on this. Did you try with a curl command?

**Comment by HigginTown** [comment]
hey @ehdsouza I didn't try using the curl, the demo needs to use python and don't to just write a bunch of bash in a notebook

**Comment by atambo** [comment]
The discovery API only returns 10 results by default. If you want more results you can use the `count` parameter to increase the number of results returned up to a maximum of 10000.

**Comment by ehdsouza** [comment]
@HigginTown as you can see @atambo replied. 

Also, here was the reply from discovery team:
By default the count=10 for that many results. you can increase count to a higher amount if you want more results. note: news has a hard cap of count=50 as it's a shared data set

**Comment by germanattanasio** [comment]
@HigginTown where you able to use the `count` parameters to retrieve more results? Is this still an issue?
