### ISSUE TITLE
Update the IBM Cloud Discovery Docs to Current PyPI Version

### ISSUE THREAD

**Issue by HigginTown** [watson-developer-cloud/python-sdk#352]
The discovery docs have not been updated since `watson-developer-cloud` 0.26 , this makes it difficult to work with multiple Watson services when the documentation for different services recommend using different versions of the client. 

I spoke with @germanattanasio on Dec 14th, he said you all would update the documentation soon. 
PyPi version is v > 1.0. 

<img width="575" alt="screen shot 2018-01-31 at 11 10 08 am" src="https://user-images.githubusercontent.com/18233688/35636634-6ad388f4-0677-11e8-9d2a-fd1017e4e61b.png">

<img width="874" alt="screen shot 2018-01-31 at 11 13 21 am" src="https://user-images.githubusercontent.com/18233688/35636741-c876cd4a-0677-11e8-857e-42af88b04056.png">

**Comment by germanattanasio** [comment]
Thanks for reporting this problem @HigginTown. The documentation team is aware of the issue but we don't have a time for when it will be fixed.

I guess your problem is #351 so I will help you with that issue and keep this open until the documentation is updated
