### ISSUE TITLE
Add Sample Output to Examples in Comments

### ISSUE THREAD

**Issue by manistal** [watson-developer-cloud/python-sdk#36]
Hello, 
I was walking through the examples today (i.e. https://github.com/watson-developer-cloud/python-sdk/blob/master/examples/relationship_extraction_v1_beta.py ) and noticed that they don't give a lot of insight into what's going on in the example, since it's just an import/invoke. 

Since all of these scripts require login credentials I think it'd be a nice addition if the output from the print statements at the end of the script could be followed by comments showing what the output would be. For example:

```
print(["Hi!" for i in range(0, 3)])
"""
['Hi!', 'Hi!', 'Hi!']
"""
```

**Comment by jsstylos** [comment]
Hi, thanks for creating this issue. Currently we use our API reference pages (e.g. http://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/document-conversion/api/v1/) to document the service output, while our SDKs only document the input, and need to be run to see the output. I worry that putting the output inline in comments will be difficult to test for correctness, and decrease the readability of large examples. We'll think about this and see if there are ways we can better show the output of services while keeping them up to date.
