### ISSUE TITLE
Details in error message

### ISSUE THREAD

**Issue by victorzhao1990** [watson-developer-cloud/python-sdk#361]
As for #359, the error message only shows that validation fails but no clue which field is missing/malformed. Instead of `Error: Invalid Request Body`, is it possible to add something like:
`Missing 'type' key in CreateValue object/type`?

**Comment by victorzhao1990** [comment]
@germanattanasio 
The error is `Error: Invalid Request Body`

**Comment by ehdsouza** [comment]
This has been supported in the upcoming release: v1.1.0.
The dictionary would be converted to the appropriate model before making a network call. So, the missing params would be notified.

**Comment by victorzhao1990** [comment]
Thanks, @ehdsouza . I tried the latest sdk and it throws the same error.
It may be because its validation logic was not implemented in the same way as the server-side validation. This logic doesn't check whether the provided argument is `string` or `list`.
https://github.com/watson-developer-cloud/python-sdk/blob/develop/watson_developer_cloud/conversation_v1.py#L2351

**Comment by ehdsouza** [comment]
Yes right, it will give you notification of `Missing 'type' key in CreateValue object/type` for required params. It wouldn't make a type check. 

The user is required to check the type in the description of the method param.

**Comment by victorzhao1990** [comment]
Thanks!
