### ISSUE TITLE
WatsonException should show description text

### ISSUE THREAD

**Issue by wpm** [watson-developer-cloud/python-sdk#37]
I have the maximum number of NLC classifiers. When I try to allocate another one using a CURL call I see the following error

    {
      "code" : 400,
      "error" : "Entitlement error",
      "description" : "This user or service instance has the maximum number of classifiers."
    }

If I do the same thing with the `watson_developer_cloud` Python sdk, the following exception is displayed.

    WatsonException: Error: Entitlement error, Code: 400

It would be really helpful if the Python sdk also displayed the description text, since offhand I don't know what an "Entitlement error" is.

It looks like this information has to be fished out of the `response` local variable in `WatsonDeveloperCloudService.request` in `watson_developer_cloud_service.py`.

**Comment by SirSpidey** [comment]
This is a dupe of #34

**Comment by jsstylos** [comment]
Fixed in 0c603adeff780a05fd9d6b38c38f98d3d4c577c8
