### ISSUE TITLE
Language Translation missing methods

### ISSUE THREAD

**Issue by melissamahoney3** [watson-developer-cloud/python-sdk#38]
The Python SDK is missing methods for the following Language Translation methods:
List identifiable languages
GET  /v2/identifiable_languages

Create model
POST  /v2/models

Delete model
DELETE  /v2/models/{model_id}

Get model details
GET  /v2/models/{model_id}

**Comment by jsstylos** [comment]
Fixed in 0c603adeff780a05fd9d6b38c38f98d3d4c577c8
