### ISSUE TITLE
How to get a specific parameter value in personality insights?

### ISSUE THREAD

**Issue by hariskr** [watson-developer-cloud/python-sdk#383]
Given the file personality_insights_v3.py, I am unclear on how to get a specific parameter (e.g., percentile of neuroticism). Could you please clarify how to actually extract these values so that I can work with them, and not just see the printed output? TIA!

**Comment by ehdsouza** [comment]
@hariskr, please follow the issue template so that we can help you better:
#### Expected behavior

#### Actual behavior

#### Steps to reproduce the problem

#### Code snippet (Note: Do not paste your credentials)

#### python sdk version

#### python version

**Comment by hariskr** [comment]
**Expected behavior**
Given the file personality_insights_v3.py, I am unclear on how to get a specific parameter (e.g., percentile of neuroticism). Could you please clarify how to actually extract these values so that I can work with them, and not just see the printed output? TIA!

**Actual behavior**
I can just print out the results, but cannot get specific parameter values that I can work with

**Steps to reproduce the problem**
run the sample code personality_insights_v3.py

**Code snippet (Note: Do not paste your credentials)**
profile = personality_insights.profile(
  content, content_type='text/plain',
  raw_scores=True, consumption_preferences=True)

print(json.dumps(profile, indent=2))

**python sdk version**
2.7

**python version** 
2.7

**Comment by ammardodin** [comment]
@hariskr If you want the percentage of a particular `big5` trait, you can do something like this. Let's assume you want the percentage of neuroticism. You can do something like this

```python
def get_percentile(personality_traits, trait_name):
    percentile = None
    for personality_trait in personality_traits:
        if trait_name in personality_trait.get('trait_id', ''):
            percentile = personality_trait['percentile']
            break
    return percentile

profile = personality_insights.profile(
content, content_type='text/plain',
raw_scores=True, consumption_preferences=True)

personality = profile['personality']
neuroticism_percentile = get_percentile(personality, 'neuroticism')
if neuroticism_percentile is None:
    print 'NOT FOUND'
```
