### ISSUE TITLE
Android - problem in installing watson-developer-cloud module for Python

### ISSUE THREAD

**Issue by Gio123bg** [watson-developer-cloud/python-sdk#385]
Hi All,
I need to install the library `watson-developer-cloud` in Android with Qpyton3. 
I have installed QPython (Python version 2 and 3) on my mobile
Android version 5.1.1
Kernel version 3.10.49

The command that I use is 
```
pip install watson_developer_cloud
```
I would like to install the module `watson-developer-cloud` but I receive these errors with QPYPI.
```
disutils.errors.DistutilsExecError: command '/data /data/org.qpython.qpy/files/bin/python-android5' failed with exit status 1
Command python setup.py egg_info failed with error code 1
```

```
Command python setup.py egg_info failed with error code 1
storing complete log in /sdcard/qpython/.pip/pip.log
```

**Comment by Gio123bg** [comment]
Hi German,
First of all, I thank You for your quick reply and for the support.

Please find below the steps and the complete detail of the error messages.

1) Pressing the Qpython3 icon on Android
2) Selecting QPYPI icon
3) Use of pypi ("Install with official pypi") by launching [Pip console] 
by pressing the button with this name.
4)   command  --> pip install "watson-developer-cloud"


Error messages at the end of the installation process that I see in the 
QPyton console.


WARNING: linker: zlib.cpython-32.so: unused DT entry: type 0x6ffffffe arg 
0x8a4
WARNING: linker: zlib.cpython-32.so: unused DT entry: type 0x6fffffff arg 
0x1

Traceback (most recent call last):
     File "<string>", line 16, in <module>
     File "/storage/emulated/0/qpython/cache/pip-build/requests/setup.py", 
line 55, in <module>

      exec(f.read(), about)

      File "<string>", line 14

   __cake__ = u'\u2728 \U0001f370 \u2728'
  v
      SyntaxError: invalid syntax
------------------------------------------------------------------------
Command python setup.py egg_info failed with error code 1 in 
/storage/emulated/0/qpython/cache/pip-build/requests
Storing complete log in /sdcard/qpython/.pip/pip.log
-->

.
If I select "Install with QPypi" by pressing the [QPypi] button I see the 
following packages that I can install.

* ipython-qpython 6.2.1
* mysql-connector-qpython 1.0.8
* pyxmpp2-qpython


I have this Android version.
Android version:
5.1.1

Kernel version:
3.10.49
develop@SW2-Server #1
Mon Mar 20 18:43:28 CST 2017

Best,
   Giovanni


Cordiali Saluti / Best Regards
          Giovanni Bucci
IBM - Segrate (MI) - Italy
Mobile: +39-335-7843208
Office e-Mail: giovanni_bucci@it.ibm.com

IBM Italia S.p.A. Sede Legale: Circonvallazione Idroscalo - 20090 Segrate 
(MI) Cap. Soc. euro 347.256.998,80 C. F. e Reg. Imprese MI 01442240030 - 
Partita IVA 10914660153 Societa' con unico azionista Societa' soggetta 
all'attivita' di direzione e coordinamento di International Business 
Machines Corporation (Salvo che sia diversamente indicato sopra / Unless 
stated otherwise above)

**Comment by Gio123bg** [comment]
Hi All,
Sorry for the trouble. This email is just to know if there are news about 
my issue. I would like to inform you that, if it is necessary, I am 
willing to remove QPython3 from my mobile phone and proceed again with the 
installation and configuration, following your guidelines.
Regards,

       Giovanni

Cordiali Saluti / Best Regards
          Giovanni Bucci
IBM - Segrate (MI) - Italy
Mobile: +39-335-7843208
Office e-Mail: giovanni_bucci@it.ibm.com





From:   Giovanni Bucci/Italy/IBM
To:     watson-developer-cloud/python-sdk 
<reply@reply.github.com>
Date:   08/03/2018 05:26
Subject:        Re: [watson-developer-cloud/python-sdk] Android - problem 
in installing watson-developer-cloud module for Python (#385)


Hi German,
First of all, I thank You for your quick reply and for the support.

Please find below the steps and the complete detail of the error messages.

1) Pressing the Qpython3 icon on Android
2) Selecting QPYPI icon
3) Use of pypi ("Install with official pypi") by launching [Pip console] 
by pressing the button with this name.
4)   command  --> pip install "watson-developer-cloud"


Error messages at the end of the installation process that I see in the 
QPyton console.


WARNING: linker: zlib.cpython-32.so: unused DT entry: type 0x6ffffffe arg 
0x8a4
WARNING: linker: zlib.cpython-32.so: unused DT entry: type 0x6fffffff arg 
0x1

Traceback (most recent call last):
     File "<string>", line 16, in <module>
     File "/storage/emulated/0/qpython/cache/pip-build/requests/setup.py", 
line 55, in <module>

      exec(f.read(), about)

      File "<string>", line 14

   __cake__ = u'\u2728 \U0001f370 \u2728'
  v
      SyntaxError: invalid syntax
------------------------------------------------------------------------
Command python setup.py egg_info failed with error code 1 in 
/storage/emulated/0/qpython/cache/pip-build/requests
Storing complete log in /sdcard/qpython/.pip/pip.log
-->

.
If I select "Install with QPypi" by pressing the [QPypi] button I see the 
following packages that I can install.

* ipython-qpython 6.2.1
* mysql-connector-qpython 1.0.8
* pyxmpp2-qpython


I have this Android version.
Android version:
5.1.1

Kernel version:
3.10.49
develop@SW2-Server #1
Mon Mar 20 18:43:28 CST 2017

Best,
   Giovanni


Cordiali Saluti / Best Regards
          Giovanni Bucci
IBM - Segrate (MI) - Italy
Mobile: +39-335-7843208
Office e-Mail: giovanni_bucci@it.ibm.com

IBM Italia S.p.A. Sede Legale: Circonvallazione Idroscalo - 20090 Segrate 
(MI) Cap. Soc. euro 347.256.998,80 C. F. e Reg. Imprese MI 01442240030 - 
Partita IVA 10914660153 Societa' con unico azionista Societa' soggetta 
all'attivita' di direzione e coordinamento di International Business 
Machines Corporation (Salvo che sia diversamente indicato sopra / Unless 
stated otherwise above)


IBM Italia S.p.A. Sede Legale: Circonvallazione Idroscalo - 20090 Segrate 
(MI) Cap. Soc. euro 347.256.998,80 C. F. e Reg. Imprese MI 01442240030 - 
Partita IVA 10914660153 Societa' con unico azionista Societa' soggetta 
all'attivita' di direzione e coordinamento di International Business 
Machines Corporation (Salvo che sia diversamente indicato sopra / Unless 
stated otherwise above)

**Comment by ehdsouza** [comment]
This seems to be an issue in qpython3: https://github.com/qpython-android/qpython3/issues/28

**Comment by ehdsouza** [comment]
HI @Gio123bg,

This seems like an issue with qpyhton3: https://github.com/qpython-android/qpython3/issues/28. I am closing this issue, feel free to reopen
