### ISSUE TITLE
Document conversion issues with non JSON (ANSWER UNITS) response

### ISSUE THREAD

**Issue by jmrr** [watson-developer-cloud/python-sdk#39]
If I try with a MWE with a conversion to `NORMALIZED_TEXT` or `NORMALIZED_HTML`, 

```
with open('sample.pdf', 'rb') as document:
    watson_config = {'conversion_target': DocumentConversionV1.NORMALIZED_TEXT}
    print(json.dumps(document_conversion.convert_document(document=document, config=watson_config)))
```
`watson_developer_cloud_service.py` (line 233):
```
response_json = response.json()
```
throws an error` JSONDecodeError: Expecting value: line 1 column 1 (char 0)`, i.e. the response doesn't conform to JSON, as it's either text or HTML, therefore I believe it should be contemplated, as I think is the original intention of `return response` in line 243.

**Comment by jsstylos** [comment]
Good catch. Since the response type depends on a field of the input this is a little weird, but I switched it so you can access the text / html with .text on the output for non-answer-unit conversion targets. Fixed in fa617a449070b1dae50cdaaf6d8dcf6e6b5cd174
