### ISSUE TITLE
Rate Limit Header Missing

### ISSUE THREAD

**Issue by victorzhao1990** [watson-developer-cloud/python-sdk#401]
Does the sdk support the header info about rate limiting? I don't see the header available in either python response or the cURL/Postman response.
Ref: https://www.ibm.com/watson/developercloud/conversation/api/v1/?curl#rate-limiting

**Comment by ehdsouza** [comment]
@victorzhao1990 ,
If its not present in a curl response, it wouldn't be present in the sdk model response as well. You could get more information from the service team by opening a ticket.

Regards,
Erika
