### ISSUE TITLE
Authorization.get_tokens had failed

### ISSUE THREAD

**Issue by jaideeppatel** [watson-developer-cloud/python-sdk#406]
#### Expected behavior
get a successful response with the authorization token for the web service
#### Actual behavior
watson_developer_cloud.watson_service.WatsonApiException: Error: Unauthorized: Access is denied due to invalid credentials , Code: 401
#### Code snippet (Note: Do not paste your credentials)
```py
from watson_developer_cloud import AuthorizationV1
from watson_developer_cloud import NaturalLanguageUnderstandingV1
from watson_developer_cloud import SpeechToTextV1

authorization = AuthorizationV1(username="username", password="password")
print(json.dumps(authorization.get_token(url=NaturalLanguageUnderstandingV1.default_url),
                 indent=2))
```
**Note:** I am using my Watson login email and password for the username and password in the authorization service. I am not sure if that is what I need to use or do I need to create any new credentials. Id yes, then please point me to how and where can I find/create the credentials that I need to use for the authorization service.

**Comment by jaideeppatel** [comment]
To mention - I am running these services on my local.

**Comment by germanattanasio** [comment]
Can you add this before calling the SDK
```py
try:
    import http.client as http_client
 except ImportError:
    # Python 2
    import httplib as http_client
 http_client.HTTPConnection.debuglevel = 1
```

That will enable logging.

**Comment by jaideeppatel** [comment]
Here is the error log:

header: Server header: Connection header: Content-Type header: Content-Length send: b'GET /authorization/api/v1/token?url=https://gateway.watsonplatform.net/natural-language-understanding/api HTTP/1.1\r\nHost: gateway.watsonplatform.net\r\nuser-agent: watson-apis-python-sdk-1.0.2 Darwin 16.7.0 3.6.4\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nAuthorization: Basic amFpcGF0ZWxAaXUuZWR1OipIZWVyYWwxMzM=\r\n\r\n'
reply: 'HTTP/1.1 401 Unauthorized\r\n'
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-59-2bfc041e86a3>", line 1, in <module>
    print(json.dumps(authorization.get_token(url=NaturalLanguageUnderstandingV1.default_url),
  File "/anaconda3/lib/python3.6/site-packages/watson_developer_cloud/authorization_v1.py", line 53, in get_token
    response = self.request(method='GET', url='/v1/token?url=' + url)
  File "/anaconda3/lib/python3.6/site-packages/watson_developer_cloud/watson_service.py", line 415, in request
    error_info)
watson_developer_cloud.watson_service.WatsonApiException: Error: Unauthorized: Access is denied due to invalid credentials , Code: 401
header: X-Backside-Transport header: Content-Type header: X-DP-Watson-Tran-ID header: WWW-Authenticate header: X-Global-Transaction-ID header: Strict-Transport-Security header: Content-Encoding header: Content-Length header: Date header: Connection header: Vary send: b'POST /RPC2 HTTP/1.1\r\nHost: 127.0.0.1:62533\r\nAccept-Encoding: gzip\r\nContent-Type: text/xml\r\nUser-Agent: Python-xmlrpc/3.6\r\nContent-Length: 161\r\n\r\n'
send: b"<?xml version='1.0'?>\n<methodCall>\n<methodName>NotifyFinished</methodName>\n<params>\n<param>\n<value><boolean>0</boolean></value>\n</param>\n</params>\n</methodCall>\n"
reply: 'HTTP/1.1 200 OK\r\n'

**Comment by ehdsouza** [comment]
HI @jaideeppatel,

You will need to create a natural language understanding service and put in those username and password.

**Comment by jaideeppatel** [comment]
Hi Ehdsouza - I did create a service and corresponding service credentials for the NLU service. the service works fine when I directly make the API request but it doesn't work with the authorization service.

**Comment by jaideeppatel** [comment]
I think I got your point. I was trying to use my Bluemix credentials in the username and password but instead we need to use the corresponding "Service credentials" . I works for me now. Thanks for you help.
