### ISSUE TITLE
conversation client .message() fails due to check for conversation_id

### ISSUE THREAD

**Issue by scottdangelo** [watson-developer-cloud/python-sdk#410]
#### Expected behavior
Check in:
`watson_developer_cloud/conversation_v1.py", line 1716, in _from_dict` should pass

#### Actual behavior
This throws an exception because it is accessing the `conversation_id` field without using 
`['context']['conversation_id']`

#### Steps to reproduce the problem
use the .message() API with a message consisting of:
```
{'intents': [], 'entities': [], 'input': {}, 'output': {'text': ['Hello! and Welcome to Watson Online Store.'], 'nodes_visited': ['Welcome'], 'log_messages': []}, 'context': {'conversation_id': 'c1dfce32-3e10-446a-8bd5-8455f8ebe24e', 'system': {'dialog_stack': [{'dialog_node': 'Welcome'}], 'dialog_turn_counter': 1, 'dialog_request_counter': 1, '_node_output_map': {'Welcome': [0]}}, 'get_input': 'yes', 'input_text': '', 'shopping_cart': 'list'}, 'type': 'customer', 'email': 'scott.dangelo@ibm.com', 'first_name': 'Scott', 'last_name': 'DAngelo', 'shopping_cart': []}
```

#### python sdk version
Current version, but there is no `latest_version`
#### python version
Python 3.6.4

**Comment by scottdangelo** [comment]
More details here:
https://github.com/IBM/watson-online-store/issues/134

**Comment by scottdangelo** [comment]
Disregard.
The real issue is in our app, fixed here:
`https://github.com/IBM/watson-online-store/pull/135`

**Comment by ehdsouza** [comment]
@scottdangelo , there was a problem in the swagger, check https://github.ibm.com/Watson/developer-cloud--api-explorer/pull/366#event-22362980

I have regenerated conversation and assistant:
PR: https://github.com/watson-developer-cloud/python-sdk/pull/413
PR: https://github.com/watson-developer-cloud/python-sdk/pull/414

**Comment by scottdangelo** [comment]
Thanks. Yes, that PR #413 looks like it would fix our issue.
Thanks for getting back to me on this.
