### ISSUE TITLE
Error when installing Watson Developer Cloud on Mac

### ISSUE THREAD

**Issue by dansegal1** [watson-developer-cloud/python-sdk#416]
Watson Developer Cloud throws errors on installation.

Error occurs when installing using pip according to instructions on https://github.com/watson-developer-cloud/python-sdk, including: 

sudo -H pip install --ignore-installed six watson-developer-cloud

I am using pip 9.0.2 from /Library/Python/2.7/site-packages (python 2.7) . 

The OS is Mac High Sierra 10.13.3

Error also occurs when installing WDC using easy_install: Permission denied: '/Library/Python/2.7/site-packages/easy-install.pth'

See attached logs for details.

[watson developer cloud - error on install - easy_install.txt](https://github.com/watson-developer-cloud/python-sdk/files/1833518/watson.developer.cloud.-.error.on.install.-.easy_install.txt)
[watson developer cloud - error on install - pip.txt](https://github.com/watson-developer-cloud/python-sdk/files/1833519/watson.developer.cloud.-.error.on.install.-.pip.txt)

**Comment by dansegal1** [comment]
@ammardodin Hi Ammar, thanks for that suggestion.  It resolved the problem.

This time the WDC installation completed without errors:

Successfully installed Automat-0.6.0 Twisted-17.9.0 asn1crypto-0.24.0 attrs-17.4.0 autobahn-18.3.1 certifi-2018.1.18 cffi-1.11.5 chardet-3.0.4 constantly-15.1.0 cryptography-2.2.1 enum34-1.1.6 hyperlink-18.0.0 idna-2.6 incremental-17.5.0 ipaddress-1.0.19 pyOpenSSL-17.5.0 pyasn1-0.4.2 pyasn1-modules-0.2.1 pycparser-2.18 python-dateutil-2.7.0 requests-2.18.4 service-identity-17.0.0 setuptools-39.0.1 six-1.11.0 txaio-2.9.0 urllib3-1.22 watson-developer-cloud-1.2.0 zope.interface-4.4.3

See attached log for details.

[watson developer cloud - re-install - pip.txt](https://github.com/watson-developer-cloud/python-sdk/files/1834070/watson.developer.cloud.-.re-install.-.pip.txt)

**Comment by ammardodin** [comment]
@dansegal1 no problem! I am going to close this issue, but please feel free to reopen if you run into the issue again.
