### ISSUE TITLE
How do I get the license?

### ISSUE THREAD

**Issue by sehrawat317** [watson-developer-cloud/python-sdk#420]

**Comment by sehrawat317** [comment]
I have installed pip and maybe Watson developer cloud. Still the error persists 'no module named Watson developer cloud'. I also installed Microsoft Visual C++. 
![pip](https://user-images.githubusercontent.com/37714731/37874437-d210cfaa-304c-11e8-88c2-4ab3fdf7b2aa.jpg)

**Comment by germanattanasio** [comment]
Try installing the latest version not `0.26.1`.

```
pip install watson-developer-cloud --upgrade
```

**Comment by ammardodin** [comment]
@sehrawat317 Make sure you run `cmd` with admin privileges as well, since it appears you're running into permission issues from some of the error messages above.

**Comment by ammardodin** [comment]
@sehrawat317 Have you tried the above ? If it works, can you please close the issue ?

**Comment by ehdsouza** [comment]
Closing this as @ammardodin already answered above. Feel free to reopen in case you get any problems
