### ISSUE TITLE
Python vs curl response times

### ISSUE THREAD

**Issue by dansegal1** [watson-developer-cloud/python-sdk#422]
I am seeing very slow response times on API requests to _gateway.watsonplatform.net_ via Python.

As an example:

- A [Get information about a Classifier](https://www.ibm.com/watson/developercloud/natural-language-classifier/api/v1/curl.html?curl#get-information-about-a-classifier) request to Watson NLC with Python takes **75-150 seconds** to respond.

- The same request with Curl responds instantaneously.

- The problem is also evident when calling other services; e.g., Watson NLU.

- The problem is evident only when calling the endpoint _https://gateway.watsonplatform.net/natural-language-classifier/api_ .   The problem is _not_ evident when calling the API Explorer _https://watson-api-explorer.mybluemix.net/apis/natural-language-classifier-v1_ .

- This is a recent development, first noticed about one week ago.

Please see the attached scripts for examples.

The only combination of factors that reproducibly returns a slow response is a Python call to the default endpoint _gateway.watsonplatform.net_ .

Are there any known issues, or recent changes to the environment that might cause the slow response?

#### python sdk version
1.2.1

#### python version
Issue occurs with both Python 2.7.10 and Python 3.6.1

#### OS
Mac OS High Sierra 10.13.3

#### IBM Cloud instance
US South

[nlcClassifierStatusSamplePython.txt](https://github.com/watson-developer-cloud/python-sdk/files/1853470/nlcClassifierStatusSamplePython.txt)
[nlcClassifierStatusSampleCurl.txt](https://github.com/watson-developer-cloud/python-sdk/files/1853471/nlcClassifierStatusSampleCurl.txt)

**Comment by ammardodin** [comment]
@dansegal1 the Python client library uses `requests` which relies on `urlib3` for making HTTP requests, which mostly is native Python. As for `curl`, it's pure `C` code. So it's pretty hard for  native Python code to beat it here.

As for the times you're seeing, that seems to be unusual. I tried creating scripts just like you have above, and on my machine, an SDK call to `getClassifier` takes only a little bit longer than it's equivalent in `curl`. Nonetheless, both are under a second. 

I don't believe we've made any changes that should cause a drastic change, at least on the client side. Do you see this behavior consistently ?

**Comment by dansegal1** [comment]
@ammardodin   Hi Ammar, thanks for your response.

I tested again this morning, and with no changes on my side, I am now seeing responses in the range of **0.2 to 0.25 seconds** per call to the default endpoint _gateway.watsonplatform.net_, using the same Python script as before.

So it seems to be an intermittent problem, possibly one that self-corrected since yesterday.  I'll keep an eye out for future occurrences.   Thanks again!

**Comment by ammardodin** [comment]
@dansegal1 No problem. I am going to close the issue, but feel free to reopen if you feel like there's an issue in the SDK.
