### ISSUE TITLE
watson-developer-cloud is not working with python 3x

### ISSUE THREAD

**Issue by Mukund0007** [watson-developer-cloud/python-sdk#425]
#### Expected behavior
watson-developer-cloud should be working well with python 3.5+, but it's not getting installed. 
#### Actual behavior
It's working well with python 2.7
#### Steps to reproduce the problem
Installing watson-developer-cloud with python 3.5+. importing it throws error "
![capture1](https://user-images.githubusercontent.com/32159222/38052649-9569743a-32ef-11e8-80a8-7c0cb9606a2a.JPG)
![capture2](https://user-images.githubusercontent.com/32159222/38052650-95a67e66-32ef-11e8-82c7-a9fc19ca19fc.JPG)
![capture3](https://user-images.githubusercontent.com/32159222/38052651-95e1f96e-32ef-11e8-9897-bbe91b5c0bcb.JPG)

no module found"

**Comment by ehdsouza** [comment]
Hi @Mukund0007,

As shown in your error log, it says you need "Microsoft Visual C++ Build Tools". Install it using the url shown.

**Comment by Mukund0007** [comment]
Hi ehdsouza,
The required version of VS  is already installed and configured. I am wondering how WDC is working with python2.7 but not with python 3.6. 
Here is code snippet and result for python 3.6
![py3 6](https://user-images.githubusercontent.com/32159222/38065806-c206e0d0-3322-11e8-9251-882c43041fc0.JPG)

While when using the 
![py27](https://user-images.githubusercontent.com/32159222/38065936-4ed13fb0-3323-11e8-839d-221158a4ab9f.JPG)
same code with Python 2.7 on the same machine its working fine.

I have done all trial and error. but not getting success. I could have progressed with Python 2.7 but another module which I am using in the same script does not have support in Python 2.7. Afterall, I am concluding that WDC cannot be used with python3 which violating library module documentation which says "tested with python 2.7,3.5.3.6".
Please suggest some way around.

**Comment by ammardodin** [comment]
@Mukund0007 What you're missing is not Visual Studio itself, but the standalone compilers. Please install from [here](http://landinghub.visualstudio.com/visual-cpp-build-tools) before trying to install the WDC library.

**Comment by ehdsouza** [comment]
Closing this as its an environment issue. Feel free to reopen in case you need any more help.
