### ISSUE TITLE
Current build of master branch is failing

### ISSUE THREAD

**Issue by hill1303** [watson-developer-cloud/python-sdk#43]
From the Travis CI logs of the failures for what seems to be all supported versions of Python....

`The command "openssl aes-256-cbc -K $encrypted_c3e85137836d_key -iv $encrypted_c3e85137836d_iv -in .env.enc -out .env -d" failed and exited with 1 during .`

**Comment by germanattanasio** [comment]
Travis seems to have problems decrypting the credentials and that's why our integration tests are failing. you can run
```
pip install watson-developer-cloud --upgrade
```

**Comment by jsstylos** [comment]
#46 should address this issue in the future
