### ISSUE TITLE
TypeError: recognize() got multiple values for argument 'model'

### ISSUE THREAD

**Issue by thiagorova** [watson-developer-cloud/python-sdk#433]
Hi!
I've been trying to use your Speech to text API. I've done tests before on version 0.25 and everything worked OK for me back then.

After updating to 1.2.1, I started having a problem with selecting models 
If I don't choose a model it uses en-US_Broadband model by default, as expected. Whenever I choose the model, though, I'm getting the reported error:

> TypeError: recognize() got multiple values for argument 'model'

This is my code:
```python
stt = SpeechToTextV1(username=IBM_USERNAME, password=IBM_PASSWORD)
audio_file = open(audio, "rb")
result = stt.recognize(audio_file, content_type="audio/wav", timestamps=True, max_alternatives=3, model="pt-BR_NarrowbandModel")
```

I'm using Python 3.6.
Are models supposed to be set in a different way now? I've looked around a bit (including the example here: [speech_to_text_v1.py](https://github.com/watson-developer-cloud/python-sdk/blob/master/examples/speech_to_text_v1.py)), but I couldn't find anything explaining possible changes in this.
thanks!

**Comment by ehdsouza** [comment]
Hi @thiagorova,

Look at the method signature as described in the migration guide of 1.1.0 : https://github.com/watson-developer-cloud/python-sdk/wiki/Migration

The initial parameter is a model but you have given in `audio_file`. Change your call to:
```python
result = stt.recognize(audio=audio_file, content_type="audio/wav", timestamps=True, max_alternatives=3, model="pt-BR_NarrowbandModel")
```

**Comment by thiagorova** [comment]
aha! 
thanks a lot! Sorry for the inconvenience.
