### ISSUE TITLE
What does "workspace_id" refers to

### ISSUE THREAD

**Issue by atinesh-s** [watson-developer-cloud/python-sdk#437]
What does "workspace_id" refers to in the code. On running the code mentioned, I am getting this error 

`NameError: name 'workspace_id' is not defined`

**Comment by ammardodin** [comment]
@atinesh-s Thanks for opening the issue. `workspace_id` is a GUID for a Watson Assistant/Conversation service workspace that you create via calling `createWorkspace` in the python-client library. Can you possibly post the snippet you're using so that we can help you further ?

**Comment by atinesh-s** [comment]
Here is the code

```
from watson_developer_cloud import AssistantV1

assistant = AssistantV1(
    username='xxx',
    password='yyy',
    version='2017-04-21')

assistant.set_http_config({'timeout': 100})
response = assistant.message(
workspace_id=workspace_id, 
input={'text': 'What\'s the weather like?'}
)
print(json.dumps(response, indent=2))
```
xxx and yyy is replaced with username and password of watson serice that I trying to access.

**Comment by ehdsouza** [comment]
Closing this as its not a sdk issue. Feel free to reopen if you need to.
