### ISSUE TITLE
Dialog update_profile does not work

### ISSUE THREAD

**Issue by Navneet23** [watson-developer-cloud/python-sdk#44]
The update_profile method for DialogV1 does not work. I have found the issue is that client_id is not passed as it should be along with the name_values according to the API explorer:

https://watson-api-explorer.mybluemix.net/apis/dialog-v1#!/Content/putAppFile

Please update this method and also if possible add some examples for the dialogV1 class.

**Comment by jsstylos** [comment]
Good catch. Working on this, but still trying to get a working example.

**Comment by jsstylos** [comment]
I added code that should fix this, although note that variables must be defined in the dialog before they can be set. In the SDK variables can either be set as a list like [{'name': 'name1', 'value': 'value1'}] or as a dict like {'name1': 'value1', 'name2': 'value2'}. Let me know if this works for you.
