### ISSUE TITLE
watson_developer_cloud.watson_developer_cloud_service.WatsonException: Error: Too many fields, Code: 500

### ISSUE THREAD

**Issue by vkg70** [watson-developer-cloud/python-sdk#440]
```
 with open(filepath) as infile:
    add_doc = discovery.add_document("{environment_id}", "{collection_id}", file=infile, metadata=metadata)
    print(json.dumps(add_doc, indent=2))
```

getting this error:
```
Traceback (most recent call last):
  File "testupload.py", line 46, in <module>
    add_doc = discovery.add_document("xxxxxxxx", "xxxxxxx", file=infile, metadata=metadata)
TypeError: add_document() got an unexpected keyword argument 'file'
```

**Comment by vkg70** [comment]
modified the code to remove the "file=" keyword but now metadata part is not working

  filepath = ' payload[i]["html"]
  metadata = json.dumps(payload[i]['metadata'])
  with open(filepath) as infile:
    add_doc = discovery.add_document("6f49c54a-ed0e-4ba8-a1d5-1ef5b34c948d", "91c04f3f-2a21-4282-ba77-cb39169b572b", infile, metadata=metadata)
    print(json.dumps(add_doc, indent=2))

Traceback (most recent call last):
  File "testupload.py", line 46, in <module>
    add_doc = discovery.add_document("xxxxxxxx", "xxxxxx", infile, metadata=payload[i]['metadata'])
  File "/Library/Python/2.7/site-packages/watson_developer_cloud/discovery_v1.py", line 281, in add_document
    accept_json=True)
  File "/Library/Python/2.7/site-packages/watson_developer_cloud/watson_developer_cloud_service.py", line 324, in request
    raise WatsonException(error_message)
watson_developer_cloud.watson_developer_cloud_service.WatsonException: Error: Too many fields, Code: 500

**Comment by ehdsouza** [comment]
HI @vkg70 ,

How big is the metadata? Here is the specification for metadata: ```metadata: If you're using the Data Crawler to upload your documents, you can test a document against the type of metadata that the Data Crawler might send. The maximum supported metadata file size is 1 MB. Metadata parts larger than 1 MB are rejected. Example:  ``` {   \"Creator\": \"Johnny Appleseed\",   \"Subject\": \"Apples\" } ```.```

Also, did you test the command using curl?

**Comment by vkg70** [comment]
Hi, I'm sure the metadata size is less than 1KB. The add_documents with the same file and metadata size works with node.js code, so I'm sure the metadata size it in accordance to the limits. I just want to switch over to python since i will have more control over the throttling the uploads when the service runs out of threads. Do you still want me to try the curl?

**Comment by mkistler** [comment]
I just tested this on my system and it seems to be working:
```
import json
import watson_developer_cloud

discovery_username = 'xxxxxxxxxxxx'
discovery_password = 'yyyyyyyyyyy'
discovery_version = '2017-08-01'

discovery = watson_developer_cloud.DiscoveryV1(
    discovery_version,
    username = discovery_username,
    password = discovery_password)

environment_id = 'b920a7d4-2188-4f81-8c3e-690a6621df57'
collection_id = 'b469e665-ef2a-454d-bd39-737cfe2a6876'

filepath = 'sample.html'
metadata = json.dumps({"stuff": "woot"})
with open(filepath) as infile:
    add_doc = discovery.add_document(environment_id, collection_id, file=infile, metadata=metadata)
    print(json.dumps(add_doc, indent=2))
```

The result it printed was:
```
{
  "status": "processing", 
  "document_id": "8e00ba3a-8089-4ebf-a1b1-3c2ed35dab1a"
}
```

**Comment by vkg70** [comment]
I didn't had the latest SDK. You can close the issue. Thanks for checking.
