### ISSUE TITLE
AssistantV1 vs. ConversationV1

### ISSUE THREAD

**Issue by jessie831024** [watson-developer-cloud/python-sdk#455]
what's the difference between AssistantV1 and ConversationV1?

**Comment by ehdsouza** [comment]
AssistantV1 is rebranding of ConversationV1. You can use the username/password of conversation when using assistant services.
All new features would be eventually added to AssistantV1. https://console.bluemix.net/docs/services/conversation/index.html#about

**Comment by germanattanasio** [comment]
I'm closing this since it's not related to the SDK
