### ISSUE TITLE
How to make continuous transmission in speech to text

### ISSUE THREAD

**Issue by karteek-paruchuri** [watson-developer-cloud/python-sdk#47]
The transcribe function stops once it encounters a pause. How do I extend the time? https://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/doc/speech-to-text/input.shtml#timeouts
In this link I believe I need to play with continuous transmission but I'm unsure how to fit this in this code. Can you please help

**Comment by jsstylos** [comment]
The continuous=True input field specifies that recognition should continue after the first silence, such as: `speech_to_text.recognize(audio_file, content_type='audio/wav', continuous=True)`

**Comment by karteek-paruchuri** [comment]
Thankyou.
