### ISSUE TITLE
Watson NLU sentiment value for some sentences goes in to Negative.

### ISSUE THREAD

**Issue by abhijitdalavi** [watson-developer-cloud/python-sdk#482]
#### Actual behavior
Example:
sentence: global variables decreases the cohesion of a program.
sentiment score : -0.574183.
sentiment value: Negative

#### Expected behavior
**It should give the positive sentiment value for the sentence.**  I have checked that the sentiment value is retrieved due to some negative words.
Example:
sentence: global variables decreases the cohesion of a program.
sentiment value: Positive.

#### python sdk version
1.3.5
#### python version
3.6.5

**Comment by ammardodin** [comment]
@abhijitdalavi This is not an SDK issue.

**Comment by ehdsouza** [comment]
Closing as not a SDK issue
