### ISSUE TITLE
error: command 'cl.exe' failed: No such file or directory

### ISSUE THREAD

**Issue by elibroftw** [watson-developer-cloud/python-sdk#483]
#### Expected behavior
For it to install
#### Actual behavior

```
error: command 'cl.exe' failed: No such file or directory

----------------------------------------
Command "c:\users\maste\appdata\local\programs\python\python36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\maste\\AppData\\Local\\Temp\\pip-install-yjbswkx8\\Twisted\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\maste\AppData\Local\Temp\pip-record-2tmsb3sv\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\maste\AppData\Local\Temp\pip-install-yjbswkx8\Twisted\
```

#### Steps to reproduce the problem

```
pip install watson-developer-cloud
```

Also:

```
pip install --ignore-installed six watson-developer-cloud
```

#### python sdk version
????
#### python version
3.6.5

**Comment by ehdsouza** [comment]
Hi,

You may want to look into this: https://stackoverflow.com/questions/41724445/python-pip-on-windows-command-cl-exe-failed

**Comment by germanattanasio** [comment]
@ehdsouza we need to find a better library because the one we have seems to be associated with a lot of issues. Lots of users reporting errors while installing the library.. 😭

**Comment by ammardodin** [comment]
@germanattanasio @ehdsouza I did verify that in fact it is the `Twisted` library that's causing the installation issues in bare Windows envs without Visual Studio build tools.

**Comment by jeffpk62** [comment]
I believe that was the library that caused me so many problems a few weeks back, @ammardodin.  I don't think I copied you on those messages; sorry.

**Comment by ehdsouza** [comment]
I would have to look into https://github.com/websocket-client/websocket-client as mentioned by https://github.com/watson-developer-cloud/python-sdk/issues/402#issuecomment-378869964
