### ISSUE TITLE
Improper error handling on language parameter of create_workspace

### ISSUE THREAD

**Issue by victorzhao1990** [watson-developer-cloud/python-sdk#484]
#### Expected behavior
When a unknown language ID is passed in, it should be either identified at API level or trigger proper exception in SDK.
#### Actual behavior
Error code is returned without meaningful message.
`watson_developer_cloud.watson_service.WatsonApiException: Error: Invalid Request Body, Code: 400`
#### Steps to reproduce the problem
```
response = assistant.create_workspace(
    name='API test',
    description='Example workspace created via API',
    language=''  # Empty string
)
```
#### Code snippet (Note: Do not paste your credentials)
Same as above
#### python sdk version
1.3.5
#### python version
3.6.4

**Comment by ehdsouza** [comment]
The `info` would be part of the error message in the next release. PR: https://github.com/watson-developer-cloud/python-sdk/pull/485
