### ISSUE TITLE
Error message propagation for Natural Language Classifier

### ISSUE THREAD

**Issue by CatherineCao2016** [watson-developer-cloud/python-sdk#486]
#### Expected behavior
I fed a csv file containing tabs or new lines to the NLC API and got the following error message in the Jupyter Notebook: 

"WatsonApiException: Error: Malformed data, Code: 400 , X-dp-watson-tran-id: gateway02-778499955 , X-global-transaction-id: ffea405d5b1008e82e66f773." 

But if test it locally using cURL, the message looks like this:

"code" : 400,
 "error" : "Malformed data",
 "description" : "One or more fields in the training data at line 38"

So it seems the error message has not been properly propagated from the service as suggested by @venkatg.

#### python sdk version
1.3.5
#### python version
3.5

**Comment by ehdsouza** [comment]
HI @CatherineCao2016,

You can do:
```python
try:
 <your code>
except WatsonApiException as e:
  print(e.info)
```
Yesterday we had a PR to add the `info` in the error message: https://github.com/watson-developer-cloud/python-sdk/pull/485
