### ISSUE TITLE
sst and tts examples are out of date

### ISSUE THREAD

**Issue by ArthurKantor** [watson-developer-cloud/python-sdk#49]
@jsstylos:
The model voice names have changed in 
https://github.com/watson-developer-cloud/python-sdk/blob/master/examples/speech_to_text_v1.py
https://github.com/watson-developer-cloud/python-sdk/blob/master/examples/text_to_speech_v1.py

**Comment by jsstylos** [comment]
I'm not sure how the examples are out of date; the code dynamically loads the voices and models. Am I missing something?

**Comment by ArthurKantor** [comment]
sorry, linked to the wrong files:  it's the tests that look out of date:
https://github.com/watson-developer-cloud/python-sdk/blob/master/test/test_speech_to_text_v1.py
https://github.com/watson-developer-cloud/python-sdk/blob/master/test/test_text_to_speech_v1.py

**Comment by jsstylos** [comment]
Ok -- the unit tests have not been kept up to date, but don't have to exactly match the service output either, since, they're mocking the server. I may remove these if we don't have test resources to keep them up to date, since we already have the integration tests.
