### ISSUE TITLE
Will there be a RPC based SDK in the future?

### ISSUE THREAD

**Issue by victorzhao1990** [watson-developer-cloud/python-sdk#491]
#### Expected behavior
RPC over TCP

**Comment by ammardodin** [comment]
@victorzhao1990 Thanks for opening the issue. Can you elaborate on what is your use case? It would really help for us in term of planning.

cc @ehdsouza @germanattanasio

**Comment by germanattanasio** [comment]
I'm gonna wait for @victorzhao1990 to provide the use case but close this since it's not an issue with the SDK
