### ISSUE TITLE
Authentication is a mess across regions - examples out of sync. no examples across regions

### ISSUE THREAD

**Issue by nkeilar** [watson-developer-cloud/python-sdk#501]
#### Expected behavior
I can read docs and use the SDK to authenticate the examples across any region

#### Actual behavior
passwords method / IAM method / Manually obtaining tokens is basically guess work at this point. 

#### Steps to reproduce the problem
Ask a senior developer who hasn't used IBM Cloud to try to run this example. https://github.com/watson-developer-cloud/python-sdk/blob/develop/examples/assistant_v1.py

Or even this: 

```
from watson_developer_cloud import AssistantV1

watson_assistant = AssistantV1(
    version='2018-06-26',
    iam_api_key='X'
)

watson_assistant.set_url('https://gateway-syd.watsonplatform.net/assistant/api/')
watson_assistant.list_workspaces()
```

```
$ python docs_example.py 
Traceback (most recent call last):
  File "docs_example.py", line 10, in <module>
    watson_assistant.list_workspaces()
  File "/Users/nathank/workspace/cnxion-watson/venv/lib/python3.5/site-packages/watson_developer_cloud/assistant_v1.py", line 385, in list_workspaces
    accept_json=True)
  File "/Users/nathank/workspace/cnxion-watson/venv/lib/python3.5/site-packages/watson_developer_cloud/watson_service.py", line 463, in request
    info=error_info, httpResponse=response)
watson_developer_cloud.watson_service.WatsonApiException: Error: Unauthorized: Access is denied due to invalid credentials , Code: 401
```

#### Code snippet (Note: Do not paste your credentials)
not clear which values to use for sydney region or `url` or `iam_url`

#### python sdk version
watson-developer-cloud==1.4.0

#### python version
Python 3.5.1

**Comment by ehdsouza** [comment]
Hi @nkeilar ,

Thanks for your input. I totally agree with you that we need clear information for `url` in different regions. I would update the documentation with that information.

In the meantime, https://github.com/watson-developer-cloud/python-sdk/blob/develop/examples/assistant_v1.py examples are for instances using cloud foundry with default url to `us-south`. In case you are using cloud foundry instance and would like to update the service url to sydney region
```
assistant = AssistantV1(
    username='YOUR SERVICE USERNAME',
    password='YOUR SERVICE PASSWORD',
    url='https://gateway-syd.watsonplatform.net/assistant/api' #the one shown on your dashboard
    version='2017-04-21')
```

`iam_url` would be the default one for all regions unless you want to manually change it.

Please let me know if you have any questions.

**Comment by nkeilar** [comment]
Thanks for your response, but nothing I try works. I just want to run a python script to list workspaces... Ideally I could connect with the Assistant service I created but baby steps, just authentication working after 2 days of trying things would sure be nice. List of things I've tried is as long as my arm. 

`watson_developer_cloud.watson_service.WatsonApiException: Error: Unauthorized: Access is denied due to invalid credentials , Code: 401`

I've gone to https://console.bluemix.net/iam/#serviceids and created credentials and give access to `Watson Assistant`, generated an API key, and put that into 

```
from watson_developer_cloud import AssistantV1

watson_assistant = AssistantV1(
    version='2018-06-26',
    iam_api_key='X'
)

watson_assistant.set_url('https://gateway-syd.watsonplatform.net/assistant/api/')
watson_assistant.list_workspaces()
```

No dice. Should this work? What am I missing?

**Comment by nkeilar** [comment]
@ehdsouza Also, I'm inclined to this this should be tagged as a bug, as well as support. I'm opening it because I've tried everything and the service still does not work with currently version.

**Comment by nkeilar** [comment]
Okay, I got it working eventually. I have a feeling that the SDK is cacheing tokens behind the scenes. I'll keep trying to reproduce the problem. I dropped back to curl to figure out what would actually work. Initially nothing did, manually created IAM keys or service ones. After:
- nuking all service keys and api keys in the https://console.bluemix.net/iam/#/serviceids UI
- relaunching a service instance (causing new keys to be created) 
- verifying that service id worked via curl with

```
curl -k -X POST   --header "Authorization: Basic Yng6Yng="   --header "Content-Type: application/x-www-form-urlencoded"   --header "Accept: application/json"   --data-urlencode "grant_type=urn:ibm:params:oauth:grant-type:apikey"   --data-urlencode "apikey={{apikey}}"   "https://iam.bluemix.net/identity/token"
```

Note 1: where apikey is the value from https://console.bluemix.net/dashboard/apps?category=watson
Note 2: be wary, its hard to see that this response actually includes two keys in the terminal you only need the access token (note refresh token for the next step)

created token.txt with 
```
Authorization: Bearer {{access token}}
```

then
```
curl -X GET --header "$(cat token.txt)" "https://gateway-syd.watsonplatform.net/assistant/api/v1/workspaces?version=2018-02-16"
```

should produce something like this
```
"
{"workspaces":[{"name":"REDACTED","language":"en","metadata":{"api_version":{"major_version":"v1","minor_version":"2017-05-26"}},"description":"","workspace_id":"REDACTED","system_settings":{"disambiguation":{"prompt":"Did you mean:","none_of_the_above_prompt":"None of the above"},"human_agent_assist":{"prompt":"Did you mean:"}},"learning_opt_out":false}],"pagination":clear
```

at which point you can move to redo the above with python sdk

```
watson_assistant = AssistantV1(
    version='2018-02-16',
    iam_api_key='{{apikey}}',
    iam_url='https://iam.bluemix.net/identity/token',
    url='https://gateway-syd.watsonplatform.net/assistant/api',
)
watson_assistant.list_workspaces()
```

which should produce no output and just return to prompt

Note: use the api key, not the token from curl - don't confuse yourself 

Hope these debugging steps help someone else.

**Comment by axelauvinen** [comment]
Even though this is closed I have to say that it is a mess. I'm trying to get one request through to version 2 of assistant with node-sdk, and I literally have no clue what credentials, urls and version numbers to use. I know Assistant-v2 is on beta, but even so, if the baseline is this I'm feeling reluctant to use the service.

**Comment by ehdsouza** [comment]
Sorry to hear that. We will work upon updating the `README` with a more details.
