### ISSUE TITLE
wrong content type for metadata in add_document

### ISSUE THREAD

**Issue by osidorkin** [watson-developer-cloud/python-sdk#506]
#### Expected behavior
mime type for metadata should be `application/json`

#### Actual behavior
it's `text/plain` so WDS API doesn't accept it

#### Steps to reproduce the problem
just upload document with metadata

#### Code snippet (Note: Do not paste your credentials)
```
        metadata_tuple = (None, metadata, 'text/plain')
```

#### python sdk version
1.4.1

#### python version
2.7

**Comment by ehdsouza** [comment]
Hi @osidorkin,

Could you explain why it should be `application/json`, I just tried and the WDS accepts `text/plain`.

```python
import json
import sys
import os
from watson_developer_cloud import DiscoveryV1

discovery = DiscoveryV1(
    version="2017-11-07",
    username="<username>",
    password="<password>"
)

metadata = '{\"Creator\": \"Johnny Appleseed\", \"Subject\": \"Apples\" }'

with open("test.txt") as fileinfo:
    add_doc = discovery.add_document(environment_id, collection_id, fileinfo, file_content_type='application/json', metadata=metadata)
print(json.dumps(add_doc, indent=2))
```

**Comment by osidorkin** [comment]
it seems that it was an error in one of previous version of SDK or server API which forced us to use custom add document code with application/json content type. please close this issue if it's not relevant anymore.
