### ISSUE TITLE
Rename `iam_api_key` to be `iam_apikey` like in our other sdks

### ISSUE THREAD

**Issue by germanattanasio** [watson-developer-cloud/python-sdk#520]

**Comment by SirSpidey** [comment]
When this gets changed, the docgen templates also need to be changed. And if the api-definition examples are already updated to IAM, those will need to be updated as well.

**Comment by SirSpidey** [comment]
@ehdsouza Did you create an issue to update the watson-docgen project so the API docs are updated?

**Comment by ehdsouza** [comment]
@SirSpidey it is added here: https://github.ibm.com/Watson/developer-experience/issues/5361
