### ISSUE TITLE
Main thread blocks

### ISSUE THREAD

**Issue by leonbrag** [watson-developer-cloud/python-sdk#522]
It appears that when speech_to_text.recognize_with_websocket call is made, the execution happens on the main thread (the thread which made call to  speech_to_text.recognize_with_websocket)

Therefore main thread blocks, even though results comes in async fashion (by invoking appropriate methods from the class passed as  recognize_callback parameter to the call above.

Since it's async call back model is used, should SDK handle threading and ensure that main execution is not blocked (by calling creating a second thread and calling peech_to_text.recognize_with_websocket on that thread)?

Snippets:

```

with open ("blah.mp3"], 'rb') as audio_file:	
		speech_to_text.recognize_with_websocket(
		audio=audio_file,
		content_type='audio/mp3',
		model='en-US_NarrowbandModel',
		recognize_callback=myRecognizeCallback,
		interim_results=False,
		keywords=["blah"],
		keywords_threshold=0.5,
		speaker_labels=True,
		timestamps=True,
		max_alternatives=3)


              #### PROBLEM. EXECUTION DOES NOT GO TO NEXT LINE UNTIL RESULTS COME BACK
              while not myRecognizeCallback.event.is_set():
	 	     print ("Waiting")

class MyRecognizeCallback(RecognizeCallback):
        ...
	def on_data(self, data):
		...
		with open ("dump.txt", "w") as file:
			file.write (json.dumps(data, indent=2))
		self.event.set()
```

Python: 3.6

thanks

**Comment by leonbrag** [comment]
Thanks. Is there an eta on next version?

It would also be good to provide intermediate progress report callback notifications, if Watson provides such notifications (like x% completed)

**Comment by leonbrag** [comment]
@ehdsouza - just checking which version of the Python SDK will have async support.
thanks

**Comment by ehdsouza** [comment]
Actually, I have an example of async example in the v2.0 branch. You can have something similar

```py
import threading

mycallback = MyRecognizeCallback()
audio_file = open(join(dirname(__file__), '../resources/speech.wav'), 'rb')
recognize_thread = threading.Thread(target=speech_to_text.recognize_using_websocket, args=(audio_source, "audio/l16; rate=44100", mycallback))
recognize_thread.start()
```

**Comment by leonbrag** [comment]
Thank you. While this will unblock main thread, I was hoping SDK to provide intermediate notifications from Watson, to truly benefit form async nature of web sockets. Currently when Python SDK is used with web sockets, registered callback is only called when entire transcription completed.

**Comment by ehdsouza** [comment]
@leonbrag, you could try setting `interim_results=True`.

**Comment by leonbrag** [comment]
I did. Watson Python SDK sill invokes call back only once, when Watson completed entire transcription.

**Comment by ehdsouza** [comment]
https://console.bluemix.net/docs/services/speech-to-text/websockets.html#websockets
>When it is done sending the audio data for a request to the service, the client must signal the end of the binary transmission to the service.
By sending a JSON text message with the action parameter set to the value stop:
{'action': 'stop'}
By sending an empty binary message, one in which the specified blob is empty:
websocket.send(blob)

Right now, it is sending the `{action: stop}` once the entire audio is sent. 

It would give you interim results if you have empty binary

**Comment by leonbrag** [comment]
But unless I misunderstand, Watson Python SDK abstracts all the communication with web sockets (so my does not directly send JSON to end point). How would I call Watson Python SDK to get interim results while transcribing large file. Is there Python SDK example to look at?

**Comment by ehdsouza** [comment]
Closing this as there is no sdk bug
