### ISSUE TITLE
NLU- "cannot convert dictionary update sequence element #0 to a sequence"

### ISSUE THREAD

**Issue by stephen-goveia** [watson-developer-cloud/python-sdk#536]
#### Expected behavior
Return payload
#### Actual behavior
Error: "cannot convert dictionary update sequence element #0to a sequence"

#### python sdk version
1.6.0
#### python version
2.7

While using 0.26.1 my application worked. After upgrading to 1.6.0, I began getting the stated error. Please advise.

**Comment by ehdsouza** [comment]
@stephen-goveia could you provide a code snippet?

**Comment by stephen-goveia** [comment]
@ehdsouza thanks for the quick response! Actually I have figured out the issue. I failed to see the changes in the API's from 0.26.0 to 1.6.0 For example:

### imports
**v0.26.0**
```
import watson_developer_cloud
import watson_developer_cloud.natural_language_understanding.features.v1 as features
```
**v1.6.0**
```
from watson_developer_cloud import NaturalLanguageUnderstandingV1
from watson_developer_cloud.natural_language_understanding_v1 \
    import Features, EntitiesOptions, KeywordsOptions, ConceptsOptions, CategoriesOptions, EmotionOptions, MetadataOptions, RelationsOptions, SemanticRolesOptions, SentimentOptions

```

### Also getting client has changed:
**v0.26.0**
```
nlu = watson_developer_cloud.NaturalLanguageUnderstandingV1(
    version=version, username=username, password=password)
```

**v1.6.0**
```
nlu = NaturalLanguageUnderstandingV1(
    version=version, username=username, password=password)
```

### And getting the features has changed as well...

**v0.26.0**
```
feature = features.SemanticRoles(
            entities=entities, keywords=keywords, limit=limit)
```

**v1.6.0**
```
feature = Features(semantic_roles=SemanticRolesOptions(
            entities=entities, keywords=keywords, limit=limit))
```


After these updates my application is working fine again, hopefully this helps someone else. 

Thanks!!
