### ISSUE TITLE
Errors while running microphone-speech-to-text.py on Ubuntu 14.04

### ISSUE THREAD

**Issue by Mohammed-Tag-ElAsfia** [watson-developer-cloud/python-sdk#538]
#### Expected behavior
When I run the file microphone-speech-to-text.py, I should receive recording....

#### Actual behavior
```
  File "microphone-speech-to-text.py", line 67, in <module>
    f.write(data)
TypeError: must be str, not bytes
```
After fixing that issue you l receive:
```
recording...
Done recording...
Connection was successful
Unhandled Error
.
.
.
    (result, consumed) = self._buffer_decode(data, self.errors, final)
builtins.UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```
#### Steps to reproduce the problem

to change the 'w' to 'wb' in the open function at line 67
to add 'rb' to the open function at line 74

#### Code snippet (Note: Do not paste your credentials)
```py
print('recording....')
with open(tmp.name, 'wb') as f:
    for i in range(0, int(RATE / CHUNK * RECORD_SECONDS)):
        data = stream.read(CHUNK)
        f.write(data)

stream.stop_stream()
stream.close()
audio.terminate()
print('Done recording...')

with open(tmp.name,'rb') as f:
    speech_to_text.recognize_with_websocket(
        audio=f, recognize_callback=mycallback)
```
#### python sdk version
1.6.0

#### python version
python 3.4.3

**Comment by ehdsouza** [comment]
@Mohammed-Tag-ElAsfia , could you check if you recorded a valid audio file?

**Comment by ehdsouza** [comment]
@Mohammed-Tag-ElAsfia , did you try playing the recorded audio?

**Comment by germanattanasio** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
