### ISSUE TITLE
Session timed out 

### ISSUE THREAD

**Issue by Priya997** [watson-developer-cloud/python-sdk#542]
The audio file should be transcribed completely but sometimes in the middle of the transcription or at the end, I got an error Error received: Session timed out.

#### Steps to reproduce the problem
The problem can be reproduced using this audio file:
https://drive.google.com/file/d/1Y_1Oj2LkvdXxlj99_dhIcQwmwRlj3lMY/view?usp=sharing

#### Code snippet (Note: Do not paste your credentials)
The code is the same as in here https://github.com/watson-developer-cloud/python-sdk/blob/master/examples/speech_to_text_v1.py
The only change I made is:
```py
speech_to_text.recognize(
                continuous=True,
                audio=audio_file,
                content_type='audio/wav',
                Transfer_Encoding='chunked',
                timestamps=True,
                word_confidence=True,
                inactivity_timeout='-1'),
            indent=2))
```
#### python sdk version
watson-developer-cloud==1.7.0
#### python version
Python 3.6.5

**Comment by ehdsouza** [comment]
Hi,

Did you try using the `recognize_using_websockets` method instead?

**Comment by Priya997** [comment]
Hey, yes I have tried that also..Same issue thought

**Comment by ehdsouza** [comment]
@Priya997,

which version of sdk are you using? The parameters that you pass are in a very old release.

Also, we are coming with a new major release having a new websocket library.

**Comment by Priya997** [comment]
Thanks, I resolved the issue :D
