### ISSUE TITLE
Watson Assistant: SSLError

### ISSUE THREAD

**Issue by toto222** [watson-developer-cloud/python-sdk#549]
Hi !

I want to develop a chatbot with Watson Assistant with python.
But, with a very simple code I have frequently thir error message:

```console
SSLError: HTTPSConnectionPool(host='gateway.watsonplatform.net', port=443): 
Max retries exceeded with url: /assistant/api/v1/workspaces?version=2018-07-10 
(Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')",),)) 
```

I just execute the following code:
```python
import json
import watson_developer_cloud

assistant = watson_developer_cloud.AssistantV1(
    username='{username}',
    password='{password}',
    version='2018-07-10'
)

response = assistant.list_workspaces()

print(json.dumps(response, indent=2))
```

And it is random, sometimes this code works very fast about 0.2s (1 time on 10), sometimes it takes about 60s (about 3 times on 10), the other times I have this error.

I am using Watson-Developer-Cloud 1.7.0 and Python 3.6.5.

Can you help me please ?
Do you know to solve this very constraining problem please ?

I did some search but I found nothing about that.

Thanks !

**Comment by ehdsouza** [comment]
HI @toto222,

Are you behind a firewall? This looks like a service issue, Ill notify the Assistant team.

**Comment by toto222** [comment]
Hi @ehdsouza 

Yes, I am behind a firewall, but entering connexions are permitted for python... (I will desactivate its te see if something change, but it would be surprinsing)

Thank you very much for the notification

**Comment by toto222** [comment]
UP

**Comment by germanattanasio** [comment]
🤔

**Comment by ehdsouza** [comment]
@toto222, are you still facing this problem?

**Comment by toto222** [comment]
Yes, always the same problem.
Sometimes my Python code cannot run for an hour...

Nobody has already facing that ?

**Comment by toto222** [comment]
UP (please... anyone ?)

**Comment by germanattanasio** [comment]
@toto222 try to create a new service instance and delete the one you are using. It could be related to your service instance.

ARe you using the latest version of the sdk?

**Comment by ehdsouza** [comment]
Could you send the debugs log of http:
```try:
   import http.client as http_client
except ImportError:
   # Python 2
   import httplib as http_client
http_client.HTTPConnection.debuglevel = 1```

**Comment by toto222** [comment]
Hi !

I finally created Node JS files to communicate with Watson Assistant.
Then, I made some calls to my Node JS code in my python code.

I had to sent my project October 1st, and the solution is fast and works perfectly.

Thanks for your help.

**Comment by RVKRM** [comment]
Hi 

Am still facing below error 

`ssl.SSLError: ("bad handshake: SysCallError(54, 'ECONNRESET')",) 
``MaxRetryError: HTTPSConnectionPool(host='gateway-fra.watsonplatform.net', port=443): Max retries exceeded with url: 
`
Can you help me please ?
Do you know to solve this very constraining problem please ?
