### ISSUE TITLE
Request how to send OPUS format audio data to Speech to Text services using python

### ISSUE THREAD

**Issue by saravana8888** [watson-developer-cloud/python-sdk#555]
Please share the source code to send OPUS format audio data to Speech to Text services using python in Linux Platform

User Input: Audio data via Microphone in Linux (Ubuntu) Platform

**Comment by ehdsouza** [comment]
@saravana8888 ,

Here are the various content types that are supported: https://www.ibm.com/watson/developercloud/speech-to-text/api/v1/curl.html?curl#recognize

Just pass in the `Content-Type` based on your audio.
