### ISSUE TITLE
JSON from get_dialog in Dialog API throws an exception when trying to import back into the dialog

### ISSUE THREAD

**Issue by jagan120** [watson-developer-cloud/python-sdk#56]
So I faced this issue according to the last comment on #31. I got around it by removing accept_json parameter from the request and extracting raw content from the request object.

```python
def get_dialog(dialog_id, accept='application/wds+json'):
        #accept_json = False
        headers = {'accept' : accept}
        auth = HTTPBasicAuth(config.username, config.password)
        return request(method='GET', url='https://gateway.watsonplatform.net/dialog/api/v1/dialogs/{0}'.format(dialog_id), auth=auth, headers=headers).content
```

I can submit a pull request if you approve these changes.

**Comment by jsstylos** [comment]
The new code sets `accept_json` only when setting `accept` = `application/wds+json` (which is the default). Are you getting an exception when trying to get JSON, and if so is the response a valid JSON?

**Comment by jagan120** [comment]
The JSON is valid. But the issue is the JSON returned by the method with accept_json being true is throwing an exception when trying to import it into a dialog. I dont have this issue when I get the JSON as a return from request().content with accept_json being false.

**Comment by jsstylos** [comment]
I don't understand what's throwing the exception, if not a JSON parsing error. What do you mean by "when trying to import it into a dialog"?

**Comment by jsstylos** [comment]
@jagan120: Do you have a test case you can give me that creates a dialog and then throws an exception trying to get it?
