### ISSUE TITLE
From microphone recording for 5 second and sending to IBM Cloud STT Service taking 7-10 seconds

### ISSUE THREAD

**Issue by yashpatel001** [watson-developer-cloud/python-sdk#561]
#### Expected behavior

I want response from IBM Cloud Speech to text service response within 1 second
#### Actual behavior

Actual time taking by IBM SDK Code is 10 seconds.

#### Steps to reproduce the problem

```py
#### Code snippet (Note: Do not paste your credentials)
from __future__ import print_function
import pyaudio
from watson_developer_cloud import SpeechToTextV1
from watson_developer_cloud.websocket import RecognizeCallback, AudioSource
from threading import Thread

try:
    from Queue import Queue, Full
except ImportError:
    from queue import Queue, Full

###############################################
#### Initalize queue to store the recordings ##
###############################################
CHUNK = 1024
# Note: It will discard if the websocket client can't consumme fast enough
# So, increase the max size as per your choice
BUF_MAX_SIZE = CHUNK * 10
# Buffer to store audio
q = Queue(maxsize=int(round(BUF_MAX_SIZE / CHUNK)))

# Create an instance of AudioSource
audio_source = AudioSource(q, True, True)

###############################################
#### Prepare Speech to Text Service ########
###############################################

# initialize speech to text service
speech_to_text = SpeechToTextV1(
    username='YOUR SERVICE USERNAME',
    password='YOUR SERVICE PASSWORD',
    url='https://stream.watsonplatform.net/speech-to-text/api')

# define callback for the speech to text service
class MyRecognizeCallback(RecognizeCallback):
    def __init__(self):
        RecognizeCallback.__init__(self)

    def on_transcription(self, transcript):
        print(transcript)

    def on_connected(self):
        print('Connection was successful')

    def on_error(self, error):
        print('Error received: {}'.format(error))

    def on_inactivity_timeout(self, error):
        print('Inactivity timeout: {}'.format(error))

    def on_listening(self):
        print('Service is listening')

    def on_hypothesis(self, hypothesis):
        print(hypothesis)

    def on_data(self, data):
        print(data)

    def on_close(self):
        print("Connection closed")

# this function will initiate the recognize service and pass in the AudioSource
def recognize_using_weboscket(*args):
    mycallback = MyRecognizeCallback()
    speech_to_text.recognize_using_websocket(audio=audio_source,
                                             content_type='audio/l16; rate=44100',
                                             recognize_callback=mycallback)

###############################################
#### Prepare the for recording using Pyaudio ##
###############################################

# Variables for recording the speech
FORMAT = pyaudio.paInt16
CHANNELS = 1
RATE = 44100

# define callback for pyaudio to store the recording in queue
def pyaudio_callback(in_data, frame_count, time_info, status):
    try:
        q.put(in_data)
    except Full:
        pass # discard
    return (None, pyaudio.paContinue)

# instantiate pyaudio
audio = pyaudio.PyAudio()

# open stream using callback
stream = audio.open(
    format=FORMAT,
    channels=CHANNELS,
    rate=RATE,
    input=True,
    frames_per_buffer=CHUNK,
    stream_callback=pyaudio_callback,
    start=False
)

#########################################################################
#### Start the recording and start service to recognize the stream ######
#########################################################################

print("Enter CTRL+C to end recording...")
stream.start_stream()

try:
    recognize_thread = Thread(target=recognize_using_weboscket, args=())
    recognize_thread.start()

    while True:
        pass
except KeyboardInterrupt:
    # stop recording
    audio_source.completed_recording()
    stream.stop_stream()
    stream.close()
audio.terminate()
```

#### python version

3.0

**Comment by germanattanasio** [comment]
@yashpatel001 I think the latency issue is probably because you are using the lite plan which is being shared with all the free users. You will have more latency than if you pay for a premium or standard plan.

**Comment by germanattanasio** [comment]
Take a look at https://gist.github.com/3demax/4653037

**Comment by krishnacs2** [comment]
Hi germanattanasio,

i want convert french conversations. Please give code for this.


Thanks,
Krishna

**Comment by germanattanasio** [comment]
@krishnacs2 I think the example [here](https://github.com/watson-developer-cloud/python-sdk/blob/master/examples/microphone-speech-to-text.py) should work, you need to specify the french model.

**Comment by krishnacs2** [comment]
Thanks working fine

**Comment by krishnacs2** [comment]
Hi germanattanasio,

I need a small help on text to speech. In text to speech service giving the "response.content" eg (ID3#TSSELavf57.83.100ÿóÄð-A¬'0Ãçò?Á\?ÿ?ÿÿÿ.}X­) code and we are writing it into .wav file finally .wav file saving in our desc. 

Our requirement is without saving the .wav file into desc, we have to play the the sound from "response.content" example small part (ID3#TSSELavf57.83.100ÿóÄð-A¬'0Ãçò?Á\?ÿ?ÿÿÿ.}X­) in Python.

Please post a code for above requirement.

We have play the sound of response.context without saving .wav file in Python.

Thanks,
Krishna

**Comment by germanattanasio** [comment]
@yashpatel001 the audio that you synthesize is a `.wav` But it doesn't have the size information at the beginning so most audio players will fail when trying to reproduce it. You can select a different audio format or update the header before writing the file to disk

**Comment by krishnacs2** [comment]
Hi germanattanasio,

I have done with above example and working file for live streaming voice to text as a standalone python program.

Actually we are looking for REST API for the same functionality for live streaming speech to text using IBM Watson.

Please post the curl code or python code to call live streaming IBM Watson API for speech to text(live voice using micro phones)

Like below code: 

curl -X POST -u "{username}:{password}" "https://stream.watsonplatform.net/speech-to-text/api/v1/register_callback?callback_url=http://{user_callback_path}/job_results&user_secret=ThisIsMySecret"

Thanks
Krishna
