### ISSUE TITLE
Natural Language Understanding use model deployed from Knowledge Studio

### ISSUE THREAD

**Issue by AndreaLupo** [watson-developer-cloud/python-sdk#579]
#### Expected behavior
Does exist a way to pass the model id  of a model trained in Knowledge Studio to be used in NLU to find entities in the text passed?
In curl I have to pass as `--data` a json object containing the model id: 
```
 {
    "text": "Text to be analyzed." ,
    "features": {
      "entities": {
        "model": "MYMODELID"
      },
      "relations": {
        "model": "MYMODELID"
      }
    }
  }
```
#### Actual behavior
Now I'm able to send a request with the default model and obtain the correct response.
The service is hosted in Germany. 
#### Code snippet (Note: Do not paste your credentials)
`url = "https://gateway-fra.watsonplatform.net/natural-language-understanding/api"`

```
service = NaturalLanguageUnderstandingV1(
    version='2018-03-16',
    ## url is optional, and defaults to the URL below. Use the correct URL for your region.
     url=url,
    username=service_username,
    password=service_password)

response = service.analyze(
    text='I work with IBM and it's awesome.',
    features=Features(entities=EntitiesOptions(),
                      keywords=KeywordsOptions())).get_result()

print(json.dumps(response, indent=2))
```
#### python sdk version
API version: `2018-03-16`
#### python version
3.7

**Comment by ehdsouza** [comment]
@AndreaLupo , in python Features is described as a model which is basically a dictionary. If I understand your question correct, you want to pass in the model id? Your code would look like:
```py
response = service.analyze(
    text='Text to be analyzed.',
    features={
        'entities': {
            'model': 'MYMODELID'
        },
        'relations': {
            'model': 'MYMODELID'
        }
    }
).get_result()
```

**Comment by AndreaLupo** [comment]
Thank you, I didn't understand how it works. In this way it runs properly.
