### ISSUE TITLE
Natural Language Understanding - Internal Server Error, Code: 500

### ISSUE THREAD

**Issue by AndreaLupo** [watson-developer-cloud/python-sdk#583]
#### Actual behavior
I receive an internal server error when I try to use a model deployed from Knowledge Studio.
If I use `curl` with the same service it works fine. 
#### Code snippet (Note: Do not paste your credentials)

```
service = NaturalLanguageUnderstandingV1(
    version='2018-03-16',
     url=url,
    username=service_username,
    password=service_password)
response = service.list_models() 
```
#### Output:
![internalservererror](https://user-images.githubusercontent.com/26691887/47139249-9d070380-d2bb-11e8-9927-9e4c2e14c318.PNG)

#### python version
3.7

**Comment by ammardodin** [comment]
Thanks @AndreaLupo for opening the issue. Is this consistently happening, or did it happen intermittently ?

**Comment by ehdsouza** [comment]
@ammardodin, I did see integration tests sometimes failing intermittently with 5xx errors

**Comment by AndreaLupo** [comment]
Hi @ammardodin, I tried right now and the issue persists. As I said, with `curl` the service works as expected.

**Comment by AndreaLupo** [comment]
@ammardodin I tried again this morning and the problem is not solved.

**Comment by ehdsouza** [comment]
@AndreaLupo, are you sure it works with curl? I get the same response with curl:
```sh
curl -G \
-u "{username}":"{password}" "https://gateway.watsonplatform.net/natural-language-understanding/api/v1/models?version=2018-03-16"
```

**Comment by ehdsouza** [comment]
There have been some issues with the service, the team has been notified

**Comment by ehdsouza** [comment]
@AndreaLupo, could you check now. The service team has fixed it at their end.

**Comment by ehdsouza** [comment]
Closing this as it was a service problem and not an issue in the SDK. Feel free to re-open.
