### ISSUE TITLE
Adding compression to microphone-speech-to-text.py

### ISSUE THREAD

**Issue by webcast33** [watson-developer-cloud/python-sdk#587]
I wonder if anyone has succeeded in adding Opus or FLAC compression to the microphone-speech-to-text.py model. The pyaudio package only returns uncompressed chunks, which means the amount of data passed to the STT endpoint is rather large. The microphone-speech-to-text.py program works well, but I'm hoping to reduce or eliminate reaching the 100 Mb recognition request limit, which at a bitrate of 16000 comes every 55 minutes or so. Any guidance on how to do this would be very much appreciated.

Thank you.

**Comment by germanattanasio** [comment]
Hi @webcast33, 

This SDK is just a tiny wrapper on top of the REST/WS API. I would suggest you take a look at https://github.com/faroit/awesome-python-scientific-audio. There could be a package there that you can use along with this SDK.

**Comment by webcast33** [comment]
Thank you for the suggestion. I'll take a look.
