### ISSUE TITLE
Version 2.3.0 wasn't necessary?

### ISSUE THREAD

**Issue by adamchainz** [watson-developer-cloud/python-sdk#589]
According to https://github.com/watson-developer-cloud/python-sdk/releases the release 2.3.0 only all released the addition of `.github/stale.yml`, which afaiu is the config for [probot stale](https://github.com/probot/stale). This just needs to live in the repo, doesn't need to be pushed to PyPI, and shouldn't cause a minor version bump since it has no effect on users. Unless something was missed in the release notes? Basically I am a little confused if I missed something.

**Comment by germanattanasio** [comment]
My bad @adamchainz. I was adding a feature to the repo not the SDK

**Comment by ehdsouza** [comment]
@adamchainz,
 we use semantic release to trigger a release based on the commit messages. The commit: https://github.com/watson-developer-cloud/python-sdk/commit/2f59cbd73107983bc30a996a1b373f00e80f7fdf had a `feat` tag that released the SDK. Sorry for the inconvenience.

**Comment by adamchainz** [comment]
Ok fair enough, thanks for clarifying. Yes 'repo features' shouldn't cause a minor version bump as they signal to users there is some new behaviour, which is how I got confused 😄
