### ISSUE TITLE
SDK AssistantV2 ignores user context variable 

### ISSUE THREAD

**Issue by ishida330** [watson-developer-cloud/python-sdk#597]
#### Expected behavior
1) In AssistantV2, users should be able to set user-defined context variable in "message" API , same as AssistantV1  
2)  In AssistantV2 , option{'return_context': 'true'} should include latest context info in response.

#### Actual behavior
1) Python SDK - AssistantV1 handles user context correctly, but AssistantV2 ignores the user context.
(only "global.system" context like "user_id/time_zone/turn_count" remains)

It seems that the following code(_convert_model in watson_service.py) removes the user variable from the context in `assistant_v2.py`
```py 
    def message(self,
                assistant_id,
                session_id,
                input=None,
                context=None,
                **kwargs):
        ...
        if context is not None:
            context = self._convert_model(context, MessageContext)
```
2) in AssistantV2' ,option{'return_context': 'true'} doesn't return context.

#### Steps to reproduce the problem

1) In dialog, set "Hi, $(myname) ." on welcome box.
![image](https://user-images.githubusercontent.com/9675895/48747648-46745700-ecb7-11e8-8a96-4114b2066d4d.png)
2) set context "myname" and kick "message" API in AssistantV1 -> OK. = "Hi, ishida" returns.
3) same as above in AssistantV2 -> NG. = "Hi, " returns.( context is ignored )

##### AssistantV1(OK)
```py
from watson_developer_cloud import AssistantV1
iam_apikey='XXXXXXXXXX'
workspace_id = 'XXXXXXXX'
assistant = AssistantV1(
    iam_apikey=iam_apikey,
    version='2018-07-10')
response = assistant.message(
    workspace_id=workspace_id,
    context={
        'myname': 'ishida'
    }).get_result()
print(response)
```
```
--> {'intents': [], 'entities': [], 'input': {}, 'output': {'generic': [{'response_type': 'text', 'text': 'Hi, ishida .'}], 'text': ['Hi, ishida .'], 'nodes_visited': ['Opening'], 'log_messages': []}, 'context': {'myname': 'ishida', 'conversation_id': '1d45053c-d7e6-4037-99be-57868397e7a7', 'system': {'initialized': True, 'dialog_stack': [{'dialog_node': 'root'}], 'dialog_turn_counter': 1, 'dialog_request_counter': 1, '_node_output_map': {'Opening': [0]}, 'branch_exited': True, 'branch_exited_reason': 'completed'}, 'no_reservation': True}}
```
##### AssistantV2(NG)
```py
from watson_developer_cloud import AssistantV2
assistant_id = 'XXXXXXXXXX'
iam_apikey='XXXXXXXXXX',
assistant = AssistantV2(
    iam_apikey=iam_apikey,
    version='2018-11-08')
session_id = assistant.create_session(assistant_id).get_result()
message = assistant.message(
    assistant_id,
    session_id["session_id"],
    options={
        'return_context': 'true'
    },
    context={'myname': 'ishida'}
    ).get_result()
print(message)
assistant.delete_session(assistant_id, session_id["session_id"]).get_result()
```
```
--> {'output': {'generic': [{'response_type': 'text', 'text': 'Hi,  .'}], 'intents': [], 'entities': []}}
```
#### python sdk version
watson-developer-cloud   2.4.1
#### python version
Python 3.6.4

**Comment by ehdsouza** [comment]
In https://github.com/watson-developer-cloud/python-sdk/blob/master/watson_developer_cloud/assistant_v2.py#L907, the model in AssistantV2 is defined differently:

Your code should be something like:
```py
    context={ 'global': { 'system': { 'user_id': 'ishida' } }}
```

**Comment by ishida330** [comment]
Hi, ehdsouza. Thank you for the update and advice.  I'm afraid but your suggestion is talking about "system-defined" variables, which is described in [API V2 doc](https://console.bluemix.net/apidocs/assistant-v2#send-user-input-to-assistant), and I'm talking about "user-defined" variables. Suppose I'd like to set user variables, say, "myname" (or "myphone" or anything) to context and sent them to dialog. From what I see so far from code, even if I set "myname" variables to context,  sdk code checks if the variable is either "user_id" or "timezone" or "turn_count"(=system properties) and doesn't allow any other variables( = removes them from the context ), which means , "myname" is not contained in context of the request. I suppose V2 API would allow to set the  user-defined variable as V1 did. ( Or any spec change happend in V2 ?) I'd appreciate your views about this. Thanks !

**Comment by data-henrik** [comment]
I am passing context variables under this "path"; context->skills->main skill->user_defined
This works in the watoolV2.py for sending results of client actions back to WA: https://github.com/data-henrik/watson-conversation-tool

**Comment by germanattanasio** [comment]
Thanks for the tip @data-henrik, we generate the SDKs from the open API specification. I think this is probably a problem in the specification where additional properties were left out and therefore the generator is not creating a sort of key-value object but a concrete class.

**Comment by ishida330** [comment]
Hi, as described in [this stakoverflow entry](https://stackoverflow.com/questions/53404249/watson-assistant-api-v2-manages-the-context-automatically-more-details/53474350#53474350), I could successfully handle the user variables using "context->skills->main skill->user_defined" path.  ( It's working but I'm not sure if this is working as designed/correct spec change as it's not clearly stated in the API V2 doc. If it's correct, then ) I think this is not a SDK code bug, but rather,  a "incomplete/unclear document issue" of API V2 Reference. Please see the document issue I found on above Q&A entry. And about 'options':{'return_context': 'true'}, this should have been 'options':{'return_context': True} (True = boolean) and it worked. Here is the complete code I used. Thanks !
 
`import json
from watson_developer_cloud import AssistantV2

assistant_id = 'xxxx'
iam_apikey='xxxx'

assistant = AssistantV2(
    iam_apikey=iam_apikey,
    version='2018-11-08')
session_id = assistant.create_session(assistant_id).get_result()
print(json.dumps(session_id, indent=2))

message = assistant.message(
    assistant_id,
    session_id["session_id"],
    input={'text':'hello',
        'options':{'return_context': True}
    },
    context={
        "skills": {
            "main skill": {
                "user_defined": {
                    "myname": "ishida"
                }
            }
        }
    }).get_result()
print(message)

assistant.delete_session(assistant_id, session_id["session_id"]).get_result()
`
response is:
`
{'output': {'generic': [{'response_type': 'text', 'text': 'hello! Mr.ishida '}], 'intents': [{'intent': 'General_Greetings', 'confidence': 1}], 'entities': []}, 'context': {'global': {'system': {'turn_count': 1}}, 'skills': {'main skill': {'user_defined': {'myname': 'ishida'}}}}}
`

**Comment by ishida330** [comment]
Sorry for multiple post. Just to let you know, I've also tried Node SDK and the result was the same. Which means, I have to use  "context->skills->**main skill**->user_defined" path in Node SDK. When I modify the "main skill" to other expressions, I couldn't receive the user variables in dialog editor. So I believe, as of now, "**main skill**" is a kind of "reserved keyword" or constant . Then questions came to my mind.
1) The API V2 doc doesn't state about this. It only says "skills->object-> All properties(MessageContextSkill)->user_defined(string).  It doesn't talk about the "**main skill**" at all.
2) The API V2 doc says :"Skills - Contains information specific to particular skills within the Assistant."
and I suppose that Assistant will support multiple skills in the future. If that's right, then Skills section  will allow to contain multiple entries for each skills, but it seems "**main skill**" is the only valid entry as of now, Does this mean that this part of API will change in the future? ( or is there any other mechanism/rules exists , which is not clearly stated in the doc? I feel having skill name entries for each skill would be a natural design. = if the skill name is "CRM", then entries would be  skills->CRM-> user_defined)
