### ISSUE TITLE
skill name workspace name inconsistent

### ISSUE THREAD

**Issue by edwardpwtsoi** [watson-developer-cloud/python-sdk#601]
#### Expected behavior
dashbroad skill name change after _update_workspace_ method is called
#### Actual behavior
dashbroad skill name is not changed but _list_workspaces_ method showing name attributes is changed
#### Steps to reproduce the problem
    try:
        response = assistant.update_workspace(
            workspace_id = <workspace_id>,
            name=<new_name>
        ).get_result()
    except WatsonApiException as ex:
        print ("Method failed with status code " + str(ex.code) + ": " + ex.message)
open dashbroad with browser and navigate to **skill** tag would see the name doesn't change
#### python sdk version
version='2018-09-20'
#### python version
version=3.7.1

**Comment by ehdsouza** [comment]
Closing this as it is not a issue with SDK. Feel free to reopen
