### ISSUE TITLE
STT: Randomly raises `WatsonApiException` for unavailable feature (code 400)

### ISSUE THREAD

**Issue by PaperBag42** [watson-developer-cloud/python-sdk#602]
#### Expected behavior
I am trying to make a `SpeechToTextV1.recognize()` call, for a playlist of Youtube videos. My script waits for the response from each call before making the next one.
I am using the custom language model feature. My account has a trial plan (from a promo code) which should enable the feature.
#### Actual behavior
Every second to fifth call raises a `WatsonApiException` which says that the feature is not available for my account. The same call works just fine when I re-run the script.
```
Traceback (most recent call last):
  File "<input>", line 2, in <module>
  File "C:/Users/user/Documents/stuff/yiaygenerator\stt.py", line 39, in speech_to_text
    return request(file, filename)
  File "C:/Users/user/Documents/stuff/yiaygenerator\stt.py", line 60, in request
    profanity_filter=False
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\watson_developer_cloud\speech_to_text_v1.py", line 387, in recognize
    accept_json=True)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\watson_developer_cloud\watson_service.py", line 495, in request
    info=error_info, httpResponse=response)
watson_developer_cloud.watson_service.WatsonApiException: Error: This feature is not available for the Bluemix Lite plan. Please upgrade to a paid plan to activate this feature: https://console.bluemix.net/catalog/services/speech-to-text, Code: 400 , Information: {'code_description': 'Bad Request'} , X-dp-watson-tran-id: 6df0d2f463292378bd02d14c810c0bad , X-global-transaction-id: 6df0d2f463292378bd02d14c810c0bad
```
I also get a `requests.exceptions.ConnectionError: ('Connection aborted.', ...` sometimes. I am not yet sure if it is related to the problem.
#### Steps to reproduce the problem
I couldn't find any constancy as to when the exception is raised, so repeatadly making `recognize` calls one after another may be the only way to reproduce.
#### Code snippet (Note: Do not paste your credentials)
Setup:
```python
stt = watson.SpeechToTextV1(
	username=environ['WATSON_USERNAME'],
	password=environ['WATSON_PASSWORD']
)
```
I am passing different input to this part for each call:
```python
stt.recognize(
	audio=stream,
	content_type='audio/webm',
	customization_id=environ.get('WATSON_CUSTOMIZATION_ID'),
	timestamps=True,
	profanity_filter=False
).get_result()
```
The full script can be found [here](https://github.com/PaperBag42/yiaygenerator/blob/master/stt.py).
#### python sdk version
2.4.4
#### python version
3.7.0

**Comment by ehdsouza** [comment]
@PaperBag42 did you try using `recognize_using_websocket`? Here is an example: https://github.com/watson-developer-cloud/python-sdk/blob/master/examples/speech_to_text_v1.py#L66

**Comment by germanattanasio** [comment]
@ehdsouza how will that help users using `recognize()`?

**Comment by ehdsouza** [comment]
@germanattanasio I was more thinking about the `requests.exceptions.ConnectionError: ('Connection aborted.', ...` that he reported which sometimes happens when the file is too large.

@PaperBag42 , As far as the `This feature is not available for the Bluemix Lite plan. Please upgrade to a paid plan to activate this feature: https://console.bluemix.net/catalog/services/speech-to-text` error, it looks more like a service error. I have asked the service team about this.

Do you get the same error if you try with a curl?

**Comment by PaperBag42** [comment]
@ehdsouza Hello, thanks for your help.
After making a few calls with curl, I got the same error a couple of times:
```bash
curl -X POST \
    -u "$USER:$PASS" \
    -H "Content-Type: audio/webm" \
    --data-binary @audio.webm \
    "https://stream.watsonplatform.net/speech-to-text/api/v1/recognize?timestamps=true&profanity_filter=false&language_customization_id=$ID"
```
```json
{
   "code_description": "Bad Request", 
   "code": 400, 
   "error": "This feature is not available for the Bluemix Lite plan. Please upgrade to a paid plan to activate this feature: https://console.bluemix.net/catalog/services/speech-to-text"
}
```
However, I didn't get anything similar to the "connection aborted" error when using curl. I tried sending files up to 12,400KB large.
I will soon try it using websockets as well.

**Comment by ehdsouza** [comment]
I got this reply from the service team: 
`
The Watson Speech to Text Lite Plan starts with 100 minutes per month at no cost. All standard features are available with this plan, other than Language & Acoustic Model Customization. When you upgrade to the Standard Plan, you will get access to these customization capabilities.
`
https://www.ibm.com/blogs/bluemix/2017/11/watson-speech-text-text-speech-released-lite-plans/

So, looks like you need to move to standard plan. If you still have doubts I would suggest you create a ticket at : https://console.bluemix.net/unifiedsupport/tickets/add

Also, for `connection aborted`, I think you could also try increasing the `timing` param: http://docs.python-requests.org/en/master/user/quickstart/#timeouts using https://github.com/watson-developer-cloud/python-sdk#configuring-the-http-client-supported-from-v110

**Comment by PaperBag42** [comment]
My service already had the standard plan, so I will create a ticket.
Setting the `timing` did not work since that would take care of a different exception (`requests.exceptions.Timeout`). Using websockets has solved that problem though.

Thanks again!
