### ISSUE TITLE
How to update data register value in Dialog node response using Watson Assistant v1 API using python

### ISSUE THREAD

**Issue by yashpatel001** [watson-developer-cloud/python-sdk#603]
#### Expected behavior
```json
{
  "output": {
    "text": {
      "values": [
        "$(data)good morning"
      ],
      "selection_policy": "sequential"
    },
    "txcom": 1
  }
}
```
#### Code snippet (Note: Do not paste your credentials)
```py
import json

import watson_developer_cloud

# Set up Assistant service.
service = watson_developer_cloud.AssistantV1(
  iam_apikey = {API KEY}, # replace with API key
  version = '2018-09-20'
)
workspace_id = {Workspace id} # replace with workspace ID

user_input = ''
context = {}

# Main input/output loop
while True:

  # Send message to Assistant service.
  response = service.message(
    workspace_id = workspace_id,
    input = {
      'text': user_input
    },
    context = context
  ).get_result()

  # If an intent was detected, print it to the console.
  if response['intents']:
    print('Detected intent: #' + response['intents'][0]['intent'])

  # Print the output from dialog, if any. Assumes a single text response.
  if response['output']['generic']:
    print(response['output']['generic'][0]['text'])

  # Update the stored context with the latest received from the dialog.
  context = response['context']

  # Prompt for next round of input.
  user_input =str(raw_input('>> '))
```

**Comment by yashpatel001** [comment]
How to update dynamically register value available in dialog node response .

**Comment by germanattanasio** [comment]
@yashpatel001 what version of the SDK are you using?

**Comment by ehdsouza** [comment]
@yashpatel001, I am not fully sure I understand your question.

I believe you created an issue in the [java sdk](https://github.com/watson-developer-cloud/java-sdk/issues/1008) as well, did you find the answer in the example folder?

**Comment by yashpatel001** [comment]
@ehdsouza 
input text  = "hii"
{
  "output": {
    "text": {
      "values": [
        "$(data)good morning"
      ],
      "selection_policy": "sequential"
    },
    "txcom": 1
  }
}

through code if i will give input text ("hii") + data register value ("yash")

Response should come
$(data)good morning = 
yash good morning

**Comment by ehdsouza** [comment]
@yashpatel001 could you give me the java code, I could give you the equivalent python

**Comment by yashpatel001** [comment]
HashMap<String,String> abc = new HashMap();
abc.put("data","How are you");

Context co = new Context();
co.put("data","How are You");

newmessageoptions = new newmessageoptions.builder()
             .workspaceid("")
             .input("First message")
             .context(context)
             .build()
messageResponse response = assistant.message(newmessageoptions).execute();
context = response.getContext();

newmessageoptions = new newmessageoptions.builder()
             .workspaceid("")
             .input("Second message")
             .context(co)  // passing data register value how are you
             .build()

**Comment by yashpatel001** [comment]
@ehdsouza please provide for python same

**Comment by yashpatel001** [comment]
@ehdsouza i shared sample code now give python code

**Comment by germanattanasio** [comment]
@yashpatel001 She is on vacation until next week. I will try to take a look but I don't have time this week :(

**Comment by ehdsouza** [comment]
@yashpatel001 here is the equivalent code:
```py
response = assistant.message(
    workspace_id='',
    input={
        'text': 'First message'
    },
    context={
        'data': 'How are you'
    }
).get_result()
print(json.dumps(response, indent=2))

context = response['context']

response = assistant.message(
    workspace_id='',
    input={
        'text': 'Second message'
    },
    context=context
).get_result()
print(json.dumps(response, indent=2))
```

For code help, I would advice you to use: https://stackoverflow.com/questions/tagged/ibm-watson. We open issues here if there are any problems in the SDK.

**Comment by yashpatel001** [comment]
@ehdsouza Thank you so much , it is working fine
