### ISSUE TITLE
Error using "compareAndComply.classify_elements" 

### ISSUE THREAD

**Issue by VarunVerma3** [watson-developer-cloud/python-sdk#616]
#### Expected behavior
Should return a JSON structure 

#### Actual behavior
Getting error: 
```
Method failed with status code 500: The document could not be processed because Error: End-of-File, expected line
```

#### Code snippet (Note: Do not paste your credentials)
```py
response1 = compareAndComply.classify_elements(
  "Test.pdf",
  model_id=None,
  file_content_type="application/pdf",
  filename="Test.pdf")
```

I get
```
Method failed with status code 500: The document could not be processed because Error: End-of-File, expected line
```

If I change `file_content_type` to `text/plain` although which is not supported 
i.e. 

```py
response1 = compareAndComply.classify_elements(
  "Test.pdf",
  model_id=None,
  file_content_type="text/plain",
  filename="Test.pdf")
```

Method failed with status code 415: 
```
The Media Type [text/plain] of the input document is not supported. Auto-correction was attempted, but the auto detected media type [text/plain] is also not supported. Supported Media Types are: application/pdf, image/*, application/vnd.openxmlformats-officedocument.wordprocessingml.document, application/msword.
```

#### python sdk version
2.5.1
#### python version
3.6

**Comment by germanattanasio** [comment]
Thanks a lot for filing this issue! Would you like to write a patch for this? We'd be more than happy to walk you through the steps involved.

**Comment by ehdsouza** [comment]
@VarunVerma3, what error do you get with a curl command?

A `5xx` error from the service would denote an error from the service endpoint. This service is in beta and would need to handle a `application/pdf` correctly. However, could you try not giving a `file_content_type="application/octet-stream"` as it works in the integration tests.

**Comment by VarunVerma3** [comment]
HI Erika,
Sorry some how i missed the mail.
I was not get the data using python sdk but i was curl from python to
develop it. Let me check with your suggestion.
Thanks

**Comment by germanattanasio** [comment]
@ehdsouza I think the user ended up using curl. How can we check if this is a problem in the SDK or not?
