### ISSUE TITLE
Update Workspace Bug - missing "disabled" field in node model for MCR

### ISSUE THREAD

**Issue by lagarwalla** [watson-developer-cloud/python-sdk#618]
SDK Version: Any
Python Version: Any
API: Watson Assistant
Method: update workspace

There is a bug in update_worpskace method. The SDK uses a node model which does not have `disabled` field making the workspace import incorrect in some special scenario. With Curl the issue does not happen.

Steps to Reproduce:
1) Create a new workspace and create a welcome node
2) Turn on `Multiple Responses` in welcome node
3) Turn off `Multiple Responses` in welcome node 
4) Export the JSON
5) Import using python SDK update_worpskace method.
6) In new workspace, the welcome node will have `Multiple Responses` turned on. If you test in chat, the output text will appear twice.

In the exported JSON, there is a `disabled:true` flag for the multiple response node. This disabled flag disappears when imported via SDK.

The root cause seems, the node model does not have the `disabled` field.

**Comment by germanattanasio** [comment]
Hi @lagarwalla, thanks for filing this issue and I'm sorry for you to face this problem.
If you think you can fix this, would you like to write a patch for this? 
I'd be more than happy to walk you through the steps involved.

**Comment by ehdsouza** [comment]
@lagarwalla this is a very good catch. I could reproduce the error.

The exported json has disabled:
```json
    {
      "type": "response_condition",
      "output": {
        "text": {
          "values": [
            "Hello, I’m a demo customer care virtual assistant to show you the basics.  I can help with directions to my store, hours of operation and booking an in-store appointment"
          ],
          "selection_policy": "sequential"
        }
      },
      "parent": "Opening",
      "context": {
        "no_reservation": true
      },
      "disabled": true,
      "metadata": {},
      "dialog_node": "node_2_1545303459070"
    }
```

But the `CreateDialogNode` doesn't seem to be having the `disabled` field. We generate the SDKs based on the swagger specifications given by the service team. Ill get in touch with them

**Comment by lagarwalla** [comment]
Many customers use update_worpskace() method to migrate from Dev to Test/Prod. This can create serious issue where bug is not seen in Dev, but introduced in Test/Prod due to such SDK issue.

I have a suggestion to introduce a new migrate_worpskace() method which does not try to validate the JSON. The main purpose of the method is to migrate exported workspaces and can be used instead of update_workspace(). This will reduce dependency on any JSON model mismatch and SDK versions.

It needs to be clearly documented that update_worpskace() tries to validate the JSON model and is not same as updating via CURL.
