### ISSUE TITLE
Websocket auto reconnect and ping

### ISSUE THREAD

**Issue by georg90** [watson-developer-cloud/python-sdk#623]
How can we enable the Watson STT `recognize_using_websockets` to stay open or auto reconnect?

My thinking was to implement a ping function to keep the websocket open and if it fails anyway to auto connect again.

Is this implemented? I didn't seem to be able to find it :-(

**Comment by germanattanasio** [comment]
The SDK exposes methods for you to detect when there was an error, but it's up to you to design and implement how you deal with them.

Since most of the API calls incur in charges, we can't automate this because it will make it hard for the user to estimate how much money they have to pay.

**Comment by georg90** [comment]
Okay, that makes sense, will look into this. Since the recognize thread is not stopped, any best practice to restart it? Simply delete old thread, create new one isn’t the best way I guess?

**Comment by germanattanasio** [comment]
@ehdsouza can we write an example of how to reconnect to the service when we hit an error?

**Comment by georg90** [comment]
@germanattanasio @ehdsouza Would be great to have a best practice sample! Could be as simple as "if disconnected, reconnect - if timeout, reconnect".

Appreciate the help!

**Comment by georg90** [comment]
And that is how I implemented it:
```
def on_error(self, error):
                self.logger.info('Error received: {}'.format(error))
                self.restartThread()
```
```
def restartThread(self):
        self.recognize_thread = Thread(target=self.recognize_using_websocket)
        self.recognize_thread.start()
```

Thank you @ehdsouza !

**Comment by tilink** [comment]
Hi, I apologize for reopening this issue, but I'm experiencing the same thing. I have written into support and so far haven't gotten any help.

I attempted your solution @georg90 but it doesn't seem to do anything for me. I'm using the examples/microphone-speech-to-text.py - when I add the method you mentioned it doesn't do anything at all that I can tell. I've also attempted to reconnect to the websocket by adding to on_close:

```
def on_close(self):
    print("Connection closed")
    mycallback = MyRecognizeCallback()
    speech_to_text.recognize_using_websocket(audio=audio_source,
                                             content_type='audio/l16; rate=44100',
                                             recognize_callback=mycallback,
                                             interim_results=True
                                             inactivity_timeout=-1)
```


But even though it will say "Connection was successful" and "Service is listening" it doesn't appear to be picking anything up anymore - I'm positive my system is feeding audio to the microphone (I can test in Audacity as well as STT working before). It will continue to get Session time out errors, then connect and listen again. It looks like data is being passed through the internet (from system monitor) but I'm not seeing anything else happening from Watson, no callback functions are running. 

Then when I stop the program I get lots of these errors (depending on how many times I attempted to recreate/start the thread):
```
Unhandled exception in thread started by <function RecognizeListener.send_audio.<locals>.run at 0x7fa58ac950>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/ibm_watson/websocket/recognize_listener.py", line 135, in run
    self.ws_client.send(self.build_closing_message(), websocket.ABNF.OPCODE_TEXT)
  File "/usr/local/lib/python3.5/dist-packages/websocket/_app.py", line 151, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/usr/local/lib/python3.5/dist-packages/websocket/_core.py", line 240, in send
    return self.send_frame(frame)
  File "/usr/local/lib/python3.5/dist-packages/websocket/_core.py", line 265, in send_frame
    l = self._send(data)
  File "/usr/local/lib/python3.5/dist-packages/websocket/_core.py", line 430, in _send
    return send(self.sock, data)
  File "/usr/local/lib/python3.5/dist-packages/websocket/_socket.py", line 114, in send
    raise WebSocketConnectionClosedException("socket is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: socket is already closed.
```

So, restarting the thread doesn't seem to do anything at all, and "reconnecting" to the websocket doesn't seem to continue to get data from Watson.

I don't want to risk the session timing out and not being able to reconnect to Watson, my project will need to run continuously on its own and the program cannot be fully stopped and restarted once we deploy our product. Even sending "silence" or what have you, I don't want to rely on that.

I'm running on Ubuntu 16.04, Python3.5, the most recent version of watson-developer-cloud and pyaudio - I also have the pay-as-you-go standard subscription for TTS. Not sure what other details about my environment you might need?

@ehdsouza Do you have any other advice on reconnecting to the websocket when getting Session timed out? I researched a bit of the socket library that is used here, and it looks like its being run with  [.run_forever](https://github.com/watson-developer-cloud/python-sdk/blob/f3d80287bbf5dfa3d2e55df4af74539106167e2d/ibm_watson/websocket/recognize_listener.py#L65) - should it be closed fully by setting [.keep_running to False](https://stackoverflow.com/a/38995641/6005346)? That could perhaps prevent the errors when exiting the program I'm getting about the websocket already being closed, which I'm wondering if that is preventing the websocket from being reopened and connecting to the STT service again?
