### ISSUE TITLE
ImportError: cannot import name VisualRecognitionV3

### ISSUE THREAD

**Issue by saimouli** [watson-developer-cloud/python-sdk#63]

**Comment by jsstylos** [comment]
Have you installed the latest version of the library? VisualRecogntionV3 was added in release 0.13.0.

**Comment by saimouli** [comment]
Yes, I cloned the latest version. 
n_v3.py", line 4, in <module>
    from watson_developer_cloud import VisualRecognitionV3
ImportError: cannot import name VisualRecognitionV3

**Comment by jsstylos** [comment]
It's likely using a different installed version than the one you cloned. The right way to install an official version is: `pip install --upgrade watson-developer-cloud`. (If you made changes to the clone and want to test them out locally you can do `python setup.py install` in your local directory.)

**Comment by saimouli** [comment]
Thanks that solved the issue
