### ISSUE TITLE
Is it possible to supply labeling metadata with discovery.add_document?

### ISSUE THREAD

**Issue by LTepliakov** [watson-developer-cloud/python-sdk#640]
#### Expected behavior
Is it possible to provide labeling metadata when I add a document?
https://cloud.ibm.com/docs/services/discovery/information-security.html#information-security
If yes, can you please provide a sample request?

**Comment by ehdsouza** [comment]
Based on the documentation, you would need to supply a `X-Watson-Metadata` header with a customer_id.
```python
assistant.set_default_headers({'X-Watson-Metadata': 'customer_id=<value>'})
```

**Comment by LTepliakov** [comment]
Thank you Erika!
It works fine now.
It would be good to add a link to sdk documentation to readme file.
