### ISSUE TITLE
'html_conversion' not available for this plan

### ISSUE THREAD

**Issue by spiderzys** [watson-developer-cloud/python-sdk#643]
I am using "Lite" plan for Compare and Comply.
```py
service=CompareComplyV1(version='2018-10-20',iam_apikey='myKey', url='https://gateway.watsonplatform.net/compare-comply/api')

with open('/Users/yzou/Downloads/Payroll_Deposit_Form_English_2.3.doc', "rb") as fileinfo:
	result=service.convert_to_html(fileinfo,file_content_type="application/msword")
```
Then it throws an exception: `watson_developer_cloud.watson_service.WatsonApiException: Error: The given request could not be processed due to component 'html_conversion' not available for this plan., Code: 426.`   

So do I need a standard plan?

**Comment by ehdsouza** [comment]
@spiderzys,

I asked the question in an internal chat.

**Comment by mahernan** [comment]
`html_conversion` is not available in Lite. This is only enabled in Standard. You can get the converted html from the `element_classification` output in Lite.

**Comment by ehdsouza** [comment]
@spiderzys closing this as @mahernan has answered your question. Feel free to re-open if you have any doubts.
