### ISSUE TITLE
Improve error handling of TextToSpeechV1

### ISSUE THREAD

**Issue by spackows** [watson-developer-cloud/python-sdk#649]
### Overview
When I mistakenly passed Watson Visual Recognition credentials to `TextToSpeechV1`, that function call didn't fail.  Instead, I got failures later on with messages that sent me down the wrong path.

### Expected behavior
Any of the following:
- `TextToSpeechV1` should fail
- If the problem can't be caught in `TextToSpeechV1` itself, return a more accurate error message later

### Actual behavior
The call to `synthesize` failed with the error message
```
Please supply a date version parameter
```

**How to reproduce**
```
vr_iam_apikey = "xxxxx"
vr_url = "https://gateway.watsonplatform.net/visual-recognition/api"

from watson_developer_cloud import TextToSpeechV1
text_to_speech = TextToSpeechV1(
    url = vr_url,
    iam_apikey = vr_iam_apikey
)

with open('hello_world.wav', 'wb') as audio_file:
    audio_file.write(
        text_to_speech.synthesize(
            'Hello world',
            'audio/wav',
            'en-US_AllisonVoice'
        ).get_result().content )
```

### Screenshots
![image](https://user-images.githubusercontent.com/18294329/54698860-65b8af00-4b06-11e9-89a5-1c005f34f5f6.png)

### SDK Version
![image](https://user-images.githubusercontent.com/18294329/54699054-b03a2b80-4b06-11e9-83f9-f6e4b6a38d2c.png)

### Additional information
Python 3.5 in Watson Studio (public) Cloud notebook

**Comment by ehdsouza** [comment]
@spackows , Thanks for creating the issue.
When an instance of a service is created , it doesn't make an api call to the service. So, there is no way for the SDK to handle this type of an error.
