### ISSUE TITLE
v4 Goals

### ISSUE THREAD

**Issue by ehdsouza** [watson-developer-cloud/python-sdk#672]
## Schedule

We plan to release v4 in late September 2019 and a release candidate in early September 2019. This issue will be updated with more specifics on timings.

## Breaking Changes
- [x] As python 2.x will retire in December 2019, we will no longer support it
- [x] Decouple authentication mechanism from service constructor (still under discussion)

---
This issue will be used to track features and changes we want to make in the next major release of this package. We welcome community feedback on these goals - do people want these things? Are there other implementations/packages we should be looking at? Any comments are appreciated!

**Comment by mediumTaj** [comment]
Still active

**Comment by ehdsouza** [comment]
released: https://pypi.org/project/ibm-watson/4.0.0/

Look at the [migration guide](https://github.com/watson-developer-cloud/python-sdk/blob/master/MIGRATION-V4.md)
