### ISSUE TITLE
(Cross-Service) Async IO support

### ISSUE THREAD

**Issue by alex-thewsey-ibm** [watson-developer-cloud/python-sdk#675]
**As a** Modern consuming Python microservice author
**I want** Support for asynchronous (non-blocking) API requests (like NodeJS SDK users already have...)
**So that** My IO-limited apps can scale effectively without overhead & boilerplate of controlling thread pools everywhere

IMHO Python has been a bit late to the concurrency party, but modern frameworks like [Sanic](https://github.com/huge-success/sanic) and [aiohttp](https://github.com/aio-libs/aiohttp) are empowering and forcing developers to explore how much more value we can get out of individual threads - both on web server apps and more batchy data science style workloads.

Today the SDK core [BaseService](https://github.com/IBM/python-sdk-core/blob/master/ibm_cloud_sdk_core/base_service.py) uses the `requests` library, with which requests are *blocking* and prevent the thread from executing other code while waiting for a response.

By swapping this out for an alternative client like `aiohttp` and exposing async interfaces for Watson service calls, it becomes simpler (always subjective) and less thread-heavy to process multiple concurrent requests: e.g. for multi-user web services, or accelerated parallel batch analysis jobs in other already-asynchronous contexts.

Since asynchronicity is not (yet) every Python dev's cup of tea (either because the project is too small/simple to require it, or they already have an established pattern otherwise) it would be ideal to offer both interfaces (a bit like some Node libraries do, although async is more expected there).

At least one other user has already [kind of asked for async support](https://developer.ibm.com/answers/questions/510143/asynchronous-calls-to-watson-assistant-send-messag/) on the DeveloperWorks forum. My own use case is also Assistant (V1), but including admin/model APIs as well as the basic send message. The value naturally extends to the other APIs too though.

**Comment by ehdsouza** [comment]
@alex-thewsey-ibm, thanks for the detailed overview. Would you like to create a PR with an initial pass? The base changes would be in: https://github.com/watson-developer-cloud/python-sdk

**Comment by alex-thewsey-ibm** [comment]
:+1: Tough to find time at the moment but I'll certainly try!

**Comment by germanattanasio** [comment]
Thanks @alex-thewsey-ibm.

**Comment by germanattanasio** [comment]
We are still looking at how to support asynchronous operations, but besides you @alex-thewsey-ibm nobody has asked for this, so it's lower in our priority list.

**Comment by szymonzaczek** [comment]
> We are still looking at how to support asynchronous operations, but besides you @alex-thewsey-ibm nobody has asked for this, so it's lower in our priority list.

I would also greatly benefit from this feature  - @alex-thewsey-ibm in his initial post also mentioned another user that has been asking about it. Moreover, the vast majority of population just accepts the facts as there are, and if something is not supported, they just accept it, without acting upon it. It is 2020 now and asynchronous Python is already considered mature as of 3.8 version, thus it is time to utilize its capabilities.
