### ISSUE TITLE
ON MY DEVICE IT IS NOT WORKING

### ISSUE THREAD

**Issue by theja0473** [watson-developer-cloud/python-sdk#68]
Hi,
I am using watson-developer-cloud service but the text to speech services are not working on my Raspberry Pi 3 Model B. What can I do?

**Comment by jsstylos** [comment]
Hi, if you don't have a specific bug report for the SDK the best way to get help it to create a post on Stackoverflow, The more context you'll give -- specific error messages, whether or not your code works in other environments -- the more likely you'll be to get help.
