### ISSUE TITLE
SDK to handle HTTP Proxy

### ISSUE THREAD

**Issue by vperrinfr** [watson-developer-cloud/python-sdk#681]
Python SDK for Watson Assistant

I would like to be able to configure a HTTTP proxy configuration in the ibm-watson library (I'm using AssistantV1) in order to force all HTTP request to use the proxy. Please find an example of the code: 

> proxyDict = {
>               "http"  : http_proxy,
>               "https" : https_proxy,
>               "ftp"   : ftp_proxy
>             }
> r = requests.get(url, headers=headers, proxies=proxyDict)

BTW, when I use :

> proxies = {'http': 'http://user:pass@host:port’}
> service.set_http_config({'proxies': proxies})

I have that error message

> {
>      "message": "An unexpected error has occurred. : (\"Error: <class 'requests.exceptions.InvalidURL'>\", InvalidURL(LocationParseError('Failed to parse: http://user:password@host:port',),))",
>      "status": 500,
>      "success": false,
>      "type": "UnexpectedException"
> }

Thanks for taking into consideration that evolution

**Comment by ehdsouza** [comment]
Hi, 

Which version of python are you using? I tried the code on `Python 3.6.3` and it worked. Seems like there could be a problem with the version of the library with a smaller python version.

**Comment by vperrinfr** [comment]
Python : 3.6.8

**Comment by ehdsouza** [comment]
@vperrinfr could you provide the version of the `request` library? 
Use `pip list`

**Comment by vperrinfr** [comment]
2.22.0

**Comment by ehdsouza** [comment]
@vperrinfr recently we had a issue reported with `python-core` where the proxy was not set for IAM authentication: https://github.com/IBM/python-sdk-core/issues/31.

Could you see if it was the same problem for you.The version to try would be `ibm-watson==3.4.2`

**Comment by germanattanasio** [comment]
This should be fixed in the latest released
