### ISSUE TITLE
Error: Unauthorized: Access is denied due to invalid credentials, Code: 401

### ISSUE THREAD

**Issue by shsh88** [watson-developer-cloud/python-sdk#682]
I'm getting this error:

ApiException: Error: Unauthorized: Access is denied due to invalid credentials, Code: 401 , X-global-transaction-id: 7ecac92c5d41bae959f499a9

when trying to run the following code which I followed from the example provided in personality_insights_v3.py :
```py
service = PersonalityInsightsV3(
    version='2017-10-13',
    iam_apikey={'My_iam_apikey'},
    url='https://gateway-fra.watsonplatform.net/personality-insights/api'
)

with open('personality-v3.json') as profile_json:
    
    response = service.profile(
        profile_json.read(),
        accept='text/csv',
        csv_headers=True).get_result()

profile = response.content
cr = csv.reader(profile.splitlines())
my_list = list(cr)
for row in my_list:
    print(row)
```
#### python version
3.6

**Comment by ehdsouza** [comment]
Hi,

Could you try with a curl command?

Also, which version of the sdk are you using and make sure the url that you are supplying is correct.

**Comment by shsh88** [comment]
Sorry I made a mistake. I'm using `Python 3.7.3`
I'm getting the same response with curl command, also I made sure of the url again.

```
curl -X POST -u "apikey:myAPIKey" 
--header "Content-Type: application/json" --header "Accept: application/json" 
--data-binary @/home/razan/Dropbox/phd/ECIR20_CLEF/profile.json 
"https://gateway-fra.watsonplatform.net/personality-insights/api/v3/profile?version=2017-10-13/v3/profile?version=2017-10-13&consumption_preferences=true&raw_scores=true"
```

**Comment by ehdsouza** [comment]
This looks more like a service issue. Could you create a ticket: https://cloud.ibm.com/unifiedsupport/supportcenter for help

**Comment by ehdsouza** [comment]
@shsh88 is your issue resolved?

**Comment by bhaskar24** [comment]
@ehdsouza A day before yesterday it worked as expected but now I am also getting the same error i.e, the issue is yet to be resolved.

**Comment by ehdsouza** [comment]
@bhaskar24 did yours work with a curl? you could post in your code snippet
