### ISSUE TITLE
AssistantV1.update_workspace breaks with Autocomplete set in skill

### ISSUE THREAD

**Issue by Nozziel** [watson-developer-cloud/python-sdk#683]
**Overview**
while updating a skill with Autocomplete setting you will get an exception
**Scenario:** get json from development skill and update a test environment skill with the data from development

**Cause** WorkspaceSystemSettings  is missing stuff for spelling_auto_correct.
I think an earlier version of the SDK just ignored this and did not update it's setting (we did it by hand back then) but now it gives an error

**Expected behavior**
Update the Autocomplete setting in the skill being updated

_You could argue that this is a new feature because it never updated this autocomplete, then the expected behavior would be that it should not stop the update (it should just ignore the unknown key)_

**Actual behavior**
exception that stops the update
ValueError: Unrecognized keys detected in dictionary for class WorkspaceSystemSettings: spelling_auto_correct

**How to reproduce**

1. Create a workspace/skill
2. turn on Autocorrection (skill->options) (without turning it on the 'key' will be absent in step 3)
3. use sdk AssistantV1.get_workspace() to get the workspace
3. update the skill with AssistantV1.update_workspace() with basically itself by using the data extracted from step 3's json.

**SDK Version**
tested with 3.2 and 3.3

**Comment by ehdsouza** [comment]
@Nozziel thanks for bringing this to our notice. Recent release we added checks for `badKeys` in the models. Seem like the JSON downloaded from the tooling is not in sync with our API definitions.

**Comment by ehdsouza** [comment]
Hi @Nozziel, in https://pypi.org/project/ibm-watson/4.0.0/ we dont do the conversion from json to model before making the api call, can you see if your issue is resolved?
