### ISSUE TITLE
In the discovery Example, can you show a query that asks a question of the news?

### ISSUE THREAD

**Issue by kabonker** [watson-developer-cloud/python-sdk#692]
The discovery example has the following code as the final step:

```
query_results = discovery.query(
    news_environment_id,
    news_collections[0]['collection_id'],
    filter='extracted_metadata.sha1::f5*',
    return_fields='extracted_metadata.sha1').get_result()
print(json.dumps(query_results, indent=2))
```
But what does this really do?   It seems to produce a bunch of encrypted meta data tags?

`   "id": "HWEnK-F2P37Tf6wS9E0pq_YxqWM_uvTX0ESWEywDohAGuNQg1Pa-Qy84IW27eY5y",
      "result_metadata": {
        "score": 0
      },
      "extracted_metadata": {
        "sha1": "f506a6163e40ed87fcc4f99106c6112a6c95ed9b"
      }`

I was hoping to see a Natural Language Question going the the Query..   Can you enhance your example showing a news question, like "Who is running for President in 2020"?   

I have a discovery service I trained, but could not find the API reference on how to use the DiscoveryV1 query to ask a Natural Language question...

thank you

**Comment by ehdsouza** [comment]
Hi @kabonker, you could try:

```python
result = discovery.query(
    environment_id='system',
    collection_id='news-en',
    natural_language_query='Who is running for President in 2020').get_result()
print(result)
```

**Comment by scienram** [comment]
Cool, it works!
