### ISSUE TITLE
Adding APIs for assistants

### ISSUE THREAD

**Issue by rulai-huajunzeng** [watson-developer-cloud/python-sdk#702]
I was trying to find APIs to list the assistants and get the information about them such as skills etc. but cannot find them. Without those API I have to use the V1 APIs to get the list of workspaces (skills), but still can't get the information about which skills are for specific assistants. Is there a plan to add those APIs or is there any workaround available?

Thanks!

**Comment by nyoscar** [comment]
The V2 authoring APIs are not yet available but they are indeed in our roadmap. For now, only the V1 authoring APIs are available for programmatic changes within a workspace/skill. https://cloud.ibm.com/apidocs/assistant/assistant-v1
