### ISSUE TITLE
Handshake status 403 Forbidden Microphone Speech to Text

### ISSUE THREAD

**Issue by JonhnyDev** [watson-developer-cloud/python-sdk#719]
### Description

I want to make the microphone audio go straight to IBM.
I used the [mp3 file example](https://github.com/watson-developer-cloud/python-sdk/blob/master/examples/speech_to_text_v1.py) and it works

When I use the microphone example I get a `Handshake status 403`

## Steps to reproduce

1. Create an instance of Speech to Text
1. Install the latest version of the SDK
1. Replace the credentials in the microphone example
1. Run the example

### OS
Window? Mac?

### Python version
3.6

**Comment by germanattanasio** [comment]
Please provide a set of reproducible steps.

**Comment by JonhnyDev** [comment]
good .., so I just installed the dependencies you request in the installation guide, put my valid ibm KEY and tried to run the code provided in the examples HERE:
(https://github.com/watson-developer-cloud/python-sdk/blob/master/examples/microphone-speech-to-text.py)

Image pyCharm:
[https://imgur.com/dIB7aIh](url)
(As you can see all the dependencies are installed right ..)


I have no idea how to give more details ... because I did the same basics ... I just installed dependencies-> token-> run..

**Comment by JonhnyDev** [comment]
who can help me?

**Comment by germanattanasio** [comment]
@JonhnyDev I just updated all your comments with more information. I will try to reproduce your issue in a clean environment

**Comment by germanattanasio** [comment]
I just tested the example and it's working. Make sure you have `pyaudio` installed. If you have a mac you may have to do a few things before installing `pyaudio`
```
xcode-select --install
brew remove portaudio
brew install portaudio
```
then
```
pip install pyaudio
```

Replace the `apikey` with your apikey and make sure you don't have a url different than `https://stream.watsonplatform.net/speech-to-text/api` otherwise you need to update the url too.

```
python examples/microphone-speech-to-text.py
```

```
Enter CTRL+C to end recording...
Connection was successful
Service is listening
hello
{'result_index': 0, 'results': [{'final': False, 'alternatives': [{'transcript': 'hello '}]}]}
hello is
{'result_index': 0, 'results': [{'final': False, 'alternatives': [{'transcript': 'hello is '}]}]}
hello is it
{'result_index': 0, 'results': [{'final': False, 'alternatives': [{'transcript': 'hello is it '}]}]}
hello is a test
{'result_index': 0, 'results': [{'final': False, 'alternatives': [{'transcript': 'hello is a test '}]}]}
hello is a test one
{'result_index': 0, 'results': [{'final': False, 'alternatives': [{'transcript': 'hello is a test one '}]}]}
hello is a test one two
{'result_index': 0, 'results': [{'final': False, 'alternatives': [{'transcript': 'hello is a test one two '}]}]}
hello is a test one two three
{'result_index': 0, 'results': [{'final': False, 'alternatives': [{'transcript': 'hello is a test one two three '}]}]}
hello is a test one two three four
{'result_index': 0, 'results': [{'final': False, 'alternatives': [{'transcript': 'hello is a test one two three four '}]}]}
...
```

**Comment by JonhnyDev** [comment]
I found the error in the code does not have the following line "speech_to_text.set_service_url ('https://gateway-wdc.watsonplatform.net/speech-to-text/api')"
to set the url

thanks

**Comment by DaemonHack** [comment]
When getting a handshake status 403 Forbidden,

1. go to your **speech.cfg**   file
<img width="1433" alt="Screenshot 2021-03-29 at 8 55 15 AM" src="https://user-images.githubusercontent.com/47863308/112812409-a12ed200-906c-11eb-903b-f1c159a201fc.png">


2. check if the region is corresponding to the **model**
<img width="1433" alt="Screenshot 2021-03-29 at 8 59 30 AM" src="https://user-images.githubusercontent.com/47863308/112812860-1b5f5680-906d-11eb-9979-365108f206fc.png">
 
3.If not make  sure your **region** is corresponding to **model** in the **def get_url**

``` python

def get_url():
    config = configparser.RawConfigParser()
    config.read('speech.cfg')
    # See
    # https://console.bluemix.net/docs/services/speech-to-text/websockets.html#websockets
    # for details on which endpoints are for each region.
    region = config.get('auth', 'region')
    host = REGION_MAP[region]
    return ("wss://{}/speech-to-text/api/v1/recognize"
            "?model=en-AU_BroadbandModel").format(host)

```
