### ISSUE TITLE
interim_results=False no return

### ISSUE THREAD

**Issue by JonhnyDev** [watson-developer-cloud/python-sdk#720]
I need to return only the final result after the sentence completion, reading the documentation I found the method "interim_results" that if False would return only 1 but when I change to False it returns nothing

https://imgur.com/a/0TWEwY8

how much is true works when false stops working

**Comment by germanattanasio** [comment]
The SDK works as expected. You need to send the stop message or tell the service no more audio will be sent in order to get the final results

**Comment by ArlindKadra** [comment]
> The SDK works as expected. You need to send the stop message or tell the service no more audio will be sent in order to get the final results

Could you please elaborate on the correct way to do it?
This is the example for the speech to text and it shows nothing about a stop message.
https://github.com/watson-developer-cloud/python-sdk/blob/master/examples/speech_to_text_v1.py

`service.send(RecognizeListener.build_closing_message())`

Tried adding this as a really quick fix, now the transcript is getting returned however an error is being thrown for the above. I would suggest showing in the example clearly that a stop message is needed and how that stop message can be given.

**Comment by JonhnyDev** [comment]
> O SDK funciona conforme o esperado. Você precisa enviar a mensagem de parada ou informar ao serviço que não será enviado mais áudio para obter os resultados finais


what stop message? And for that there is a variable that according to the documentation should return only the last message and it does not do this?

**Comment by ehdsouza** [comment]
Hi @JonhnyDev,

You can use the `on_transcription` callback method: https://github.com/watson-developer-cloud/python-sdk/blob/master/ibm_watson/websocket/recognize_abstract_callback.py#L23 for getting the final result.

**Comment by JonhnyDev** [comment]
> Hi @JonhnyDev,
> 
> You can use the `on_transcription` callback method: https://github.com/watson-developer-cloud/python-sdk/blob/master/ibm_watson/websocket/recognize_abstract_callback.py#L23 for getting the final result.

i am sorry , but with i use this? you have a example?

**Comment by ehdsouza** [comment]
@JonhnyDev I believe you want to return only the final result right? If yes, then the `on_transcription` method in the callback is suppose to return the final result.

It is present in the example here: https://github.com/watson-developer-cloud/python-sdk/blob/master/examples/speech_to_text_v1.py#L33
