### ISSUE TITLE
Data Cleaning IBM Watson Personality Insights

### ISSUE THREAD

**Issue by MichaelKLB** [watson-developer-cloud/python-sdk#727]
While working with IBM Watson Personality Insights and looking through the documentation, I have not seen any information regarding the data cleaning process before parsing text to the service.

Assuming I would use tweets as a textual basis, would the service filter out urls, hashtags and mentions? Moreover, does the service recognize emojis in an utf-format?

**Comment by germanattanasio** [comment]
The service will clean the tweets for you
