### ISSUE TITLE
unicode and special characters in fox

### ISSUE THREAD

**Issue by Matthew-Zorumski** [watson-developer-cloud/python-sdk#728]
- [ ] remove unicode from text before analysis

**Comment by mamoonraja** [comment]
@Matthew-Zorumski can you provide more info about the request?

**Comment by Matthew-Zorumski** [comment]
@mamoonraja this was accidentally posted to the Watson developer cloud i meant to put this issue on one of my personal projects, i apologize for any confusion i caused.

**Comment by mamoonraja** [comment]
No worries. Have a great weekend!
