### ISSUE TITLE
LanguageTranslationV2 unexpected key word error

### ISSUE THREAD

**Issue by FabLabEP** [watson-developer-cloud/python-sdk#73]
translate() got an unexpected keyword argument 'model_id'

**Comment by germanattanasio** [comment]
you need to specify the `model_id` or `source` and `target` to call translate

**Comment by germanattanasio** [comment]
are you passing those parameters? what version of the sdk are you using? can you add the code you are using?

**Comment by FabLabEP** [comment]
import json
from watson_developer_cloud import LanguageTranslationV2 as LanguageTranslation

language_translation = LanguageTranslation(
    username='xxxxxxxx', 
    password='xxxxxxxx')
    
translation = language_translation.translate(
    text='blah blah blah',
    model_id='xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx')
print(json.dumps(translation, indent=2, ensure_ascii=False))

**Comment by FabLabEP** [comment]
Specifying source and target works fine.  Error on specific model_id.

**Comment by jsstylos** [comment]
Thanks for the report -- there was a bug in the SDK around the model_id, which will be fixed in the next release.

**Comment by FabLabEP** [comment]
Great!  In the meantime I've found using requests works fine.

`import requests
payload = {'model_id': 'blah blah blah', 'text': text}
r = requests.post(url, auth=('user', 'pw'), data=payload)
print r.status_code
print r.text`

**Comment by jsstylos** [comment]
Fixed
