### ISSUE TITLE
How to end "dummy threads"

### ISSUE THREAD

**Issue by nathannzw** [watson-developer-cloud/python-sdk#734]
Hi I have combined the stt, assistant and tts examples into one code and run them in a loop. Every loop, two new "dummy threads" are created and the previous ones are not deleted. I did not specify using any threads but it seems that they are coming from the websocket speech recognition and synthesize functions. How do I end these threads every end of a loop? Thanks

**Comment by apaparazzi0329** [comment]
Nobody else has seemed to bring up this issue so it is likely very minor. If the problem still exists after upgrading to the latest python and python-sdk versions please feel free to open up a new issue.
