### ISSUE TITLE
TTS No Chinese Voice?

### ISSUE THREAD

**Issue by nathannzw** [watson-developer-cloud/python-sdk#736]
{
  "voices": [
    {
      "gender": "female",
      "supported_features": {
        "custom_pronunciation": true,
        "voice_transformation": false
      },
      "name": "es-US_SofiaVoice",
      "customizable": true,
      "description": "Sofia: North American Spanish (espa\u00f1ol norteamericano) female voice.",
      "language": "es-US",
      "url": "https://api.jp-tok.text-to-speech.watson.cloud.ibm.com/instances/11e4ca94-46d1-4bd8-a574-a1b54d6558c9/v1/voices/es-US_SofiaVoice"
    },
    {
      "gender": "female",
      "supported_features": {
        "custom_pronunciation": true,
        "voice_transformation": false
      },
      "name": "en-US_LisaV2Voice",
      "customizable": true,
      "description": "Lisa: American English female voice. Dnn technology.",
      "language": "en-US",
      "url": "https://api.jp-tok.text-to-speech.watson.cloud.ibm.com/instances/11e4ca94-46d1-4bd8-a574-a1b54d6558c9/v1/voices/en-US_LisaV2Voice"
    },
    {
      "gender": "female",
      "supported_features": {
        "custom_pronunciation": true,
        "voice_transformation": false
      },
      "name": "en-US_EmilyV3Voice",
      "customizable": true,
      "description": "Emily: American English female voice. Dnn technology.",
      "language": "en-US",
      "url": "https://api.jp-tok.text-to-speech.watson.cloud.ibm.com/instances/11e4ca94-46d1-4bd8-a574-a1b54d6558c9/v1/voices/en-US_EmilyV3Voice"
    },
    {
      "gender": "male",
      "supported_features": {
        "custom_pronunciation": true,
        "voice_transformation": false
      },
      "name": "de-DE_DieterVoice",
      "customizable": true,
      "description": "Dieter: Standard German (Standarddeutsch) male voice.",
      "language": "de-DE",
      "url": "https://api.jp-tok.text-to-speech.watson.cloud.ibm.com/instances/11e4ca94-46d1-4bd8-a574-a1b54d6558c9/v1/voices/de-DE_DieterVoice"
    },
    {
      "gender": "female",
      "supported_features": {
        "custom_pronunciation": true,
        "voice_transformation": false
      },
      "name": "it-IT_FrancescaV2Voice",
      "customizable": true,
      "description": "Francesca: Italian (italiano) female voice. Dnn technology.",
      "language": "it-IT",
      "url": "https://api.jp-tok.text-to-speech.watson.cloud.ibm.com/instances/11e4ca94-46d1-4bd8-a574-a1b54d6558c9/v1/voices/it-IT_FrancescaV2Voice"
    },
    {
      "gender": "female",
      "supported_features": {
        "custom_pronunciation": true,
        "voice_transformation": false
      },
      "name": "de-DE_BirgitV3Voice",
      "customizable": true,
      "description": "Birgit: Standard German (Standarddeutsch) female voice. Dnn technology.",
      "language": "de-DE",
      "url": "https://api.jp-tok.text-to-speech.watson.cloud.ibm.com/instances/11e4ca94-46d1-4bd8-a574-a1b54d6558c9/v1/voices/de-DE_BirgitV3Voice"
    },
    {
      "gender": "female",
      "supported_features": {
        "custom_pronunciation": true,
        "voice_transformation": false
      },
      "name": "en-GB_KateV3Voice",
      "customizable": true,
      "description": "Kate: British English female voice. Dnn technology.",
      "language": "en-GB",
      "url": "https://api.jp-tok.text-to-speech.watson.cloud.ibm.com/instances/11e4ca94-46d1-4bd8-a574-a1b54d6558c9/v1/voices/en-GB_KateV3Voice"
    },
    {
      "gender": "male",
      "supported_features": {
        "custom_pronunciation": true,
        "voice_transformation": false
      },
      "name": "en-US_MichaelV3Voice",
      "customizable": true,
      "description": "Michael: American English male voice. Dnn technology.",
      "language": "en-US",
      "url": "https://api.jp-tok.text-to-speech.watson.cloud.ibm.com/instances/11e4ca94-46d1-4bd8-a574-a1b54d6558c9/v1/voices/en-US_MichaelV3Voice"
    },
    {
      "gender": "male",
      "supported_features": {
        "custom_pronunciation": true,
        "voice_transformation": false
      },
      "name": "en-US_HenryV3Voice",
      "customizable": true,
      "description": "Henry: American English male voice. Dnn technology.",
      "language": "en-US",
      "url": "https://api.jp-tok.text-to-speech.watson.cloud.ibm.com/instances/11e4ca94-46d1-4bd8-a574-a1b54d6558c9/v1/voices/en-US_HenryV3Voice"
    },
    {
      "gender": "male",
      "supported_features": {
        "custom_pronunciation": true,
        "voice_transformation": false
      },
      "name": "es-ES_EnriqueVoice",
      "customizable": true,
      "description": "Enrique: Castilian Spanish (espa\u00f1ol castellano) male voice.",
      "language": "es-ES",
      "url": "https://api.jp-tok.text-to-speech.watson.cloud.ibm.com/instances/11e4ca94-46d1-4bd8-a574-a1b54d6558c9/v1/voices/es-ES_EnriqueVoice"
    },
    {
      "gender": "female",
      "supported_features": {
        "custom_pronunciation": true,
        "voice_transformation": false
      },
      "name": "es-LA_SofiaVoice",
      "customizable": true,
      "description": "Sofia: Latin American Spanish (espa\u00f1ol latinoamericano) female voice.",
      "language": "es-LA",
      "url": "https://api.jp-tok.text-to-speech.watson.cloud.ibm.com/instances/11e4ca94-46d1-4bd8-a574-a1b54d6558c9/v1/voices/es-LA_SofiaVoice"
    },
    {
      "gender": "female",
      "supported_features": {
        "custom_pronunciation": true,
        "voice_transformation": false
      },
      "name": "en-US_OliviaV3Voice",
      "customizable": true,
      "description": "Olivia: American English female voice. Dnn technology.",
      "language": "en-US",
      "url": "https://api.jp-tok.text-to-speech.watson.cloud.ibm.com/instances/11e4ca94-46d1-4bd8-a574-a1b54d6558c9/v1/voices/en-US_OliviaV3Voice"
    },
    {
      "gender": "female",
      "supported_features": {
        "custom_pronunciation": true,
        "voice_transformation": false
      },
      "name": "it-IT_FrancescaV3Voice",
      "customizable": true,
      "description": "Francesca: Italian (italiano) female voice. Dnn technology.",
      "language": "it-IT",
      "url": "https://api.jp-tok.text-to-speech.watson.cloud.ibm.com/instances/11e4ca94-46d1-4bd8-a574-a1b54d6558c9/v1/voices/it-IT_FrancescaV3Voice"
    },
    {
      "gender": "male",
      "supported_features": {
        "custom_pronunciation": true,
        "voice_transformation": false
      },
      "name": "es-ES_EnriqueV3Voice",
      "customizable": true,
      "description": "Enrique: Castilian Spanish (espa\u00f1ol castellano) male voice. Dnn technology.",
      "language": "es-ES",
      "url": "https://api.jp-tok.text-to-speech.watson.cloud.ibm.com/instances/11e4ca94-46d1-4bd8-a574-a1b54d6558c9/v1/voices/es-ES_EnriqueV3Voice"
    },
    {
      "gender": "female",
      "supported_features": {
        "custom_pronunciation": true,
        "voice_transformation": false
      },
      "name": "pt-BR_IsabelaV3Voice",
      "customizable": true,
      "description": "Isabela: Brazilian Portuguese (portugu\u00eas brasileiro) female voice. Dnn technology.",
      "language": "pt-BR",
      "url": "https://api.jp-tok.text-to-speech.watson.cloud.ibm.com/instances/11e4ca94-46d1-4bd8-a574-a1b54d6558c9/v1/voices/pt-BR_IsabelaV3Voice"
    },
    {
      "gender": "female",
      "supported_features": {
        "custom_pronunciation": true,
        "voice_transformation": false
      },
      "name": "de-DE_BirgitV2Voice",
      "customizable": true,
      "description": "Birgit: Standard German (Standarddeutsch) female voice. Dnn technology.",
      "language": "de-DE",
      "url": "https://api.jp-tok.text-to-speech.watson.cloud.ibm.com/instances/11e4ca94-46d1-4bd8-a574-a1b54d6558c9/v1/voices/de-DE_BirgitV2Voice"
    },
    {
      "gender": "female",
      "supported_features": {
        "custom_pronunciation": true,
        "voice_transformation": false
      },
      "name": "fr-FR_ReneeV3Voice",
      "customizable": true,
      "description": "Renee: French (fran\u00e7ais) female voice. Dnn technology.",
      "language": "fr-FR",
      "url": "https://api.jp-tok.text-to-speech.watson.cloud.ibm.com/instances/11e4ca94-46d1-4bd8-a574-a1b54d6558c9/v1/voices/fr-FR_ReneeV3Voice"
    },
    {
      "gender": "male",
      "supported_features": {
        "custom_pronunciation": true,
        "voice_transformation": false
      },
      "name": "de-DE_DieterV2Voice",
      "customizable": true,
      "description": "Dieter: Standard German (Standarddeutsch) male voice. Dnn technology.",
      "language": "de-DE",
      "url": "https://api.jp-tok.text-to-speech.watson.cloud.ibm.com/instances/11e4ca94-46d1-4bd8-a574-a1b54d6558c9/v1/voices/de-DE_DieterV2Voice"
    },
    {
      "gender": "female",
      "supported_features": {
        "custom_pronunciation": true,
        "voice_transformation": false
      },
      "name": "en-US_AllisonV2Voice",
      "customizable": true,
      "description": "Allison: American English female voice. Dnn technology.",
      "language": "en-US",
      "url": "https://api.jp-tok.text-to-speech.watson.cloud.ibm.com/instances/11e4ca94-46d1-4bd8-a574-a1b54d6558c9/v1/voices/en-US_AllisonV2Voice"
    },
    {
      "gender": "female",
      "supported_features": {
        "custom_pronunciation": true,
        "voice_transformation": true
      },
      "name": "en-US_LisaVoice",
      "customizable": true,
      "description": "Lisa: American English female voice.",
      "language": "en-US",
      "url": "https://api.jp-tok.text-to-speech.watson.cloud.ibm.com/instances/11e4ca94-46d1-4bd8-a574-a1b54d6558c9/v1/voices/en-US_LisaVoice"
    },
    {
      "gender": "female",
      "supported_features": {
        "custom_pronunciation": true,
        "voice_transformation": false
      },
      "name": "es-LA_SofiaV3Voice",
      "customizable": true,
      "description": "Sofia: Latin American Spanish (espa\u00f1ol latinoamericano) female voice. Dnn technology.",
      "language": "es-LA",
      "url": "https://api.jp-tok.text-to-speech.watson.cloud.ibm.com/instances/11e4ca94-46d1-4bd8-a574-a1b54d6558c9/v1/voices/es-LA_SofiaV3Voice"
    },
    {
      "gender": "female",
      "supported_features": {
        "custom_pronunciation": true,
        "voice_transformation": false
      },
      "name": "de-DE_ErikaV3Voice",
      "customizable": true,
      "description": "Erika: Standard German (Standarddeutsch) female voice. Dnn technology.",
      "language": "de-DE",
      "url": "https://api.jp-tok.text-to-speech.watson.cloud.ibm.com/instances/11e4ca94-46d1-4bd8-a574-a1b54d6558c9/v1/voices/de-DE_ErikaV3Voice"
    },
    {
      "gender": "female",
      "supported_features": {
        "custom_pronunciation": true,
        "voice_transformation": false
      },
      "name": "de-DE_BirgitVoice",
      "customizable": true,
      "description": "Birgit: Standard German (Standarddeutsch) female voice.",
      "language": "de-DE",
      "url": "https://api.jp-tok.text-to-speech.watson.cloud.ibm.com/instances/11e4ca94-46d1-4bd8-a574-a1b54d6558c9/v1/voices/de-DE_BirgitVoice"
    },
    {
      "gender": "female

is there no Chinese voice?

**Comment by mamoonraja** [comment]
Hi, Can you confirm if your output is getting truncated?  I tried `get_voices` and I can see Chinese voices.

![image](https://user-images.githubusercontent.com/16810846/78783995-8a323400-7972-11ea-9241-4007b12d5a3a.png)

**Comment by nathannzw** [comment]
oh dear...i think it is oops. I still can't use the voice without getting a handshake error though...Thanks
