### ISSUE TITLE
ibm WATSON AssistantV1 throwing Error: Forbidden, Code: 403 

### ISSUE THREAD

**Issue by jp820** [watson-developer-cloud/python-sdk#739]
I am trying to use WATSON api Assistant service for conversational flow. But after initialization, when I am trying to get response it gives me following error.

![ibmwatson_assitant_error](https://user-images.githubusercontent.com/19853152/78906960-a979b000-7a9d-11ea-87b4-39cb5de575bc.PNG)

I was following the techniques given in GITHUB repo as follows:

from ibm_watson import AssistantV1
from ibm_cloud_sdk_core.authenticators import IAMAuthenticator

authenticator = IAMAuthenticator('myapikey')
assistant = AssistantV1(
    version='2018-07-10',
    authenticator=authenticator)
assistant.set_service_url('https://gateway.watsonplatform.net/assistant/api')

response = assistant.message(workspace_id='myworkspace_id', input={
    'text': 'What\'s the weather like?'}).get_result()
print(json.dumps(response, indent=2))

I am missing some thing here. Please help me solve this error.

**Comment by mamoonraja** [comment]
Hi, Thanks for opening the issue, can you confirm whether `API key` and `service_url` is set up properly?

**Comment by jp820** [comment]
Hi,
Thanks for immediate response. I figured out two the issues in here - workspace_id and service_url were wrong. There is confusion to set them as repo gives sample code for both Assistant version.

Today, I got response for curl command. 

curl -u "apikey:{my_apikey}" "https://api.eu-gb.assistant.watson.cloud.ibm.com/v1/workspaces/{my_workspaceid}?version=2020-04-01"

Below is the response for curl:
{"name":"myapp","language":"en","metadata":{"api_version":{"major_version":"v1","minor_version":"2020-04-01"}},
"description":"","workspace_id":"my_workspaceid","learning_opt_out":false,"status":"Available"}

But when I tried to use same apikey and workspace id in python api it was giving the mentioned error. I was using **service url** 'https://gateway.watsonplatform.net/assistant/api' mentioned in readme document of repo.

Today I was going through cloud docs for WATSON Assistant. It seems there are different methods and credentials for Assistant versions (v1 and v2). 

Documentation : https://cloud.ibm.com/apidocs/assistant/assistant-v1#introduction

With help of this doc, I found there is naming confusion about the workspace ID, skill id, assistant ID. For API v1 version, workspace ID is the skill ID of the Assistant. This can be located by going to assistant -> skill -> dialog -> API details.

Other major missing thing was which service URL to use for Assistant. After trying 3-4 URLs from documentation and repo, finally found the URL to be used. For Assistant V1, service URL : https://api.eu-gb.assistant.watson.cloud.ibm.com. Also this will change if change the region.

Now I am able to connect and execute the commands for Assistant.

Please find below updated syntax for above code for Assistant V1:

from ibm_watson import AssistantV1
from ibm_cloud_sdk_core.authenticators import IAMAuthenticator
import json 

authenticator = IAMAuthenticator('my_apikey')
assistant = AssistantV1(version='2018-07-10',authenticator=authenticator)
assistant.set_service_url('https://api.eu-gb.assistant.watson.cloud.ibm.com') ## This url will change with your region

response = assistant.message(workspace_id= my_workspace_id, input={
    'text': 'What\'s the weather like?'}).get_result()   ## my_workspace_id will be your skill id of assistant you created. 
print(json.dumps(response, indent=2))

Thanks.

**Comment by mamoonraja** [comment]
Thanks a lot for addressing your pain points, we actively try to improve the experience, so we will take your feedback and try to figure out best possible way to address the issues you experienced.
