### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED error

### ISSUE THREAD

**Issue by Rafi993** [watson-developer-cloud/python-sdk#74]
When I tried to run the examples i get the following error 

![capture](https://cloud.githubusercontent.com/assets/8092120/16410902/3e4d5828-3d42-11e6-95be-39678e03b8b4.PNG)
how do I proceed with this

**Comment by germanattanasio** [comment]
what is the python version you are using?

**Comment by germanattanasio** [comment]
Take a look at this http://stackoverflow.com/questions/27835619/ssl-certificate-verify-failed-error

**Comment by jsstylos** [comment]
Closing this as it appears to be independent from the SDK (a periodic issue with accessing the services themselves).
