### ISSUE TITLE
Unrecognized keys detected in dictionary for class MessageContextGlobal: session_id

### ISSUE THREAD

**Issue by arturoaviles** [watson-developer-cloud/python-sdk#742]
**Overview**

Package 3.4.2 started to return the error message on april 16, 2020:
"Unrecognized keys detected in dictionary for class MessageContextGlobal: session_id" when sending the 2nd message in a conversation with Watson Assistant

**Expected behavior**

The Assistant should return the node with an answer

**Actual behavior**

The package breaks and returns such error message even when there is a session_id and a node with an answer.

**How to reproduce**

Send a message to Watson Assistant, after an answer is returned, send a 2nd message with the same session

**Screenshots**
None

**SDK Version**
3.4.2

**Additional information:**
Official Docker container Python 3.7.0

- Which version of `Python` are you using?
3.7.0

**Additional context**
We will probably check v4

**Comment by mamoonraja** [comment]
Hi @arturoaviles , thanks a lot for opening the issue.  Can you please provide a code snippet for better understanding and confirm whether you have `session id` setup correctly.
