### ISSUE TITLE
Deprecation warning due to invalid escape sequences

### ISSUE THREAD

**Issue by tirkarthi** [watson-developer-cloud/python-sdk#745]
**Overview**

Deprecation warnings are raised due to invalid escape sequences. This can be fixed by using raw strings or escaping the literals. pyupgrade also helps in automatic conversion : https://github.com/asottile/pyupgrade/

**How to reproduce**

```
find . -iname '*.py' | grep -Ev 'test.py' | xargs -P4 -I{} python3.8 -Wall -m py_compile {}
./ibm_watson/visual_recognition_v3.py:197: DeprecationWarning: invalid escape sequence \ 
  """
./ibm_watson/visual_recognition_v3.py:359: DeprecationWarning: invalid escape sequence \ 
  """
```

**Additional information:**
- Which version of `Python` are you using? 3.8

**Comment by mamoonraja** [comment]
@tirkarthi Thanks a lot for opening the issue, we will take a look at the error message.
