### ISSUE TITLE
IBM cloud acess

### ISSUE THREAD

**Issue by israelhtr** [watson-developer-cloud/python-sdk#755]
I have this error when  type the command: 

$ sudo pip install watson-developer-cloud

  ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-JAgAuE/watson-developer-cloud/setup.py'"'"'; __file__='"'"'/tmp/pip-install-JAgAuE/watson-developer-cloud/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-BGAIDz
         cwd: /tmp/pip-install-JAgAuE/watson-developer-cloud/
    Complete output (3 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: No module named setuptools
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by mamoonraja** [comment]
@israelhtr try using `pip install ibm-watson`

**Comment by israelhtr** [comment]
Is the same error

**Comment by mamoonraja** [comment]
which python version and OS version are you using?

**Comment by israelhtr** [comment]
Python 2.7.17
Linux Mint 19.3

**Comment by mamoonraja** [comment]
That's the problem then, we only support Python 3.5 and higher.
