### ISSUE TITLE
ibm-watson is not more compatible with  PyJWT 2.0.0 dependecy

### ISSUE THREAD

**Issue by marvincorreia** [watson-developer-cloud/python-sdk#769]
**Overview**
ibm-watson sdk has a PyJWT dependency and is not working with PyJWT version 2.0.0

**Expected behavior**
No error whit PyJWT 1.x.x versions

**Actual behavior**
jwt.exceptions.DecodeError: It is required that you pass in a value for the "algorithms" argument when calling decode().
/lib/site-packages/jwt/api_jwt.py, line 113, in decode

Stracktrace:
File "C:\Users\marvi.virtualenvs\vabmakersite-yxWtHWbQ\lib\site-packages\ibm_cloud_sdk_core\base_service.py", line 297, in prepare_request
self.authenticator.authenticate(request)
File "C:\Users\marvi.virtualenvs\vabmakersite-yxWtHWbQ\lib\site-packages\ibm_cloud_sdk_core\authenticators\iam_authenticator.py", line 106, in authenticate
bearer_token = self.token_manager.get_token()
File "C:\Users\marvi.virtualenvs\vabmakersite-yxWtHWbQ\lib\site-packages\ibm_cloud_sdk_core\jwt_token_manager.py", line 79, in get_token
self.paced_request_token()
File "C:\Users\marvi.virtualenvs\vabmakersite-yxWtHWbQ\lib\site-packages\ibm_cloud_sdk_core\jwt_token_manager.py", line 124, in paced_request_token
self._save_token_info(token_response)
\lib\site-packages\jwt\api_jwt.py", line 113, in decode
decoded = self.decode_complete(jwt, key, algorithms, options, **kwargs)
File "C:\Users\marvi.virtualenvs\vabmakersite-yxWtHWbQ\lib\site-packages\jwt\api_jwt.py", line 80, in decode_complete
'It is required that you pass in a value for the "algorithms" argument when calling decode().'
jwt.exceptions.DecodeError: It is required that you pass in a value for the "algorithms" argument when calling decode().

**How to reproduce**
import jwt
...
decoded_response = jwt.decode(access_token, verify=False)

**SDK Version**
_Please provide the SDK version here._

**Additional information:**
```
{
  "cryptography": {    
    "version": "3.3.1" 
  },
  "implementation": {  
    "name": "CPython", 
    "version": "3.7.5" 
  },
  "platform": {        
    "release": "10",   
    "system": "Windows"
  },
  "pyjwt": {
    "version": "2.0.0" 
  }
}
```

**Comment by dorringel** [comment]
Getting the same issue here.

Doing some investigation it looks like in PyJWT version 2.0.0 released several days ago the deprecation warning has been altered with an exception being raised, see here:
[https://github.com/jpadilla/pyjwt/search?q=It+is+required+that+you+pass+in+a+value+for+the+%22algorithms%22+argument+when+calling+decode%28%29](url)

Adding: `PyJWT==1.7.1` to the relevant requirements.txt file resolved the issue for us

**Comment by jodmoreira** [comment]
I'm having the same issue. Any expectations of fixing?

**Comment by marvincorreia** [comment]
> Getting the same issue here.
> 
> Doing some investigation it looks like in PyJWT version 2.0.0 released several days ago the deprecation warning has been altered with an exception being raised, see here:
> [https://github.com/jpadilla/pyjwt/search?q=It+is+required+that+you+pass+in+a+value+for+the+%22algorithms%22+argument+when+calling+decode%28%29](url)
> 
> Adding: `PyJWT==1.7.1` to the relevant requirements.txt file resolved the issue for us

Thank u its works for me, u save my day🙌

**Comment by jodmoreira** [comment]
Oh, ok. I just did the same. It`s working here. Thanks

**Comment by marvincorreia** [comment]
> I'm having the same issue. Any expectations of fixing?

if are you using pipenv add
PyJWT = "==1.7.1" in Pipefile before ibm-watson 

Or add PyJWT==1.7.1 in requirements.txt

**Comment by mamoonraja** [comment]
@marvincorreia thanks for opening the issue and providing the fix, we will have the fix for the SDK out today.
