### ISSUE TITLE
New Issue

### ISSUE THREAD

**Issue by jorgebg2016** [watson-developer-cloud/python-sdk#776]
How can I create an own interface to create watson assistants without needing to use the interface of the IBM Cloud?

**Comment by mamoonraja** [comment]
What do you mean by not using the IBM Cloud? Cause you need the IBM Cloud to create the Assistant service.

**Comment by jorgebg2016** [comment]
I need to create my dialog tree without need to log in the IBM Cloud interface to do that. Is it possible? Is there a way to do that?

**Comment by mamoonraja** [comment]
How are you creating it right now? You can use the SDK once you get the API key from IBM Cloud. But you need cloud interface for that atleast.

**Comment by jorgebg2016** [comment]
I am creating the assistant dialog thru IBM Cloud interface, and integrating it using the python client library. I'd like to create it by other way.

**Comment by apaparazzi0329** [comment]
For general Watson SDK Developer help I would recommend joining the Watson Developer Community with this link and ask your questions there. https://wdc-slack-inviter.mybluemix.net/

**Comment by apaparazzi0329** [comment]
Closing as non issue
