### ISSUE TITLE
Custom machine learning model

### ISSUE THREAD

**Issue by vathanathy** [watson-developer-cloud/python-sdk#779]
Hello! So, I want to use my custom machine learning model. In the documentation, I can see how I can do it using curl as you can see below. I am wondering how can I do the same thing using python, especially the part _"model": "your-model-id-here"_? Any help would be appreciated!
![image](https://user-images.githubusercontent.com/58713123/106880395-985cf800-66dc-11eb-9232-c002991bfe89.png)

**Comment by mamoonraja** [comment]
@vathanathy We usually have examples in programming languages provided in API reference, check out https://cloud.ibm.com/apidocs/natural-language-understanding?code=python#analyze

**Comment by vathanathy** [comment]
> @vathanathy We usually have examples in programming languages provided in API reference, check out https://cloud.ibm.com/apidocs/natural-language-understanding?code=python#analyze

You're right. I did see that, but among all the parameters, I don't see any parameter which allows me to specify the model ID like what we can do with _curl_ in the screenshot above (the very last line). I don't know if you understand what I mean?

**Comment by mamoonraja** [comment]
It's part of `EntitiesOptions`:

![image](https://user-images.githubusercontent.com/16810846/106932267-8af83b80-66e5-11eb-9b5f-ccea24f093e1.png)

**Comment by vathanathy** [comment]
@mamoonraja I see it now. My bad! Thank you very much!
