### ISSUE TITLE
AssistantV2 API - time incorrectly resolved when timezone is provided

### ISSUE THREAD

**Issue by dorringel** [watson-developer-cloud/python-sdk#784]
**Overview**
We've been using the AssistantV2 for a long time. We're now adding support for different user timezones by leveraging the 'timezone' argument passed into the message_stateless method, but the time entities are resolved incorrectly.

`message_input_stateless = MessageInputStateless(
            message_type="text",
            text=request,
            intents=intents,
            options=message_input_options_stateless
        )`

`message_context_stateless = MessageContextStateless(
            global_=MessageContextGlobalStateless(
                system=MessageContextGlobalSystem(
                    timezone=timezone,
                    user_id=user_id
                )
            )
        )`
`assistant_result = assistant.message_stateless(
                assistant_id=assistant_id,
                input=message_input_stateless,
                context=message_context_stateless,
                headers=headers).get_result()`

When sending the following text (as a simple example): `I'd like to schedule an appointment at 3pm EST`
and timezone is sent as either "US/Eastern", or "America/New_York".

The response from the assistant:

`{
  "output": {
    "intents": [
      {
        "intent": "BookAnAppointmentWithAMedicalProfessional",
        "confidence": 0.6162809371948242
      }
    ],
    "entities": [
      {
        "entity": "sys-time",
        "location": [
          36,
          46
        ],
        "value": "16:00:00",
        "confidence": 1,
        "metadata": {
          "calendar_type": "GREGORIAN",
          "timezone": "America/New_York"
        },
        "interpretation": {
          "timezone": "America/New_York",
          "specific_hour": 15,
          "granularity": "hour",
          "calendar_type": "GREGORIAN"
        }
      }
    ],
    "generic": []
  },
  "user_id": "559e8fde-f8cc-11ea",
  "context": {
    "global": {
      "system": {
        "timezone": "America/New_York",
        "user_id": "559e8fde-f8cc-11ea",
        "turn_count": 1
      },
      "session_id": "74f769f2-53a7-4d40"
    },
    "skills": {
      "main skill": {
        "user_defined": {
          "time": "16:00:00"
        },
        "system": {
          "state": "eyJzZXNzaW9uX2lkIjoiNzRmNzY5ZjItNTNhNy00ZDQwLWJm"
        }
      }
    }
  }
}`

**Expected behavior**
As EST, "US/Eastern", and "America/New_York" are of the same timezone, I would expect the corrected time to be 15:00:00 (3pm) and not changed to 16:00:00 (4pm)

**Actual behavior**
The resulted time is 16:00:00

**How to reproduce**
Code is above

**SDK Version**
ibm_watson==4.7.1
ibm_cloud_sdk_core==1.7.3

**Additional information:**
- OS: Reproducible on many Unix OSs (didn't try on windows) - MacOS, Linux EC2, etc.
- Which version of `Python` are you using? 3.7.7

**Comment by apaparazzi0329** [comment]
@dorringel Thank you for submitting this issue and my apologizes for the late response time. In this time, have you managed to resolve the issue? If not, I will perform an investigation this week to try to replicate this issue and work on potential solutions.

**Comment by dorringel** [comment]
Hey,

We were not able to resolve the issue. Would appreciate the investigation.

Thanks

**Comment by apaparazzi0329** [comment]
I have a pretty good feeling this issue is related to time differences from daylight savings given that there is only a one hour difference. This does not appear to be a python-sdk issue but I am asking around to see if this a common issue or a possible service bug. I will update you here but feel free to experiment with this knowledge if you haven't already. For instance, changing EST to EDT.
