### ISSUE TITLE
Inconsistent Behavior in the Delete_Document Method of the SDK

### ISSUE THREAD

**Issue by damlagul** [watson-developer-cloud/python-sdk#785]
**Overview**
I am using Watson Discovery v2 on Cloud Pak for Data.
When I try to delete documents from one of the collections in the Watson Discovery using the Watson Python SDK (https://cloud.ibm.com/apidocs/discovery-data?code=python#deletedocument),
The API call returns 200 and “status”: “deleted” as shown in the attached screenshot below. However, sometimes the documents don’t get deleted. There is an instability in the behavior of the delete_document method in the python SDK. Sometimes it works, sometimes it doesn’t work. 

**Expected behavior**
I would expect to delete all the documents that are given to the delete document function in the code.

**Actual behavior**
There is an instability in the behavior of the delete_document method in the python SDK and the API. Sometimes it works, sometimes it doesn’t work. 

**How to reproduce**
Below are the codes that we are using to delete the documents:
SDK:

```
def delete_doc(self, doc_id, project_id=None, coll_id=None):
	if project_id is None:
		project_id = self.project_id
	if coll_id is None:
		coll_id = self.collection_i
	try:
		deletion_status = self.service.delete_document(
			project_id=project_id, collection_id=coll_id, document_id=doc_id
		).get_result()
		logger.info(deletion_status)
	except Exception as e:
		logger.error(
			"Error when deleting the document with id {}: {}".format(doc_id, e)
		)
```

API:

```
def delete_doc(self, doc_id, project_id=None, coll_id=None):
	if project_id is None:
		project_id = self.project_id

	if coll_id is None:
		coll_id = self.collection_id

	try:
		base_env_url = "{host}/discovery/{release}/instances/{instance_id}/api".format(host=settings.WDS_CP4D_CLUSTER_HOST, release=settings.WDS_CP4D_CLUSTER_RELEASE, instance_id=settings.WDS_CP4D_CLUSTER_INSTANCE_ID) 
		url = base_env_url + "/v2/projects/" + self.project_id + "/collections/" + self.collection_id + "/documents/" + doc_id + "?version=2019-11-29"
		bearer_token = 'Bearer ' + settings.WDS_BEARER_TOKEN.get_secret_value()
		headers = {'Authorization': bearer_token, 'Content-Type': 'application/json'}

		response = requests.request("DELETE", url, headers=headers, verify=False, timeout = settings.REQUESTS_TIMEOUT)

		logger.info(response.text) 
	except Exception as e:
		logger.error(
			"Error when deleting the document with id {}: {}".format(doc_id, e)
		)
```

**Screenshots**
Below is the screenshot for one of the examples that the delete_method returned the status as "deleted", but the document wasn't deleted from the collection although we waited for 30-40 minutes.
<img width="596" alt="output_from_the method" src="https://user-images.githubusercontent.com/29822045/115217010-b946be00-a10d-11eb-86ea-541d1a934903.png">

**SDK Version**
Python SDK version 5.1.0

**Additional information:**
Python 3.8
Cloud Pak for Data 3.0.1
Watson Discovery 2.1.4 (2019-11-22)

**Additional context**
The documents are document segments created by splitting the uploaded documents by each occurrence of the subtitles. All uploaded documents are PDFs.

**Comment by apaparazzi0329** [comment]
To be clear, you are seeing the same instability in the API call as you are in the SDK call?

**Comment by damlagul** [comment]
Yes, we saw this inconsistent behavior in the API call as well.

I tested the delete document method both with the **parent_document_id** and the **document_id** and sometimes it was able to delete the docs when we use the document_id.

**Comment by apaparazzi0329** [comment]
As stated in the api docs: `Note: Segments of an uploaded document cannot be deleted individually. Delete all segments by deleting using the parent_document_id of a segment result.` If you are using the `document_id` to delete (or update) segmented documents you may get unexpected results

Link to the docs here: https://cloud.ibm.com/apidocs/discovery-data?code=swift#deletedocument

**Comment by apaparazzi0329** [comment]
If the API call is also not working then this is very unlikely to be an sdk issue as all the sdk does is provide a simple wrapper over API calls

**Comment by apaparazzi0329** [comment]
Closing issue as this is being resolved internally elsewhere
