### ISSUE TITLE
Include full Python client for dialog

### ISSUE THREAD

**Issue by data-henrik** [watson-developer-cloud/python-sdk#79]
I wrote a Python script to manage Watson dialog files from the command line and to test simple chats. The project is available here: https://github.com/data-henrik/henriksDialog

Maybe the dialog_v1.py could be replaced by a client like the above?

**Comment by jsstylos** [comment]
Nice app! Our dialog focus is shifting to the Conversation service, but once the Conversation service supports dialog then a command line app like this might make sense in the utilities folder.

**Comment by data-henrik** [comment]
right now the API for Conversation is very limited

**Comment by jsstylos** [comment]
Yes, but full API access is coming!

**Comment by germanattanasio** [comment]
I'm closing this since we will focus on Conversation moving forward.
