### ISSUE TITLE
Watson stt examples print out bunch of hex data

### ISSUE THREAD

**Issue by daehyunryu** [watson-developer-cloud/python-sdk#808]
**Overview**
Watson stt examples print out bunch of hex data. I have plan to use it with Watson assistant and tts as well.

**Expected behavior**
Expected to get only json output

**How to reproduce**
Clone and ran microphone-speech-to-text.py and speech_to_text_v1.py example.
microphone-speech-to-text.py prints out just bunch of hex code.

**Screenshots**
![image](https://user-images.githubusercontent.com/24998195/139815695-10c076c8-cbe9-488e-b54f-95641c99ca5d.png)

**SDK Version**
ibm-cloud-sdk-core       3.12.0
ibm-watson               5.3.0

**Additional information:**
- OS: Windows 10
- Which version of `Python` are you using? 3.9.1

**Additional context**
I used en-US_Broadband_sample1.wav file from [the link](https://github.com/watson-developer-cloud/speech-to-text-nodejs/tree/master/public/audio)

**Comment by daehyunryu** [comment]
Websocket trace is enabled. ```websocket.enableTrace(True)``` should be commented in recognize_listener.py and synthesize_listener.py?

**Comment by Kaustubh0699** [comment]
Were you able to solve this issue?
I am also not able to get transcript for a streaming audio

**Comment by daehyunryu** [comment]
@Kaustubh0699 
Not really. Do you see same hex data? As temporary workaroud, try again after commenting out ```websocket.enableTrace(True)``` in recognize_listener.py and synthesize_listener.py of watson lib.

**Comment by Kaustubh0699** [comment]
Got a temporary workaround . Try this......
Insert the second line where above where you create the pyaudio stream object. This will disable all the loggings and output would be cleaner.

import logging
logging.disable(logging.CRITICAL)

**Comment by johann-petrak** [comment]
Disabling my own logging is not really an option, why did this not get any attention yet? Having a released library dump out every single byte it sends over to you is really annoying.

**Comment by mediumTaj** [comment]
@apaparazzi0329 can you please take a look

**Comment by apaparazzi0329** [comment]
@johann-petrak I am looking into this issue at the moment. Any suggestions and PRs are greatly appreciated. @daehyunryu your suggestion looks very promising I will look into that first.

**Comment by johann-petrak** [comment]
@apaparazzi0329  as I wrote in #813, this seems to happen because of
https://github.com/watson-developer-cloud/python-sdk/blob/e8a2f1883822f0ad2d655d31a595dbd93f5c81c9/ibm_watson/websocket/recognize_listener.py#L56
It should be sufficient to just remove that line for the release code. 

Note that this line is also present in SynthesizeListener, see https://github.com/watson-developer-cloud/python-sdk/blob/e8a2f1883822f0ad2d655d31a595dbd93f5c81c9/ibm_watson/websocket/synthesize_listener.py#L47
where it probably should also get removed.

**Comment by johann-petrak** [comment]
Here is the PR https://github.com/watson-developer-cloud/python-sdk/pull/814
