### ISSUE TITLE
Pinned down websocket-client==1.1.0

### ISSUE THREAD

**Issue by nbmurphy** [watson-developer-cloud/python-sdk#810]
I work on a Speech Science software development team at [CaptionCall](http://indeo.com/). We have developed a system that can run audio through a selection of various speech-to-text ASRs --- including your `ibm-watson` recognizer. A `pip` requirement for your recognizer is `websocket-client==1.1.0`, pinned to one value. Other recognizers allow for a range of values which adds to the flexibility of our software system, enabling multiple recognizers to be selected during one run, without having to change software environments multiple times.  

Here's an example of one such conflict:
```
ERROR: Cannot install -r requirements_benchmark_asrs.txt (line 10) and rev-ai==2.13.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    ibm-watson 5.3.0 depends on websocket-client==1.1.0
    rev-ai 2.13.0 depends on websocket-client<1.0.0 and >=0.56.0
```

**Comment by cdce8p** [comment]
We at Home Assistant are having a similar issue. Pinned to `==1.1.0` doesn't really work unfortunately.
Would love an update here to open that up, ideally to at `<1.3.0`. The changelog seems to indicate that it should be compatible. [websocket-client - ChangeLog](https://github.com/websocket-client/websocket-client/blob/81fa70d259ce1609b3fb1bf66c8a9bed81a3f28c/ChangeLog#L4)

**Comment by cdce8p** [comment]
This is still an issue

**Comment by epenet** [comment]
This is still an issue: https://github.com/home-assistant/core/pull/86336

**Comment by rutkai** [comment]
@apaparazzi0329 could you please advise on this issue? It'd be great to have a solution for this fixed version.

**Comment by arne-kapell** [comment]
Still an issue for the same reason (homeassistant integration). As this seems to be noticed for almost 2 years now and regarding the presumably low effort for a fix this should be done soon.
