### ISSUE TITLE
Parameter `character_insertion_bias` not implemented

### ISSUE THREAD

**Issue by leonardofurnielis** [watson-developer-cloud/python-sdk#818]
**Overview**
The parameter `character_insertion_bias`  was not implemented in python-sdk. It's already in Watson API documentation.
https://cloud.ibm.com/apidocs/speech-to-text?code=python#recognize
https://cloud.ibm.com/docs/speech-to-text?topic=speech-to-text-parsing#insertion-bias

**Expected behavior**
Expect to attach `character_insertion_bias` as url query parameter using python-sdk.

**Actual behavior**
TypeError: Session.request() got an unexpected keyword argument 'character_insertion_bias'.

**How to reproduce**

```
speech_recognition_results = speech_to_text.recognize(
                audio=audio_file.read(),
                model='',
                content_type='',
                character_insertion_bias=0.3
        ).get_result()
```

**SDK Version**
6.0.0

**Comment by apaparazzi0329** [comment]
This has been implemented in the latest sdk release
