### ISSUE TITLE
Conversation - Unauthorized: Access is denied due to invalid credentials

### ISSUE THREAD

**Issue by ygina** [watson-developer-cloud/python-sdk#82]
`watson_developer_cloud.watson_developer_cloud_service.WatsonException: Unauthorized: Access is denied due to invalid credentials`

I put my credentials in the Conversation example from `examples/conversation_v1.py` and got this error. It looks like `watson_developer_cloud/conversation_v1.py` might be hitting the wrong URL endpoint. (API docs say https://gateway.watsonplatform.net/conversation/api/v1 but the URL in that file does not have the "v1")

**Comment by LaviLaza** [comment]
I got the same error till I explicitly specified the url:

conversation = conversation_v1.ConversationV1('2016-07-11', username = *****, password = *****, url = 'https://gateway.watsonplatform.net/conversation/api')

**Comment by jsstylos** [comment]
This was fixed in 0.16.1 but pip doesn't seem to be picking up the patch release. I'll release 0.17.0 today which should push the update through.
