### ISSUE TITLE
pip install version error

### ISSUE THREAD

**Issue by ellsaking** [watson-developer-cloud/python-sdk#84]
Dear developers,

I am trying to install watson-developer-cloud for python using pip, but an error occurred "Could not find a version that satisfies the requirement watson-developer-cloud (from versions:) 
No matching distribution found for watson-developer-cloud"

I did a little research, it seems like that there is a version issue for pip install if the package is a per-released version. 
I tried to get round using pip install -- pre, but unfortunately it doesn't work.
I am using python 2.7.11 version.

Please let me know whether this is a bug and how to fix it.

Thanks,
Yue

**Comment by jsstylos** [comment]
Is there a requirements.txt file in your directory? What's the pip command you're running?
