### ISSUE TITLE
How does one add content to a solr index using the python sdk?

### ISSUE THREAD

**Issue by Mikemosca** [watson-developer-cloud/python-sdk#88]
How does one add content to a solr index using the python sdk?  Was looking for a way to upload/index documents using the python sdk but could not find any such API.   The corresponding curl command is something like 
```sh
curl -X POST -H "Content-Type: application/json" -u "{username}":"{password}" "https://gateway.watsonplatform.net/retrieve-and-rank/api/v1/solr_clusters/sc1ca23733_faa8_49ce_b3b6_dc3e193264c6/solr/example_collection/update" --data-binary @your_docs.json
```
The API reference for Retrieve and Rank does not contain any python examples so a bit confused here.

**Comment by germanattanasio** [comment]
The [examples](https://github.com/watson-developer-cloud/python-sdk/blob/master/examples/retrieve_and_rank_v1.py#L41) folder has some examples for this particular case.

What you need to do is to get the solr client and use it to index and search for documents.
We use solrpy so you just need to learn how to use that package. See http://pythonhosted.org/solrpy/

**Comment by jsstylos** [comment]
See for example: http://pythonhosted.org/solrpy/reference.html#solr.SolrConnection.add_many
