### ISSUE TITLE
how does one do a search and rank via the python sdk?

### ISSUE THREAD

**Issue by Mikemosca** [watson-developer-cloud/python-sdk#89]
how does one do a search and rank via the python sdk? The standard solr search seems to be handled by the get_pysolr_client() api.  But if I want to used the reranked results in the query how is this accomplished?

For example with curl you can use fcselect and pass in the ranker_id as opposed to using the stand solr query select

**Comment by germanattanasio** [comment]
The answer is similar to #88, in this case you will look at the solr client we use. 

http://pythonhosted.org/solrpy/reference.html#solr.SearchHandler.__call__

**Comment by jsstylos** [comment]
I think we need support for this, since pysolr itself doesn't have support for fcselect and ranker_id.

**Comment by germanattanasio** [comment]
@jsstylos I think `pysolr` supports that.

```python
service = RetrieveAndRankV1(username='USERNAME', password='PASSWORD')
solr = service.get_pysolr_client('CLUSTER_ID', 'COLLECTION_NAME')
results = pysolr_client.search('bananas', search_handler='fcselect', **{ 'ranker_id': 'RANKER_ID' })
```

**Comment by jsstylos** [comment]
That looks like it covers it.
