### ISSUE TITLE
API Reference lacks Python examples

### ISSUE THREAD

**Issue by adam2392** [watson-developer-cloud/python-sdk#94]
https://www.ibm.com/watson/developercloud/speech-to-text/api/v1/?java#recognize_sessionless_nonmp12

On the documentation, it lists that the keywordThreshold is the optional argument, but after much headache, in Python it is actually now keyword_threshold. Perhaps the documentation should be fixed?

**Comment by jsstylos** [comment]
Yes, the documentation needs to be updated with Python information and examples.

**Comment by data-henrik** [comment]
The API reference still lacks many Python examples

**Comment by jeffpk62** [comment]
Sadly, the Speech API reference lacks references to Python entirely.  I really apologize for the delays, but I have unfortunately been assigned to a higher-priority task for the past three weeks.  Python remains high on the list of things to address once I return to the services.  Again, I am very sorry for the delay.

In the interim, parameter names for Python are generally similar to those for Node.js; only Java uses camel-case parameter names.

**Comment by data-henrik** [comment]
I wrote this example for the Conversation API related for workspaces https://github.com/data-henrik/watson-conversation-tool
Maybe something similar could be added to the Conversation service as CLI?

**Comment by germanattanasio** [comment]
That's pretty good @data-henrik
