### ISSUE TITLE
Alchemy vision no longer available

### ISSUE THREAD

**Issue by josepmao** [watson-developer-cloud/python-sdk#98]
Hi Alchemy vision is no available, can be better if remove it from the library, and guide user to use visual recognition v3 instead to avoid confusion.

**Comment by germanattanasio** [comment]
@josepmao I know that AlchemyVision was deprecated but do you know if it still works? If I remove the service then existing users won't be able to use the API with this SDK. I need to know if that's the case

**Comment by josepmao** [comment]
@germanattanasio I think it is gone.  Since it is combination between these 2 services  Alchemy Vision and VR.  But double checking with Alyssa in slack
https://ibm-watson.slack.com/archives/wdc-vision/p1474244739000510

**Comment by germanattanasio** [comment]
I'm closing this because the service will be available for 1 year.

**Comment by josepmao** [comment]
Thanks @germanattanasio.  Get response in slack from Alyssa, we need to keep it for 12 months.
https://ibm-watson.slack.com/archives/wdc-vision/p1474246659000512
