### ISSUE TITLE
the returned output text is always conversation_start response

### ISSUE THREAD

**Issue by AndreiD** [watson-developer-cloud/python-sdk#99]
Greetings,

The bot works great on the "Try it out" inside the console where you design it, but no matter what I send using 
```python
response = conversation.message(workspace_id=workspace_id, message_input={'text': "my question..."})
print(json.dumps(response, indent=2))
```
it returns the default start_conversation answer.

```json
{
  "intents": [
    {
      "confidence": 1,
      "intent": "yes"
    }
  ],
  "entities": [],
  "context": {
    "conversation_id": "dd1b02d1-c714-xxxxxxxxxxx7be",
    "system": {
      "dialog_turn_counter": 1,
      "dialog_stack": [
        "root"
      ],
      "dialog_request_counter": 1
    }
  },
  "output": {
    "log_messages": [],
    "nodes_visited": [
      "node_9_1473588"
    ],
    "text": [
      **"THE START CONVERSATION ANSWER"**
    ]
  },
  "input": {
    "text": "Yes"
  },
  "alternate_intents": false
}
```

so the text array with is returned no matter what I send....

**Comment by AndreiD** [comment]
I found the answer. it's the context variable that needs to be remembered.

# Replace with the context obtained from the initial request
context = {}

workspace_id = '25dfa8a0-0263-471b-8980-317e68c30488'

response = conversation.message(
  workspace_id=workspace_id,
  message_input={'text': 'Turn on the lights'},
  **context=context**
)
------------------------

I would update the example with this, because it's an important piece for getting started and you want to make the devs life as easy as possible when they get started.

**Comment by SirSpidey** [comment]
yes, including the context in the request is included in the example in the API reference: http://www.ibm.com/watson/developercloud/conversation/api/v1/?python#send_message
